### ISSUE TITLE
Gifts - Rollable Attribute Lacks Perception and Appearance

### ISSUE THREAD

**Issue by lordgat** [JohanFalt/Foundry_WoD20#1]
Hi,

The Perception and Appearance stats are missing from the Attribute options when setting what stats to roll for a gift. It appears to allow the 5th Edition stats only.
![image](https://user-images.githubusercontent.com/104499583/165500492-e7a46c84-7c0b-44b2-815c-73c6e0ca7196.png)

I have confirmed that it is set to 20th Edition stats on both the World Setting and the Sheet.
![image](https://user-images.githubusercontent.com/104499583/165500699-0997a20f-4ff4-4664-b752-f8a52d581660.png)
![image](https://user-images.githubusercontent.com/104499583/165500727-2f28957b-601b-4bd0-adb5-b0eac95a6cc0.png)

**Comment by JohanFalt** [comment]
Verifying

**Comment by JohanFalt** [comment]
Confirmed, will be fixed in v1.3.
