### ISSUE TITLE
[Test] Combat Phase in Build: 1.4.5

### ISSUE THREAD

**Issue by Moradion** [JohanFalt/Foundry_WoD20#110]
Combat Test
Situation: Werewolf Chara in homid, against a human / 1 complete combat round
WoD Build: 1.4.5

Show Screenshot 1 ![1_Combat_Phase_0](https://user-images.githubusercontent.com/106521628/173696631-c25f7464-a44e-4039-b887-38336697efe6.JPG)
Start ranged combat with combat tracker and roll for both characters -> Works fine!

Show Screenshot 2 ![2_Combat_Phase_1_Initiative](https://user-images.githubusercontent.com/106521628/173696689-b6f1c7bb-e268-41ee-8987-60dd898a6e03.JPG)
The chat massage for each character don’t show the base attributes, is for equal rolls important.

Show Screenshot 3 ![3_Combat_Phase_2_Attack and Defense](https://user-images.githubusercontent.com/106521628/173696719-04b64b4a-5933-4c3e-9034-01db8685d2e2.JPG)
Manuel attack roll and defiance roll works well.

Show Screenshot 4 ![4_Combat_Phase_3_Damage](https://user-images.githubusercontent.com/106521628/173696742-73d685ab-91d2-4739-ad5f-e2b8bb606220.JPG)
Damage Roll of the sheet don’t count 1, but a failure roll is possible. Only 1 succeed with this roll.
The use of the Roll Attack Checkbox is not clear. Has no connection with the damage roll. And for the sequence, it must also be done before the dodge. 

Show Screenshot 5 ![5_Combat_Phase_3_Damage_Botch](https://user-images.githubusercontent.com/106521628/173696758-5542bc96-29ce-4767-80ff-d595eb7825e4.JPG)
Damage rolls of the sheet make botch’s, too. But with damage and soak roll’s you can’t botch. The result should be only a failure.

Show Screenshot 6 ![6_Combat_Phase_4_Soak with Armor](https://user-images.githubusercontent.com/106521628/173696779-b0f7f5d4-64c3-4960-9343-8c6f26f943b7.JPG)
Soak roll manually with Stamina allow you to change the difficulty, the armor must add manually as modifier for this example 3.

Show Screenshot 7 ![7_Combat_Phase_4_No Damage](https://user-images.githubusercontent.com/106521628/173696902-d47929c3-3e7a-43c9-93ca-76505489e144.JPG)
Stamina soak works well, show of the attribute, selected difficulty, successes and the summary result (Success) correct.

Show Screenshot 8 ![8_Combat_Phase_4_Soak with Armor Shortcut](https://user-images.githubusercontent.com/106521628/173696921-4ce63277-3c39-438c-9ebd-dccc099c3339.JPG)
Use of the Quickroll Soak, with Modifier 3 to add Armor again. Change of the difficulty isn’t possible.

Show Screenshot 9 ![9_Combat_Phase_4_No Damage](https://user-images.githubusercontent.com/106521628/173696949-cd9e897d-df6d-4ac5-b56a-061c424ffb9f.JPG)
Quick Soak don’t shown the attribute, selected difficulty and the summary result (Success or Failure). But otherwise seems correct.

Show Screenshot 10 ![10_Combat_Phase_3_Damage_Failure](https://user-images.githubusercontent.com/106521628/173696971-3a53c96b-dfff-4b0f-9d04-d1530458c589.JPG)
Second Try: Quick Soak roll of the sheet don’t count 1, but a failure roll is possible. Only 1 succeed with this roll. 

Show Screenshot 11 ![11_Combat_Phase_3_Damage_Failure](https://user-images.githubusercontent.com/106521628/173696991-8ba45777-2c9a-4096-b99c-f2270cf69967.JPG)
After some try’s: The summery result should be a failure. That should be shown in the chat text.

Show Screenshot 12 ![12_Combat_Phase_3_Counterattack_Damage_Failure](https://user-images.githubusercontent.com/106521628/173697003-d274ce3b-1f18-4a30-9c85-c9bf013becd1.JPG)
Same result with the werewolf damage roll of the sheet don’t count 1, but a failure roll is possible. Correct result 0 successes, the roll should be shown a failure.

**Comment by JohanFalt** [comment]
Regarding Show Screenshot 4
Damage Roll of the sheet don’t count 1, but a failure roll is possible. Only 1 succeed with this roll.

Is '1's counted in damage rolls? Could be that I have just run a house rule on it though and in that case it should.

**Comment by JohanFalt** [comment]
Regarding:
The use of the Roll Attack Checkbox is not clear. Has no connection with the damage roll. And for the sequence, it must also be done before the dodge. 

A rework of the attack form is coming where I will merge the attack and damage in one flow instead of as it is now - two types of actions with no connection between them.

**Comment by JohanFalt** [comment]
Regarding Screenshot 8

Has been fixed in the coming version as new forms for all rolls has been created.

**Comment by JohanFalt** [comment]
From Screenshot 10
Second Try: Quick Soak roll of the sheet don’t count 1, but a failure roll is possible. Only 1 succeed with this roll.

Same function as Damage in that case I assume.
