### ISSUE TITLE
Mage20 sheet has technology under 'Knowledges' instead of 'Abilities'

### ISSUE THREAD

**Issue by jkb619** [JohanFalt/Foundry_WoD20#125]

**Comment by JohanFalt** [comment]
This is due to it is a Knowledge ability in Werewolf and Vampire and due to how the System is built I’m not sure it can be altered.

**Comment by JohanFalt** [comment]
Possible solution - move all abilities so they exists under {abilites} then have the sorting decide which column the ability end up in.

**Comment by jkb619** [comment]
Or possibly putting Technology in the config area like is done for secondary skills (enable/disable) and 2 different technologies: Technology (M20) and Technology (Everything else)?

Just as a note, took the module out for a test run last night at my local game of Mage20...went over GREAT.  Your work is appreciated.

**Comment by JohanFalt** [comment]
What work will add that in the next 1.5 release.

**Comment by JohanFalt** [comment]
Added technology under skills but only mages can see it and it is added automatically for newly created mages.
Old mages can see it under knowledge and in settings you can remove it but as you do it is removed from the list and you can then only see the skill version.
