### ISSUE TITLE
Wound Penalty and dicepool

### ISSUE THREAD

**Issue by Ringelpiez** [JohanFalt/Foundry_WoD20#126]
Penalty for damage is not included in the dicepool

![FVTT20220618](https://user-images.githubusercontent.com/107757109/174438983-5aa8d9b2-cb5e-4b3e-b633-e6d2320f01ce.png)
.

**Comment by JohanFalt** [comment]
I think the problem here is a general problem with the new roll system which always set damage penalty to 0 for some reason.

will fix right away.
