### ISSUE TITLE
[C20] Changeling the Dreaming Character Sheet

### ISSUE THREAD

**Issue by Ringelpiez** [JohanFalt/Foundry_WoD20#127]
### Top

Name
Player
Chronicle

Court
Legacies
House

Seeming
Kith
Motley

### Attributes
(as usual)

### Talents
Alertness
Athletics
Brawl
Empathy
Expression
Intimidation
**Kenning**
Leadership
Streetwise
Subterfuge

### Skills
Animal Ken
Crafts
Drive
Etiquette
Firearms
Larceny
Melee
Performance
Stealth
Survival

### Knowledges
Academics
Computer
Enigmas
**Gremayre**
Investigation
Law
Medicine
Politics
Science
Technology

### Advantages

Backgrounds

Arts

### Realms
Actor
Fae
Nature
Prop
Scene
Time

Birthright
Frailty

Antithesis

Ravaging Threshold
Musing Threshold

Glamour
Willpower
Nightmare
Banality

[C20_2-Page_Official_Interactive.pdf](https://github.com/JohanFalt/Foundry_WoD20/files/8933600/C20_2-Page_Official_Interactive.pdf)

**Comment by EldritchTranslator** [comment]
In the 'gear' section there could be a section for Treasures, like in the Fetish/Talen section of the Werewolf sheet.

**Comment by JohanFalt** [comment]
I have been reading the rules and started to plan how things should work.

I am planning to have a tab called Dreaming or something where I place everything connecting to their magic - Arts,  Realms and so on. 

Then as you use your magic you can either decide which Realms you add and thus the difficulty is calculated. There should be a check if you wish to go full Unleaching Mode.

Should Bulks be a thing like Rotes are in the MtA sheet?

Arts I picture to handle like I have done with Disciplines. Then able to list your ratings on the Realms. 

Are there more Realms than mentioned in the main book?

Are there limits on how many Arts your character can have?

**Comment by Ringelpiez** [comment]
> Should Bulks be a thing like Rotes are in the MtA sheet?

Unfortunately, I don't know anything about mta.

Casting Cantrips is pretty damn complex because so many things go into it.
- Art levels
- Realm level
- Difficulty: Environment/Banality/Bunk (selection list?)
- Glamour Cost
- two different dice (standard and Nightmare dice)

Probably only a few things can be automated:
- Arts: Check whether Chimerical or Wyrd (cost 1 Glamor).
- Realms: Scene and Time (difficulty +1)
- Realm -1 for Kith Affinity

Or am I wrong?

**Comment by JohanFalt** [comment]
Your reply answered my question - it is (in a way).

I'll add a button for "Casting" and that will open a window which you check what kind of cantrip it is, you add bonuses and such and then roll.

As number of dices is decided on level of realms used (for instance), is the rating of your selected Art always the rating you have. Say you have Autumn 4 and use the power of Autumn 2, does all calculations etc still uses the "value" of 4? 
Want to recall you use Art + the lowest Realm as number of dices rolled.

**Comment by Ringelpiez** [comment]
In your example: 4

C20, p.236: "Callie has Metamorphosis ooo and Actor ooo. She decides to use Metamorphosis o, Sparrows and Nightingales, to teach the lecher a lesson, and Actor ooo, Familiar Face, to target him directly. 
(...), and then rolls Metamorphosis + Actor — a total of six dice."
