### ISSUE TITLE
Inability to Set Renown To 0

### ISSUE THREAD

**Issue by lordgat** [JohanFalt/Foundry_WoD20#13]
Hi,

Currently, it is not possible to reduce the Permanent Renown (of any category) of a character down to 0.
![image](https://user-images.githubusercontent.com/104499583/166292099-469b85ad-eaf0-4fe6-9a75-ae66ec7df354.png)

Right-clicking to remove the dot does not work. Clearing the Temporary Renown track and then trying to clear further does not work.

Current work around requires downloading the character json file and editing manually.

**Comment by JohanFalt** [comment]
Can you do the following:
Open a sheet this is happening. 
Click F12.
The new window should be set in what is called Console.
![Skärmklipp](https://user-images.githubusercontent.com/57871596/166407474-8848076e-ffc7-4bb3-827a-ec6e3cdf042f.PNG)
Click on the "clear" circle and then see if anything red appear in the Console. If anything I would need that.

**Comment by JohanFalt** [comment]
Understand the problem now. Yes setting permanent Renown is not possible at this stage.
