### ISSUE TITLE
Can't resize sheets

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#132]
An opened sheet can be too big for a screen, cutting off (even if the screen has the correct minimum resolution for Foundry). Even when zooming out to see all of it, you can't resize the sheet at all, in length or width. When opening a sheet for the first time it defaults to have the lower end cut off.

Adding 1. a scrolling option for when the sheet cuts off/is smaller and 2. an ability to resize the sheet would greatly improve usability (which is to say, right now I can't use it at all)

**Comment by JohanFalt** [comment]
Min size 1024 x 700
