### ISSUE TITLE
"Feature" is not accepted type for Backgrounds/Merits/Flaws

### ISSUE THREAD

**Issue by ParadoxSong** [JohanFalt/Foundry_WoD20#133]
The Notes section for the mage sheet doesn't allow you to add an item of type Feature to add Backgrounds, Merits, or Flaws. This is what we assume we're supposed to do for it based on the wiki. Weapons and stuff work fine.

**Comment by JohanFalt** [comment]
I can't recreate this problem. Is it named background, merit or flaws items?
I'll add functionallity so you can see that they have been added even if you haven't given them text.

**Comment by ParadoxSong** [comment]
Yeah, as it turns out we were all far too stupid, it works perfectly fine. The only thing close to a bug "bug" here is that the section is empty on the wiki. Sorry about that - we were clearly too gung-ho after finding one bug in the sheet and lost all our brain cells.
