### ISSUE TITLE
(All/Mage) Trusted Players don't have nearly the access levels they should. 

### ISSUE THREAD

**Issue by ParadoxSong** [JohanFalt/Foundry_WoD20#141]
This is somewhat related to the Feature item thing I posted earlier- it turns out that all sorts of stuff just doesn't display for trusted players. My players can't select Type for Feature items, or levels. They can't upload pictures to the character bio, either - Click the top left image simply doesn't do anything for them.  

My trusted players are set up with every permission possible - they're not assistant GMs which prevents them from seeing sheets I haven't shown them, but that's it.

**Comment by JohanFalt** [comment]
Regarding image forcing you being GM that is no problem what so ever to just change to a setting as there are no real harm of anyone changing that.

Problem arises with type and levels. If you change an item being placed on a sheet to something that that sheet can't "see" then it is gone. You can't change it back again. And that is why it is hidden so I can set this regarding the editing permissions of items to a setting itself as well it is just that those that get that permission really needs to know what they are doing.

**Comment by ParadoxSong** [comment]
Yes please! I need this so badly. You are my hero!!
