### ISSUE TITLE
Bug: Cannot add Abilities Specialities to the Character sheet And Blood Pool Cannot Remove 1st point. 

### ISSUE THREAD

**Issue by miker177** [JohanFalt/Foundry_WoD20#145]
Hello, I have noticed that there seems to be an issue where you cannot add Abilities or specialities to the Character Sheet. It allows you to add specialities to the Attributes but not to the Abilities. Also, I have noticed that you cannot remove the 1st point on the Vampire Blood Pool. Thank you for making this wonderful system; looking forward to new releases. 

![image](https://user-images.githubusercontent.com/107895781/174691674-5dfc8e60-1f7f-484e-b940-13f502c04673.png)
![image](https://user-images.githubusercontent.com/107895781/174691709-db8237db-7e70-4484-b1ce-b784e123c78c.png)

**Comment by JohanFalt** [comment]
I will place the blood pool problem in an issue by itself
