### ISSUE TITLE
Create own Abilities and specialities at lower values than 4 

### ISSUE THREAD

**Issue by DrSlimeV** [JohanFalt/Foundry_WoD20#161]
Hi, 
I wanted to ask if it is possible to create an easy way to add new abilities and not rollable specialities at lower values than 4, for example to craft.

**Comment by JohanFalt** [comment]
Would the following be a good design?

Under Settings -> Abilities. Say except just to be able to add abilities as you unlock the sheet you can also alter the name of the abilities so say you can alter Craft to Craft (Carpeting).

**Comment by DrSlimeV** [comment]
That sounds good

**Comment by JohanFalt** [comment]
Lore and Area Knowledge

**Comment by DrSlimeV** [comment]
Hi short question, i tried to use the feature and i think that i´m maybe to tired o.ä. to understand it but how exactly do i change the Abilities names XD

**Comment by JohanFalt** [comment]
That is because this feature hasn’t been implemented yet. It is planned to be in the coming version of v1.7. You are most likely using the newest version of 1.6.

**Comment by DrSlimeV** [comment]
Right examphase Kills my brain XD
