### ISSUE TITLE
Bug: New Update 1.5.8

### ISSUE THREAD

**Issue by miker177** [JohanFalt/Foundry_WoD20#164]
Hello, I have downloaded the new update and it seems it has messed up the Character Sheets. Not running any other mods. Tried the previous version and that is working fine. 
![image](https://user-images.githubusercontent.com/107895781/175315164-fd2c7064-3526-492a-8325-6e61a9218670.png)

**Comment by JohanFalt** [comment]
Releasing v1.5.8

**Comment by JohanFalt** [comment]
released again
