### ISSUE TITLE
Bug: Bone Craft does not apprears in the Skill list after adding it, 

### ISSUE THREAD

**Issue by miker177** [JohanFalt/Foundry_WoD20#175]
Hello, I have noticed that Bone Craft does not appear in the Skill List after I added it. 
![image](https://user-images.githubusercontent.com/107895781/176453109-23f0f613-c64a-4be9-a8ef-8ca2a75d87e9.png)
![image](https://user-images.githubusercontent.com/107895781/176454324-0cd2fb02-1b55-468e-891d-fe5ffaf663db.png)

Also if possible Can you add some missing skills from Dark Ages like - Commerce and Seneschal, etc. There is also one other thing I've noticed - It seems that some skills are missing from the dropdown when you are making rolls for Powers.  Like said Bone Craft, Hearts Wisdom etc.

**Comment by JohanFalt** [comment]
That you can’t see all abilities in the drop box was on purpose as mainly only the main abilities are listed as power abilities.

Or am I missing something how you can use powers? As I said it would be very easy to add them I just couldn’t see a reason to.

**Comment by miker177** [comment]
Personally for the abilities for power, I only care about the Bonecraft for Vicissitude. Though there are some Disciplines or Thaumaturgy in some 3rd party materials that use some of those. But then again, I can have my players roll them from the main page.  And once again thank you for your quick response and all of your hard work.

**Comment by JohanFalt** [comment]
I split this issue up in new ones. 

One for the Dark Ages Abilities which I will add in v1.6
Then the other one regarding Power abilities I'll see when I can plan that in.
