### ISSUE TITLE
Dropdown list alternative

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#187]
This is really more of a prompt than anything, but in the CoD2e system by SoulCake there is a beautiful solution to the issue raised many times that some things are not in a dropdown, and so they aren't usable in a certain sheet. In their sheet while there is a dropdown with suggestions the box remains editable, and so you can add whatever you wish inside, while still providing a guideline to what you may need to insert there, or even to add specifications other than just, say, the bloodline or what.

I have no idea whether that is easy or not to implement, but just in case.
![](https://puu.sh/J9NPL/46d28b86f9.gif)

**Comment by JohanFalt** [comment]
data-koptions
