### ISSUE TITLE
[GEAR] Adding "Magic Item" Item

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_WoD20#19]
Exists in different form and different type of items.

**Comment by EldritchTranslator** [comment]
Apart from Wonders and such from Mage you could also fold the Talens and Fetishes under it, as well as Changeling Treasures when you make them, helping solve the #20 issue too maybe? Just making it an object with a selectable type like with Powers.

**Comment by JohanFalt** [comment]
Solution: Rename Fetish to "Magic Item" and then expand on that.

Need to patch all existing Fetish types in World.
