### ISSUE TITLE
Vampire - Clan, Sect and Path of Enlightenment options resetting

### ISSUE THREAD

**Issue by Salty-Byzrus** [JohanFalt/Foundry_WoD20#199]
There seems to be an issue regarding clans, sects and path of enlightenments selections resetting.

After opening a sheet that had these options filled in previously and unlocking the edit sheet function, sect and clan will reset to show select. If still on this tab when you stop editing the sheet it will correct these options to what had been chosen (though sometimes it saves it when you cease editing on a different tab). 
Likewise, path will reset if you are editing a sheet while on the tab that allows this to be changed. 

However, if a sheet is closed while editable, then it will reset these values on reopneing and then relocking the sheet will not return them to the prior values. This happens whether you have been on the tabs for these values or not.

**Comment by Salty-Byzrus** [comment]
Also seems like if all these values aren't set at the same time, and the sheet is then reopened to change another value, it resets the other. Certainly at least clan and sect being changed reset path of enlightenment to humanity.

**Comment by JohanFalt** [comment]
Will investigate and fix this.
