### ISSUE TITLE
Discipline power level 9 bubbles

### ISSUE THREAD

**Issue by raif11152** [JohanFalt/Foundry_WoD20#208]
Hi, thanks for the ruleset.

The dots for disciplines on the character sheet only go up to 5, but the discipline powers allow for 9 levels.  Can you add 4 more bubbles to the Disciplines page on the character sheet? Probably also need them for paths and rituals, I'd imagine (haven't tried them yet). I've been getting around this by creating a 2nd discipline "Auspex 6+" for example, but it seems inelegant.

Thanks!

**Comment by JohanFalt** [comment]
This was actually a mistake on my part. Will be fixed in the coming version of v1.6.

**Comment by JohanFalt** [comment]
I have tested this in atleast my development version.

If I have a vampire with a number of disciplines and then turn the sheet (under Bio) to generation 4 I get 9 dots on all Disciplines. Does this work in your version as well? Or is it something I have fixed?

![image](https://user-images.githubusercontent.com/57871596/178919033-920d9f8f-62e3-4fcb-9c8e-3c29f5db04c3.png)

**Comment by miker177** [comment]
Hello, the issue what I found with this is. If you add the Discipline to Vampire... lets say of generation 5, the discipline will show only up to level 5. However, if you change the generation to something else and then change it back again it will be shown correctly.
