### ISSUE TITLE
Can't resize sheet windows

### ISSUE THREAD

**Issue by raif11152** [JohanFalt/Foundry_WoD20#209]
Apparently the ability to resize the character sheet window is locked, which makes sense to keep the format likely from breaking. But it makes it complicated on my laptop monitor because the bottom is off the screen and there's no scroll to the sheet. A scroll ability or the ability to resize the vertical height of the window would be awesome.

**Comment by JohanFalt** [comment]
This has been solved in the coming v1.6 where I also let the sheet react to the size of the Foundry window. I'll set this as - solved but if you later as you the new version is released and it still doesn't work as you need, please let me know.
