### ISSUE TITLE
Graphical Bug on 4th and 5th Gen Vampires

### ISSUE THREAD

**Issue by miker177** [JohanFalt/Foundry_WoD20#215]
Hello, there seems to be a bug on the Sheets for 4th and 5th Generation Vampires. It seems that the formatting got a little bit messed up and the dots and text are not aligned correctly. 
![image](https://user-images.githubusercontent.com/107895781/179359130-cea48258-22da-4404-85a6-04fa918df1c7.png)
Compared to 6th Gen and up
![image](https://user-images.githubusercontent.com/107895781/179359170-dc736fc2-b693-43f2-99ab-eb200bc9a57b.png)

**Comment by miker177** [comment]
Update: Just played around with the sheet and if you resize it will correct itself. 
![image](https://user-images.githubusercontent.com/107895781/179359587-da636e9a-ac62-4753-8b73-085294d71b2a.png)
after resizing the sheet. 
![image](https://user-images.githubusercontent.com/107895781/179359599-c6178f7e-9912-4e88-9c78-760a00612333.png)

**Comment by JohanFalt** [comment]
I’ll see how to handle this. The obvious would be to automatically widen the sheet but there are problem with that if the user has a small screen.

It is not hard really mainly it is easy to cause problems.
