### ISSUE TITLE
[Feature Request] Temporary Generation

### ISSUE THREAD

**Issue by RinVindor** [JohanFalt/Foundry_WoD20#217]
Things like Path of Blood allow a Blood Magic user to temporarily lower their Generation from say 10th to 7th, it'd be great to have a spot for a Temp Generation that way the actual generation is always left untouched.

**Comment by JohanFalt** [comment]
Do you have any idea where I could put this? As a modifier beside the Gerneration trait? Like 0 to -5 in a select or simular? Because it can't be connected to the generation select as you need to be able to see what the real value was.
