### ISSUE TITLE
Chimerical damage

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_WoD20#225]

**Comment by JohanFalt** [comment]
Only Changelings and chimerical creaturs/stuff.

Most likely certain types of mortals as well.

**Comment by Ringelpiez** [comment]
"However, the changeling exists in two senses — she has a chimerical aspect and a physical aspect. Both are real, and both
can be harmed in various ways. However, the consequences for these two types of harm are very different." 
(...)
"The myriad dangers of the Dreaming cause chimerical damage. This may be the claws and teeth of a great chimerical beast, the moon-forged blade of an enemy, or whatever else may be conjured. This damage affects only the faerie mien of the changeling, and not her physical body."
(...)
"Physical damage is any damage taken from actions or combat in the Autumn world. This could be anything from a car accident to a fist fight to a gunshot — the mundane world can be a very dangerous place."
(...)
Aggravated Damage: Certain sources of damage, chimerical or physical, cause injuries that are qualitatively worse than others. This includes fire, most attacks by Prodigals (including their teeth and/or claws), acid, toxic waste, and of course cold iron."

C20 p.290

**Comment by Ringelpiez** [comment]
I'm not entirely sure how to handle the / X and * markers. 
We've always handled it in such a way that both chimerical damage and physical damage can be any of the three damage types.

**Comment by JohanFalt** [comment]
They can yes. In a sense the two are the same, the character has two wound trackers where the one showing the worst is the set wound penalty. I’ll see if doing a similar look as the sheet has or I just have two different health areas next to each other.

**Comment by JohanFalt** [comment]
I will handle this by using the same design as the Changeling sheet - two columns.
