### ISSUE TITLE
Use of Editor in textarea

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_WoD20#235]

**Comment by RinVindor** [comment]
Just asking to clarify is this every text area that will have full use of the editor? Such as the 2 text areas for Powers for both Description and System? If so that's awesome I was just about to ask about that since a ton of powers have tables within their System text.

**Comment by JohanFalt** [comment]
Do think I need to really or it will be a short while before a request to add it for another one and so on.
