### ISSUE TITLE
Entry Boxes should resize with Window

### ISSUE THREAD

**Issue by BinMan86** [JohanFalt/Foundry_WoD20#240]
When resizing a window, for example a Power, the Text Entry Boxes do not resize/scale with it. It would be useful if they could do this as it would save scrolling when the boxes contain a large amount of text/lines
<img width="335" alt="itembox" src="https://user-images.githubusercontent.com/49035373/181611955-f481cbcb-cc9e-4f83-b56f-0062ff4ad6ed.png">

**Comment by JohanFalt** [comment]
This couldn't be done in a very good fashion.

**Comment by JohanFalt** [comment]
The new editboxes fixes the problem quite nicesly.

**Comment by JohanFalt** [comment]
![image](https://user-images.githubusercontent.com/57871596/191477579-190dd89c-9fbb-4f3d-84d6-d91190a2f274.png)

Will see what kind of css magic I can pull off.
