### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#241]
There are a few untranslatable strings in the system. Here are the ones I found:
- When creating an object, the kind of object it is cannot be translated;
- When picking the kind of object it is once it's created, the splat the object comes from is not translatable (Vampire for Roads, Werewolf for Gifts, etc);
- In both Changing Breeds and Werewolf sheets, the names of the Ranks are not translated (Cub, Legend, etc);
- In the Changing Breeds Sheet if a CB has Glory, Honor, or Wisdom as its traits, those words aren't translated (this isn't the case in Werewolf where those names are correctly translated);
- In the CB sheet, the Pryio, Factions, Aspects, Tribes are not translatable
- In the Combat tab of all sheets, the Soak tags for damage (Soak A, Soak B, Soak L) can't be translated - you translate 'Soak' but not the letters after, which are different in different languages (ie: Bashing is 'Contundente' in Italian, and so should be a 'C')

**Comment by JohanFalt** [comment]
Problem to translate:

- Shifter type (e.g Ananasi, Corax)
- Item type
- Splat type

Rest will be fixed, the others I will store for later fix (if possible).

**Comment by JohanFalt** [comment]
Requires patching:

- Corax - breed, tribe

**Comment by JohanFalt** [comment]
Need to fix graphics for disabled select boxes.

**Comment by JohanFalt** [comment]
Beside above mentioned about type all should now be translatable.
