### ISSUE TITLE
Jumbled up words in Combat Sheet

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#243]
Since the tags for the various weapon/armor attribute columns can't be widened, they can get out quite jumbled if in translation the words are longer than in English (see example). Also, in the Werewolf and Changing Breeds sheet, where there are the various form names in the 'soak' section, if you don't use the splat font the words come out too close.

![](https://puu.sh/JdSMs/fcfd3091dc.png)

**Comment by JohanFalt** [comment]
Should only happen with Italian and French as those aren't official languages yet.

**Comment by JohanFalt** [comment]
In a sense it works like this. Most languages beyond English have longer words and that is especially with Combat tab. 

So how I fix this is that as the sheet is created I mark the sheet with the language used and then as the graphics is drawn it adapt to the language in question. This is I assume Italian? And Italian doesn't have rules yet as I lack the language files for it. Unsure what sheet I have them for at this stage.
