### ISSUE TITLE
Picture in Shapeshifting tab doesn't cut off

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#248]
If you resize the sheet to be shorter than the picture in the Shapeshifting tab in the Werewolf and Changing Breeds sheet the picture doesn't cut off but instead hangs out.
![](https://puu.sh/JdT8n/6086666e91.png)

**Comment by JohanFalt** [comment]
This graphical error is things we just have to live with.
