### ISSUE TITLE
Add Lost Breeds

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#250]
The Changing Breeds have some Lost Breeds that are now extinct (like the Bunyip, Croatan, and White Howlers). They are: 
- Apis (Minotaurs)
- Camazotz (Werebats)
- Grondr (Wereboars)

 There are also lost sub-races:
- Khara (Sabertooth werecats)
- Okuma (Asian werebears)
- Ao (Turtle Mokolè) 

As well as a lost Aspect of the Ratkin, the Ratkin Bards.
All of this is found in the Changing Breeds 20th book.

**Comment by JohanFalt** [comment]
Connected with https://github.com/JohanFalt/Foundry_WoD20/issues/359

**Comment by JohanFalt** [comment]
Apis p233 Changing Breed, Savage Age vol 1 p27
Camazotz p239 Changing Breed
Grondir p246 Changing Breed, Savage Age vol 1 p49
Khara p248 Changing Breed, Tribebook Khara p26
Ao p250 Changing Breed
