### ISSUE TITLE
[Request] Change shape of crossed dot in edit mode

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#252]
Asking around, my players were quite confused by having an 'extra dot' in edit mode. While this can obviously be solved by just telling them what it is for, I think the issue could be avoided by changing its shape to a simple cross, or something similar, that isn't a dot.

**Comment by JohanFalt** [comment]
I have been removing the clear button for Advantages for the coming version - you clear it be setting it to 1 then clicking it again.

so far I wasn’t thinking to touch traits but maybe should use same function for them as well?

**Comment by JohanFalt** [comment]
Will remove the “clear dot entirely”
