### ISSUE TITLE
Shapechange using the icon on the sheet, melee maneuvers and armor

### ISSUE THREAD

**Issue by jacksands** [JohanFalt/Foundry_WoD20#254]
![image](https://user-images.githubusercontent.com/7229143/182229404-49d0e6e4-518d-4fcf-b8b6-200339f093ce.png)

It would be nice to be able to shapechange just clicking on the simbol at the corner of the sheet.
Also, if clicking on the diff on the shapechange tab could roll the test for change!

Also.. some melee maneuvers have variable dif, can this be add to the dropbox for creating the maneuver?
![image](https://user-images.githubusercontent.com/7229143/182230007-0d05c062-faf1-4885-bd8c-e34fda385b7d.png)

finale, how I use armor items? I created then but it does not seem to affect the roll...

**Comment by JohanFalt** [comment]
Three issues really but let’s see what comes out from it.

Clicking the difficulty of the shape sounds as a good design. I’ll see how I can get that into things.

The armor has so far just been a text not being included in any soaks automatically. In coming version this will be changed as you will be able to equip an armour and thus when roll for soak its bonus will be added.

And last. I’m not sure how changing form by clicking the icon would work. Would you take “next” for as you click it or? Problem is that there are no real easy way to drop down different form as you click it so in a way you could go be as you left click you take next form and so on. Going circle that way.

**Comment by JohanFalt** [comment]
Forgot one - variable diff on weapons.

Easily fixed.

**Comment by jacksands** [comment]
Sorry about many requests on a single issue, I thought it would be better than start many different issues...

about the change shapes the ideia is to be faster and without changing tabs, perhaps clicking on it could opem a dialog window with the shape options to choose...
I play with a stargazer with kailindo... and many maneuvers can change forms... so a quicker way can help me...  but it is just a QoL idea, I don't know if it is that cool for other players.

but just to clarify, opem different issues for different reasons would be better?

tks for your efforts

Erich

**Comment by JohanFalt** [comment]
Can't find a good way to handle shifting by clicking icon. The other issues will fix the issue.
