### ISSUE TITLE
Dark Ages - new knowledge - Linguistics

### ISSUE THREAD

**Issue by Salty-Byzrus** [JohanFalt/Foundry_WoD20#257]
While Linguistics did not make into Dark Ages 20th, it is still worth adding in as an option for people to use. 
The alternative is to slap it onto academics which doesn't mesh perfectly, as people living in multicultural lands, say Transylvania, would regularly run into people with a different primary language to them and likely be able to communicate partially in it with them even if they have never received any kind of formal education.

**Comment by JohanFalt** [comment]
This would be a Secondary Ability?

**Comment by EldritchTranslator** [comment]
In V20 learning new languages and knowing more than one is governed by merits (Languages and others). Not saying that putting Linguistics is a bad idea, just explaining it's obsolete.

**Comment by Salty-Byzrus** [comment]
It is an ability that is under knowledges, from 1st and 2nd ed DA. 

I wouldn't say obsolete since it is still useful, and more so than the merits. The merit  makes you fluent in the language, while linguistics is very useful for partial fluency, understanding dialects, and for reading dead or scholarly languages.

**Comment by JohanFalt** [comment]
I do think in 20th Ed languages is a merit which in itself doesn’t really make sense as that is something you can’t get very easily.

but secondary abilities and/or other traits will handle most versions of languages.
