### ISSUE TITLE
Dark Ages - Fields of Expertise (useful for specialties too)

### ISSUE THREAD

**Issue by Salty-Byzrus** [JohanFalt/Foundry_WoD20#258]
Dark Ages v20 introduced Fields of Expertise as an addition to specialties. For the abilities that required a speciality regardless of rank in v20, like academics, these gave a way to have a specialtity for what aspect of the skill you were good at, while also describing what you knew. An example would be your academics speciality is "research" but your fields of expertise are "Sumerian Archeology" and "Anglo-Saxon England". If you tried to use academics for Nordic Mythology say, your academics would be treated as 0.

I'd suggest adding a large text box in the specialties tab below all the abilities that is free text input, like the background box on the Bio tab, in which all the fields of expertise can be inputted. This would also be useful for normal v20 as would be somewhere to list multiple specialties for one ability, if storyteller permits for things requring one by default, and be easily readable.

**Comment by JohanFalt** [comment]
The first part already is planned for v1.7 and I have an issue for it.

Second part I’ll see.

**Comment by JohanFalt** [comment]
Solved by fixing https://github.com/JohanFalt/Foundry_WoD20/issues/161
