### ISSUE TITLE
[Request] Add roller outside of sheet

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#264]
It's a bit annoying having to open a sheet to make a roll (for example, if I have a random encounter with some npc that doesn't have a sheet prepared and so have to roll the standard 4d10 for an ability roll). I wonder if it's possible to add a button (maybe where the d20 above the chat is?)

An example on how it could be implemented would be like in the CoD2e system.

**Comment by JohanFalt** [comment]
Fully agree on this one coming in v3.1
