### ISSUE TITLE
[Feature Request] Powers Using Various Rolls

### ISSUE THREAD

**Issue by RinVindor** [JohanFalt/Foundry_WoD20#269]
So a good few Powers have various rolls they can make so it'd be great to have a button to add and delete additional rolls. A good example is Song of Serenity from V20 Dark Ages it calls for Manipulation + Intimidation OR Manipulation + Empathy.

**Comment by JohanFalt** [comment]
I have no good solution for this more than you edit the power as you place it to the sheet.

**Comment by RinVindor** [comment]
I was thinking something like a + & - next to the first rolls that create additional entries and then when the next menu appears it gives you a check box of which rolls to make.

![image](https://user-images.githubusercontent.com/12647469/183376303-36505d11-eaa6-4b48-a661-a3aafb1c5842.png)

**Comment by JohanFalt** [comment]
This will complicate the rolling process too much so I will close this task without adding it.

Work-around is to have two different powers depending on how you wish to use it.
