### ISSUE TITLE
[Feature Request] Powers Sometimes Use Roads/Path Ratings

### ISSUE THREAD

**Issue by RinVindor** [JohanFalt/Foundry_WoD20#270]
As the subject states, the Road/Path Rating sometimes gets used as a roll in a Power for Vampires so it'd be great to include that like we have for Willpower and the other traits.

**Comment by JohanFalt** [comment]
![image](https://user-images.githubusercontent.com/57871596/187086396-52d6c482-6287-42c7-a1fe-2d46b00f35be.png)
Reminder
