### ISSUE TITLE
Character sheet don't open in module

### ISSUE THREAD

**Issue by Kolosof** [JohanFalt/Foundry_WoD20#287]
When i click on open character sheet i see this logs in browser:
![image](https://user-images.githubusercontent.com/37359526/187926906-cca2c52d-3a2a-4ed5-9d8d-a375da22f940.png)

**Comment by JohanFalt** [comment]
What version of WoD20 are you using?

**Comment by Kolosof** [comment]
1.6.0 and i update Foudry to 10 version

**Comment by HighKingKota** [comment]
Thank you for looking into this. I started a chronicle yesterday and found that I couldn't access the sheets. I am willing to buy you many coffees for a workaround lol.

**Comment by HighKingKota** [comment]
> When i click on open character sheet i see this logs in browser: ![image](https://user-images.githubusercontent.com/37359526/187926906-cca2c52d-3a2a-4ed5-9d8d-a375da22f940.png)

Kolosof,

Have you at least found a way to get the actor's sheets to show anywhere?

**Comment by JohanFalt** [comment]
Yes the reason is that Foundry has altered how you access the data of the sheet so it need to be altered - everywhere.

The plan is to get the present version I work on done which is about a week of. Then I will start to work on the V10 version. I estimate that the V10 version will be out be end of the month.

**Comment by JohanFalt** [comment]
If you have a back up of your world from V9 of Foundry I recommend you downgrade and use that until I’m done.

**Comment by JohanFalt** [comment]
I have so decided to rearrange my work and will start look into this.

**Comment by JohanFalt** [comment]
Just released v2.0.0 of my World of Darkness 20th System which is the version for Foundry v10, it will NOT work on Foundry v9.

This is a beta release which I need help to test. All from what I can see things should work but I need milage on this to be sure. Depracated that comes up as warning are not interesting in this stage, just pure errors and things that doesn't work.
For details for this version see https://github.com/JohanFalt/Foundry_WoD20/wiki/Changelog#fix-in-200
Any problems or comments leave these at https://github.com/JohanFalt/Foundry_WoD20/issues as usual

And ALWAYS BACKUP YOUR FOUNDRY before updating!

Happy Gaming!!

**Comment by HighKingKota** [comment]
You're a god, thanks. 0.o
