### ISSUE TITLE
(V10 Bug) New character sheets don't open

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#302]
![](https://puu.sh/Jjxtl/d876a4a666.png)

When creating new characters in a newly migrated world, no sheet will open apart from the Spirit sheet.
On creation and when clicking on them, these errors pop up in the console (example werewolf sheet): 

![](https://puu.sh/JjxrI/adbc95226e.png)

The old sheets, correctly migrated, open without issue.

**Comment by JohanFalt** [comment]
Fixed 2.0.1
