### ISSUE TITLE
(V10 Bug) When clicking on a power on a sheet, nothing happens

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#303]
(Tested just with Spirit's Charms since it's the only one that opens)

![](https://puu.sh/Jjxtl/d876a4a666.png)

When clicking the Charm's name on a sheet to open the roll dialogue, this error happens. 

![](https://puu.sh/JjxBd/9973491ffe.png)

**Comment by JohanFalt** [comment]
Fixed 2.0.1
