### ISSUE TITLE
(V10 Bug) Compendia creation

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#304]
![](https://puu.sh/Jjxtl/d876a4a666.png)

There are some issues when creating compendia. Some are present when using the English version, but when using the italian translation (which now translates the dropdown choices too) none work. 

English:
- Card Stack 
- Journal Entry
- Rollable Table
 
When selecting these choices, the creation fails and this error happens (same when using the italian system translation):
![](https://puu.sh/JjxLX/decbcd3b28.png)

**Comment by JohanFalt** [comment]
Are you creating a compendia through Foundry or what are you doing for this?

**Comment by EldritchTranslator** [comment]
I'm creating a compendium through the Foundry interface, just the normal 'Create Compendium' button.

**Comment by JohanFalt** [comment]
Can't duplicate this.

I create a compendium by pressing the Create Compendium button for items. And no problem.

**Comment by EldritchTranslator** [comment]
It happens in the new version too (obviously); here is a gif of the process in case there is some kind of miscommunication from my side. This is from the newest version, no modules active, english language:

![](https://puu.sh/JjNo8/5f09ae7064.gif)

**Comment by JohanFalt** [comment]
Foundry releated: https://github.com/foundryvtt/foundryvtt/issues/8036

**Comment by JohanFalt** [comment]
Fixed in v10.285
https://github.com/foundryvtt/foundryvtt/issues/8036
