### ISSUE TITLE
Increase maximum trait for non-vampire sheets

### ISSUE THREAD

**Issue by goatb** [JohanFalt/Foundry_WoD20#333]
Hello! My group and I are big fans of your WoD sheets, they save us tons of time with our games.

We were wondering if it is possible to have an option to increase the maximum trait values on the non-vampire sheets? Some of our characters have 6+ in Abilities through various means, and being able to have that on the sheet would be helpful.

Either way, thanks for your time and for the hard work you put in for this system!

**Comment by JohanFalt** [comment]
Well thank you.

The function you seek exists I just haven’t described it in the documentation, I will.

What you do is go to the sheet’s settings. That is the cog wheel up to the right. Go to the section Attributes and you will see an area with the attributes. Depending on what you want to do you can alter its Max - that will able you to fill in more dots. Or you can add bonus value, that will not add dots but add permanent bonus to the attribute.

**Comment by JohanFalt** [comment]
Or is it mainly the abilities you are referring too?

**Comment by goatb** [comment]
Hi! Thanks for the quick reply.

Yes, we'd like to be able to do that for Abilities, either as a whole or
individually. That would be great.
