### ISSUE TITLE
Bug with abilities

### ISSUE THREAD

**Issue by Araluen124** [JohanFalt/Foundry_WoD20#339]
I can't change the name of existing abilities and i can't add new ones and the Dark Ages abilities disappeared (The name doesn't change on the sheet) (My game was a dark ages one so i'm kinda stuck)
![image_2022-09-18_144340502](https://user-images.githubusercontent.com/104476123/190923360-d900ee90-f285-4d9e-aba3-52c2a8f2889b.png)

**Comment by JohanFalt** [comment]
Found error. Will release an update tomorrow.

**Comment by Araluen124** [comment]
Thanks

**Comment by Araluen124** [comment]
Sorry to annoy but when i tried to change the names of existing abilities, it was less than reliable (For example, i was able to rename Streetwise to Legedermain after 5 tries but i was not able to rename Firearms to Archery)

**Comment by JohanFalt** [comment]
I take a look.

**Comment by JohanFalt** [comment]
Created a new issue about this.

**Comment by JohanFalt** [comment]
Given this was reopened in a new issue I'll close this one.
