### ISSUE TITLE
Newly added Secondary Abilities max dots don't update for lower gen vampires

### ISSUE THREAD

**Issue by Salty-Byzrus** [JohanFalt/Foundry_WoD20#341]
Newly added secondary abilities max trait ratings do not update for vampires that have lower generations than 8. Raising then lowering generation does not fix this either.

If something that was formerly a primary ability was converted into a secondary ability then it still updates correctly, it is only with new ones.

- Done some further testing. Old abilities turned into secondary ones do not update their max trait rating with generation, they stay at what it was set to. Additionally, the same applies for disciplines.

**Comment by Salty-Byzrus** [comment]
Seems to also be an issue with setting dots of Secdondary Abilities, at least on Vampire sheet.

Talents and Skills - It will save what rating you set the secondary ability to but you cannot then set it back to zero.
Knowledges - It will not save what you set the secondary knowledge to, reverting back to 0, or to whatever value it had if it was converted over from an old primary ability.

**Comment by JohanFalt** [comment]
Verified:
Altering generation doesn't change secondary ability max.

**Comment by JohanFalt** [comment]
Given this is three new issues I will split this issue in new ones and set this as done.
