### ISSUE TITLE
Editing Vampire Sheet Bio on Google Chrome

### ISSUE THREAD

**Issue by Salty-Byzrus** [JohanFalt/Foundry_WoD20#342]
When set to enable edits on the bio page for a vampire (using Google Chrome) the appearance box is always open for editing and saving as per the below screenshot. 
The main issue is this has meant that data inputted into the Apperance box won't save (I have clicked the save button), once the sheet is no longer editable that text input is deleted.
The second issue is that this means one has to click and hold mouse down when adjusting generation, as otherwise you are kicked out of the drop down box.

![image](https://user-images.githubusercontent.com/101959495/191022009-9e147844-f66d-4d1d-be08-f82394a18a11.png)

**Comment by JohanFalt** [comment]
I create a second issue for the problem with selecting generation.

**Comment by JohanFalt** [comment]
This first one is a bit bigger so I will see what I can do for that one in tomorrows release.

**Comment by JohanFalt** [comment]
Apparently this is a "feature" of Foundry's edit boxes and they work like that.
