### ISSUE TITLE
[Feature Request] Support for Buffs and Debuffs

### ISSUE THREAD

**Issue by RinVindor** [JohanFalt/Foundry_WoD20#352]
Currently you can't effectively apply or track buffs and debuffs, from spells, powers, or abilities (like Kindred such as Tzimisce or Gangrel changing shape).

It'd be great to have a Active Effects / Buffs & Debuffs tab on all character sheets that helps track what is what.

**Comment by JohanFalt** [comment]
One solution would be to add these buffs on the power itself. Problem with that would be that some powers have more than one buff and Foundry doesn’t support such thing very well.

The other solution I can think of is to have certain Buff Traits you can add to the sheet and these you can set as active or not. Not sure where to place them, in the power area maybe of the sheet.

**Comment by Kad-Caiel** [comment]
Maybe in the upper right corner, like Werewolf active Form. 
Or in combat tab, left to health, (the more "technical" tab).
