### ISSUE TITLE
Changing Breeds sheets are broken

### ISSUE THREAD

**Issue by mnwolfboy** [JohanFalt/Foundry_WoD20#355]
They do not have any of the new features like werewolf sheet but that is okay. However all rites disappeared on changing breeds pages, and you cant give them rites. Reverted back to old version for now. Otherwise look forward to future additions. Keep up the great work. 

=^-^=

**Comment by JohanFalt** [comment]
I'll fix this shortly.

Could you create a list of things you have found Werewolves have and Changing Breeds are lacking and add that as a seperate issue? Thank you.
