### ISSUE TITLE
Changing Breeds Lacking Things List

### ISSUE THREAD

**Issue by mnwolfboy** [JohanFalt/Foundry_WoD20#357]
Changing Breeds does not have a:
Shapeshift Button
Roll for Frenzy Button
Does not have the buttons on Core page (only combat page)
Set Die Modifier on frenzy rolls under settings.

I think that is it. I also have a few requests (unless they are in there and im blind) but ill add that on a separate issue.

**Comment by JohanFalt** [comment]
Shapeshift Button
Roll for Frenzy Button

for later as they have different views and difficulties.
Fixed the rest.
