### ISSUE TITLE
Werewolf Tooltips Still has wierd issue still.

### ISSUE THREAD

**Issue by mnwolfboy** [JohanFalt/Foundry_WoD20#367]
My apologize, I feel like im nagging now haha. We play our campaign and just keep running across things. But just want to make sure I get it reported here none the less.

So she added a flaw to her new character the system was still showing the format coding, but the description portion was fine. Just the system part. As far as we can tell it just does it in flaws. Cant recreate the issue in Merits or Background.

Not that we plan on using it but She for the heck of it tested it in Bloodbounds/Vinculums, Description portion does the format issue but the system does not.

**Comment by JohanFalt** [comment]
No you shouldn’t feel bad of reporting stuff. Especially issues that are pure bugs.

I will get on it.
