### ISSUE TITLE
Suggestion for reorganizing Tabs content

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#371]
How I, personally, would put the tabs (left to right):

### Bio, or Info
Two colums
Small text boxes (one line each)
- Age, Apparent age, Birth date, Birthplace, Death date (vampire, wraiths), Cause of death (wraiths), Gender, Height (human form), Weight (human form), Hair/eyes/marks/scars. 
- Creature-related things (4ex., Sire).

Large boxes
- Derangements (at the right of small boxes).
- Appearance (at the right of small boxes).
- Background (below, full length) - (Background lacks of format tools that Appearance has).

### Main, or Core
- I would add the classic info at the top: name, player, nature, demeanor, concept, clan/tribe… you know, and I would remove them from Bio. Is more a basic or “main” info. Yes, probably you don’t need to check your Clan or name every time, but is more… accessible. I think so.
- I would add a simple separation between Primary and Secondary Abilities. Just a blank line or two, or maybe a section with his headline.
- I would add a button (maybe like the "plus" button to add things, or the pen and paper of "edit") at the left of the first dot, to add/edit Specialities. Specilities shows on tooltip on mouseover over the Atribute/Ability/Sec. Ability. Specialty tab it's no longer needed.
- An option to hide quick roll buttons.

### Advantages (Backgrounds & Merits/Flaws & Other Traits)
An entire tab similar to the actual _Notes_, with headlines a bit bigger.
- I would include a home/haven/caern/freehold/etc. description large box, below all. Or maybe in Bio.
- We can include here “states of being”: derangements, blood bonds, harano, etc.
- In Vampire, it would be great to include a Boons/Prestation section.
- XP, out.

### Powers (Disciplines, Gifts, Cantrips...)
No mayor changes.
- In Vampire, needs to be included a Combinate Disciplines section.
- It would be great if Paths/Rituals shows only when you add some of them, or an entire Path, or maybe a Blood Sorcery like Thaumaturgy.

### Combat, Rollable pools, Systems
- Active effects, frenzy, buffs/debuff, etc.
- Weapons and armors with stats, rollable.
- Natural weapons and Movements, for Martial Arts, or Kailindo.
- Custom “quick rolls”, for more frequent ones, like the buttons for initiative, soak and so. I don't know if a window to configure your own quick access buttons, similar to the macro bar, would be too complicated.

### Notes, Other info
- Other notes.
- Maybe a Contacts/Known persons.
- Gear, weapons, armor: large text boxes. (Is it necessary to repeat weapons and armor?)
- XP.

_I can create topics for each suggestion separately, if that's better, but I didn't want to spam_

**Comment by JohanFalt** [comment]
I have taken ideas from this list in my overhaul of the graphics.
