### ISSUE TITLE
[Suggestion] An option to force the speciality box

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#372]
In some Abilities it's mandatory to choose a speciality, like in Crafts, or in Academics in Dark Ages. It would be great to have an option to force the activation of the speciality box without having a score of 4.

**Comment by JohanFalt** [comment]
You can alter this manually under Settings -> Abilities (you need to have the sheet set to edit mode).

**Comment by Kad-Caiel** [comment]
Oh, didn't notice. As I see, only in Vampire. In Werewolf, Mage and Changeling don't work. At least, in spanish.

**Comment by JohanFalt** [comment]
You don't get this?

![image](https://user-images.githubusercontent.com/57871596/192853505-b431c720-16f1-483e-8df1-ee2a22f36055.png)

**Comment by Kad-Caiel** [comment]
I forgot to unlock the sheet.
Can you close the thread, and then I'll stop making a fool of myself every time I speak? My god... haha
