### ISSUE TITLE
[Bug?] Knowledges listed as Skills

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#374]
In Creature sheet, if you don't select any Skill, you have a Knowledge in the Skill column.

![imagen](https://user-images.githubusercontent.com/114583468/192795168-febdeb70-a758-4d6d-8dce-a5143e10a649.png)

**Comment by JohanFalt** [comment]
Seems the Mage settings are bleeding into Creature.
