### ISSUE TITLE
Improvements for Vampire Dark Ages

### ISSUE THREAD

**Issue by BinMan86** [JohanFalt/Foundry_WoD20#384]
There are some improvments needed to help compatibility with Dark Ages

- Ranged weapons, Ability drop down doesnt have Archery
- Wepon concealment location are different from modern. instead they are: P = Pouch, C = Loose Clothing, L = Long Cloak. (this is a minor issue as its pretty much the same as modern just with different names)
- Body Craft Skill (needed for Viccissitude/Tzimisce) missing

**Comment by JohanFalt** [comment]
Both issues regarding missing abilities can be solved by adding the missing secondary abilities to the sheet.
You find this under the cog wheel and select Abilities.

**Comment by BinMan86** [comment]
Ok, thanks didnt know you could do that.

**Comment by BinMan86** [comment]
Weapons also need an Armor piercing value for Dark Ages

**Comment by JohanFalt** [comment]
Archery can be created by adding a secondary ability and mark it as a ranged weapon ability.
