### ISSUE TITLE
disciplines window is empty

### ISSUE THREAD

**Issue by NanBurnham** [JohanFalt/Foundry_WoD20#395]
disciplines window seems like it's unavailable to edit. Is that an issue and if it is, how do I fix it?
![unknown](https://user-images.githubusercontent.com/116447866/197346027-6d16ccb6-b753-439f-94c2-6168d0a3143c.png)

**Comment by rhat** [comment]
Can verify on Stable FoundryVTT 10.288 seeing this exact thing with fresh game world and fresh V20 PC.

**Comment by JohanFalt** [comment]
Can you drag a discipline in from items?

**Comment by NanBurnham** [comment]
Yes!
Thank you!

**Comment by rhat** [comment]
Yeah, it looks like I can drag stuff from the Items tab, and making a fake Potence would let me drag it into the main disciplines list for the new test PC. Is there supposed to be actual disciplines already listed?

**Comment by rhat** [comment]
Oh nevermind, I just read the front page: "Dark Pack Agreement

Licensed materials will NOT be provided as this is a system provided for public use for free.

Portions of the materials are the copyrights and trademarks of Paradox Interactive AB, and are used with permission. All rights reserved. For more information please visit [worldofdarkness.com](https://www.worldofdarkness.com/).

This material is NOT an official World of Darkness material."

Okay, I have PDF's to transcribe.

**Comment by JohanFalt** [comment]
It is explained in the Wiki.
