### ISSUE TITLE
Can't install new version, stuck on 1.6

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#400]
When using manifest URL from the main code page as directed:
https://raw.githubusercontent.com/JohanFalt/Foundry_WoD20/main/system.json

Error code "k is not defined" displays and cannot be loaded. I am able to use:
https://raw.githubusercontent.com/JohanFalt/Foundry_WoD20/v1.6/system.json

This gives me 1.6, so no access to changeling sheets or other updates since. When updating this system, "k is not defined" shows up again.

**Comment by JohanFalt** [comment]
You use Foundry V10?

**Comment by SeaSaltSong** [comment]
Sorry for the delayed response, yes that was it. I am updated to v10 now and no issues. File this under "users are dumb and always will be"
