### ISSUE TITLE
Abilities and Attributes in Powers need improved sorting

### ISSUE THREAD

**Issue by BinMan86** [JohanFalt/Foundry_WoD20#414]
The attributes/abilities are currently sorted by cateogry (physical, talent, etc), then alphabetically within their category in powers

When scrolling through the list it can be tricky to find the one you are looking for as they appear as one big list and its not immediately apparent that they are sorted by category then alphabetically

Would be easier list if they were either all sorted alphabetically (and remain one big list) or maybe the drop down list could have headings for their categories to break the list up

**Comment by JohanFalt** [comment]
All attributes and abilities are sorted according to World of Darkness standard and I won’t change this.

**Comment by BinMan86** [comment]
It could be clearer in the list if there were dividers between the categories values in the drop down
