### ISSUE TITLE
Unable to edit new Fetishes on Werewolf Character Sheet

### ISSUE THREAD

**Issue by mundusartis** [JohanFalt/Foundry_WoD20#423]
error message:

d {description: undefined, fileName: undefined, lineNumber: 48, endLineNumber: 48, message: "An error occurred while rendering WoDItemSheet 42. if doesn't match iff - 48:6", …}
column: 6
description: undefined
endColumn: 8
endLineNumber: 48
fileName: undefined
lineNumber: 48
message: "An error occurred while rendering WoDItemSheet 42. if doesn't match iff - 48:6"
name: "Error"
number: undefined
stack: "Error: An error occurred while rendering WoDItemSheet 42. if doesn't match iff - 48:6\n    at d (http://localhost:30000/scripts/handlebars.min.js:28:19901)\n    at Object.l [as prepareBlock] (http://localhost:30000/scripts/handlebars.min.js:28:21115)\n    at Object.performAction (http://localhost:30000/scripts/handlebars.min.js:27:24472)\n    at a.parse (http://localhost:30000/scripts/handlebars.min.js:28:9026)\n    at d (http://localhost:30000/scripts/handlebars.min.js:27:20759)\n    at d.e [as parse] (http://localhost:30000/scripts/handlebars.min.js:27:20799)\n    at d (http://localhost:30000/scripts/handlebars.min.js:28:22596)\n    at e (http://localhost:30000/scripts/handlebars.min.js:28:22741)\n    at renderTemplate (http://localhost:30000/scripts/foundry.js:6906:10)\n    at async WoDItemSheet._renderInner (http://localhost:30000/scripts/foundry.js:5230:16)"
[[Prototype]]: Error at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:5241) at b (http://localhost:30000/scripts/handlebars.min.js:27:330) at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:2069) at b (http://localhost:30000/scripts/handlebars.min.js:27:330) at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:1435) at b (http://localhost:30000/scripts/handlebars.min.js:27:330) at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:792) at b (http://localhost:30000/scripts/handlebars.min.js:27:330) at http://localhost:30000/scripts/handlebars.min.js:27:417 at http://localhost:30000/scripts/handlebars.min.js:27:422
stack: "Error\n    at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:5241)\n    at b (http://localhost:30000/scripts/handlebars.min.js:27:330)\n    at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:2069)\n    at b (http://localhost:30000/scripts/handlebars.min.js:27:330)\n    at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:1435)\n    at b (http://localhost:30000/scripts/handlebars.min.js:27:330)\n    at Object.<anonymous> (http://localhost:30000/scripts/handlebars.min.js:27:792)\n    at b (http://localhost:30000/scripts/handlebars.min.js:27:330)\n    at http://localhost:30000/scripts/handlebars.min.js:27:417\n    at http://localhost:30000/scripts/handlebars.min.js:27:422"
[[Prototype]]: Object
constructor: ƒ Error()
stackTraceLimit: 10
arguments: (...)
caller: (...)
captureStackTrace: ƒ captureStackTrace()
length: 1
name: "Error"
prototype: {name: 'Error', message: '', constructor: ƒ, toString: ƒ}
[[Prototype]]: ƒ ()
[[Scopes]]: Scopes[0]
message: ""
name: "Error"
toString: ƒ toString()
[[Prototype]]: Object

preceding message:

Item {name: 'New fetish', type: 'Fetish', img: 'systems/worldofdarkness/assets/img/items/fetish.svg', system: {…}, #valid: true, …}
flags: {}
img: "systems/worldofdarkness/assets/img/items/fetish.svg"
name: "New fetish"
ownership: {default: 0, zTDyKg8Ej7Le5iR6: 3}
sheetType: "Werewolf"
sort: 0
system: {iscreated: true, version: '2.2.0', parentid: '', worldanvil: '', reference: '', …}
type: "Fetish"
_stats: {systemId: 'worldofdarkness', systemVersion: '2.2.0', coreVersion: '10.290', createdTime: 1669000800826, modifiedTime: 1669000806169, …}
#valid: true
actor: (...)
apps: {42: WoDItemSheet}
collection: (...)
collectionName: (...)
collections: {effects: Map(0)}
compendium: (...)
data: (...)
documentName: (...)
effects: Map(0) {_source: Array(0), invalidDocumentIds: Set(0), #model: Item, #initialized: true, documentClass: ƒ, …}
folder: (...)
hasPlayerOwner: (...)
id: (...)
invalid: (...)
isEmbedded: (...)
isOwned: (...)
isOwner: (...)
limited: (...)
link: (...)
pack: null
parent: Actor {name: 'Prof. Anton "rutgers65" Casale', type: 'Werewolf', img: 'rutgers65.webp', system: {…}, #valid: true, …}
permission: (...)
schema: (...)
sheet: (...)
thumbnail: (...)
transferredEffects: (...)
uuid: (...)
visible: (...)
_id: "j9Y4kKKrw5ul35OT"
_sheet: WoDItemSheet {options: {…}, appId: 42, _element: null, position: {…}, _dragDrop: Array(0), …}
_source: {name: 'New fetish', type: 'Fetish', system: {…}, _id: 'j9Y4kKKrw5ul35OT', img: 'icons/svg/item-bag.svg', …}
get folder: () => this.model?.get(value) ?? null
set folder: ƒ set()
[[Prototype]]: Object

**Comment by JohanFalt** [comment]
Will be fixed in next patch of 2.2. Should be in a day or two.
