### ISSUE TITLE
Feature Request: Alt Werewolf Tribe Names

### ISSUE THREAD

**Issue by mundusartis** [JohanFalt/Foundry_WoD20#426]
Would be really nice if there were a checkbox in settings to use 5th edition tribe names (Galestalkers and Ghost Council in lieu of the tribes they're replacing) https://www.worldofdarkness.com/news/werewolf-the-apocalypse-tribes-and-renown. It would additionally be nice to revert tribe back to being blank once a tribe is selected.

**Comment by JohanFalt** [comment]
You can already do this by writing in the select box the name you wish to use:

![image](https://user-images.githubusercontent.com/57871596/203716066-1244eff1-b614-4e4b-8f15-e5d2f724607e.png)
