### ISSUE TITLE
Cannot change icon of weapons or powers.

### ISSUE THREAD

**Issue by MaiFlow** [JohanFalt/Foundry_WoD20#427]
As the gamemaster I would like to have the ability to change the icons of items and powers as they appear in my Items tab for easier visual identification. When attempting to do this my custom image is in most cases overwritten by the default. For example, when attempting to change the image for a Melee Weapon or Ranged Weapon Item, I can only change it through the accompanying checkboxes in the item.

This issue seems to be present in most of the worldofdarkness Items. There are som exceptions to this issue, among them the Arts entries for Changelings.

**Comment by JohanFalt** [comment]
You can do this already just make sure the image is placed in you World folder. Just click the image on the item.

**Comment by MaiFlow** [comment]
You are right! Sorry for opening an issue on this, it appears it was just my general Foundry newbieness that made me mess up!

**Comment by JohanFalt** [comment]
No worries:)
