### ISSUE TITLE
[Feature Request] Roll Changeling Arts with Realms at 0 dots

### ISSUE THREAD

**Issue by MaiFlow** [JohanFalt/Foundry_WoD20#428]
The rules for Changeling 20th allows characters to use Realms they don't possess enough dots in (or even none at all) by expending Glamour. It would be nice if the character sheet allows rolls to be made for Art powers against Realms you don't have any dots in to represent this.

The Glamour expenditure propably should not be made automatic, as there are multiple interpretations about just how much "cheating" a Realm as the book calls it is actually supposed to cost.

**Comment by JohanFalt** [comment]
No worries :)

**Comment by MaiFlow** [comment]
Was this issue closed accidentially alongside #427?

**Comment by JohanFalt** [comment]
Oh yes it was sorry

**Comment by JohanFalt** [comment]
So just to clarify the rule about this. By spending Glamour you can push what Realms you are able to use. So should I just able people to push the level of Realms they are using and then have that shown in the roll?

Say: Fae (2) +2 

(or something similar)

**Comment by MaiFlow** [comment]
The dots you have in a Realm sets what you can target. However, the rules lets you "push" your Realm ratings up, as you describe, by spending Glamour points. The book is inconsistent on the exact cost, and there are multiple rulings on how much you need to spend. Some people say "1 Glamour per dot you are missing" and some say "1 Glamour per Realm you are missing any amount of dots in." (Hence me suggesting you don't apply the cost automatically.)

The features needed are basically:
1. Let me select Realms I have zero dots in when rolling a cantrip.
2. The number of dice rolled should equal Art + Lowest Primary Realm (Actor, Fae, Nature, Prop)
3. If Scene or Time is added, this should automatically add to the difficulty, but not affect the amount of dice rolled.

Both 2 and 3 are already implemented as far as I can tell, so all that is really needed is an option to select every Realm when rolling for a cantrip, including those with zero dots.

**Comment by JohanFalt** [comment]
Found it, its a change they have made in the newest version of Foundry. Time to fix.

**Comment by JohanFalt** [comment]
Wrote in wrong issue.
