### ISSUE TITLE
Notes section of the vampire sheet is not editable

### ISSUE THREAD

**Issue by Araluen124** [JohanFalt/Foundry_WoD20#429]
I am unable to edit the "Description" and "Details" sections of the sheet (In the History, traits, Merits and flaws)
I can't write anything even as a GM
The description can be edited for weapons but not for disciplines or powers

**Comment by Araluen124** [comment]
The same thing goes for every text box (As in the big boxes, not the ones that are only one line tall)

**Comment by JohanFalt** [comment]
You have unlocked the sheet?

**Comment by Araluen124** [comment]
Yes, i tried while the sheet was in edit mode

**Comment by JohanFalt** [comment]
Will test tonight. So description boxes can’t be edited on the vampire sheet when things comes to Notes and Disciplines?

**Comment by JohanFalt** [comment]
After you have made changes in the box did you click the editor's save button?

![image](https://user-images.githubusercontent.com/57871596/205454757-83b8836f-d0a9-4401-bab4-5bccf970767d.png)

**Comment by Araluen124** [comment]
I am just unable to write in the box, when i click in the text box, i can't get to edit them
![image](https://user-images.githubusercontent.com/104476123/205455945-2ddd7a51-2c93-4cce-b839-0712fc98797e.png)

**Comment by Araluen124** [comment]
And the sheet was in edit mode when i took the screenshot

**Comment by JohanFalt** [comment]
What version of Wod20 are you running 2.2.2?

**Comment by JohanFalt** [comment]
This is the normal appearance of a Discipline sheet.

![image](https://user-images.githubusercontent.com/57871596/205478022-c629a93e-523c-4a63-856e-056c6490f096.png)

I'll look why youredit boxes are set to read only.

**Comment by JohanFalt** [comment]
If you let the pointer hover over the box area do you see this icon?

![image](https://user-images.githubusercontent.com/57871596/205478265-bc44c570-c4c7-442f-b491-bb58d7b670ef.png)

**Comment by Crossfk** [comment]
Hi, I have the same problem. My players and I can't edit the powers and Discipline sheet. Just a blank font without possibility too edit (even the option to edit doesn't exist). I just did the new Foundry maj recently and I have the latest WoD maj too. I can add some pics if you ask.

**Comment by JohanFalt** [comment]
Found issue. It is due to a Foundry update. Has released fix for it just update your system.
