### ISSUE TITLE
Can't update from v2.2

### ISSUE THREAD

**Issue by Lachrimae93** [JohanFalt/Foundry_WoD20#430]
I checked my game and it says v2.3 is out. I also checked the releases here and confirmed. Even foundry tells me it's out. However, when i try to update my version from 2.2, foundry lists v2.2 as the latest version despite 2.3 already being out. This might be a simple fix but I don't know what's going on

**Comment by JohanFalt** [comment]
That is due to you need to have the latest Foundry installed. Version 10.291 I think it is.

**Comment by JohanFalt** [comment]
Yes it was:
![image](https://user-images.githubusercontent.com/57871596/207032167-903549dd-af1c-4c2c-a8d6-d5c504ad0fdb.png)
