### ISSUE TITLE
[Feature Request] Merits and Flaws Integration

### ISSUE THREAD

**Issue by Grandsome** [JohanFalt/Foundry_WoD20#434]
Integration similar to [WoD Character Creator](https://www.drivethrurpg.com/product/296783/WoD-Character-creator)'s, where source book listed merits and flaws are found in drop down menus and added to character bios and are counted towards exp points. Also talking of WoD Character creator, an import option for .mdtm files could be nice too.

**Comment by JohanFalt** [comment]
When it comes to Merit and Flaws I can't add more support than I have as I am not allowed to have book content in such degree in the system of itself from Paradox.

What are .mdtm-files. Not familiar to those.

**Comment by Grandsome** [comment]
Oh I see, as for .mdtm files they're the file format the WoD Character Creator uses to store the characters. The Character Creator is a really great  tool as it also enforces the points attribution rules, I wonder if you could get in contact with the creator for some collab.

**Comment by JohanFalt** [comment]
No this is a project I won’t have time to be part of.
