### ISSUE TITLE
Changeling: The Dreaming - Difficulty modifier for using Time and Scene should stack.

### ISSUE THREAD

**Issue by MaiFlow** [JohanFalt/Foundry_WoD20#436]
When evaluating the difficulty of a changeling cantrip, both the Time and Scene realms should add +1 to the difficulty. Luckily the difficulty can be manually adjusted anyway, so I belive this is a low priority, quality of life issue.

Currently the method _lowestRank in [dialogue-module\dialogs\dialog-power.js] seems to handle the difficulty calculation. However, it only checks if _at least one_ of those Realms have been selected, instead of checking them individually.

**Comment by JohanFalt** [comment]
So just making sure I get this correct.

If you have a Cantrip and you use the following:

Actor 2
Fae 3 
Nature 0

That means you will get your Art number of dices only? (ignoring difficulty at the moment)

**Comment by JohanFalt** [comment]
So you get +1 difficulty _per_ Realm? So if you get both you get a +2 in diff?

**Comment by MaiFlow** [comment]
Seems you finished it, but yes. Using either Time or Scene adds +1 difficulty. They are basically "metamagic" in DnD terms. They don't change the dice pool at all, just modify the effect and increase the difficulty. The dice pool is always (Art rating + Lowest primary realm used). 

You can use any amount of the four primary Realms (Actor, Fae, Nature, Prop) without affacting the difficulty. The exception being your affinity Realm, which reduces the difficulty by one.
