### ISSUE TITLE
Actor Ownership: Limited and Owner display same information

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#438]
When testing actors for my VtM game, when setting ownership to Limited or Observer they both show the same amount of information. If possible just the "Bio" tab would be optimal for limited. This is mostly for the purposes of NPCs being able to be built for gameplay when they are in a scene, without players being able to see everything they have access too.

I also like to set other players as limited to each other so they can see the rest of the coterie exists, without the specifics of what everyone has access to.

**Comment by JohanFalt** [comment]
That is a system setting. You find it under:

![image](https://user-images.githubusercontent.com/57871596/208610796-607f2f66-fcc6-4746-bb0d-411f14fc1f18.png)

https://github.com/JohanFalt/Foundry_WoD20/wiki/System-Settings#permission-settings

**Comment by SeaSaltSong** [comment]
Beautiful, thank you. Is there a way to separate Limited and Observer so that some sheets can be displayed as the whole thing, but limited be just the Bio tab?

**Comment by JohanFalt** [comment]
Not today. How would you like it to work?

**Comment by SeaSaltSong** [comment]
Preferably the same as this current system settings treats observer.

So I could set Observer to "Observers can see full sheet"
Then set Limited to "can see core tab only"

This will allow me to set up, say the Prince, as limited where they get a portrait and overview.
And other NPCs, such as ghouls or animals they are controlled with something like subsume the spirit, have the whole sheet visible without being edited.

Am I being clear? And thanks a ton for this system, it's honestly the best for the needs of my group.

**Comment by JohanFalt** [comment]
An observer is a player that doesn't own the character it looks at.

But what setting ssets the player to be limited? I just switched from one to the other on a few actors and as I tried to look at an actor with limited access I got that I couldn't update the sheet and couldn't watch it.

**Comment by JohanFalt** [comment]
Found it!
