### ISSUE TITLE
Paths reset and wipe virtues

### ISSUE THREAD

**Issue by Araluen124** [JohanFalt/Foundry_WoD20#439]
When i close and launch Foundry. If a vampire was on something else than Humanity, their path, it's level and their virtues get wiped and i don't know what causes that

**Comment by JohanFalt** [comment]
Made some simple tests about this but can't reproduce the problem.

I altered Road to inne voice and started with changing back and forth. Restarted Foundry and so on, and no problem. So lets begin with the basics.

Are you using the latest version of WoD20 - v2.2.5?

![image](https://user-images.githubusercontent.com/57871596/209086236-15c3fffd-0ca7-49f5-859f-d8902980103a.png)

**Comment by Araluen124** [comment]
I just realized something, it did not happen when i relauched foundry, your answer made me realize that it actually happened when i updated to 2.2.5 and 2.2.4, not on random lauches

**Comment by JohanFalt** [comment]
Did this happen to all your vampire characters? And it hasn't fixed again by say you start your foundry again?

**Comment by Araluen124** [comment]
It only happened to those witch had something other than humanity and starting again did not fix it (But it was only the update, i was mistaken at first)

**Comment by JohanFalt** [comment]
Ok do as follows. 

Open Foundry. 
Press F12
Open a vampire sheet that should have Path-values.

You should see something like:

![image](https://user-images.githubusercontent.com/57871596/209202957-0781e2ec-23ae-411a-8498-693f8f1bacd4.png)

Press the arrow before Vampire Actor like this:

Try open like follows:

![image](https://user-images.githubusercontent.com/57871596/209203080-a16201e4-c54c-4dc6-884b-8002f8f56f8c.png)

Does it look more or less the same as what I copied in?

**Comment by Araluen124** [comment]
![Capture d’écran 2022-12-22 134306](https://user-images.githubusercontent.com/104476123/209204642-80f078c4-8297-4428-a656-51512ba37867.png)
This is the thing i get for a character witch has something else than humanity (My player put lilith but he has the road of sin from dark ages)

**Comment by Araluen124** [comment]
![Capture d’écran 2022-12-22 134532](https://user-images.githubusercontent.com/104476123/209205056-7fb79ca0-2532-43a2-97e9-2d71e4809189.png)
And i get that for a character on witch i never changed from humanity

**Comment by Araluen124** [comment]
The thing i notice is that the lower path thing has no value

**Comment by Araluen124** [comment]
I think i get it... all my characters are basically a duplicate of a base i made (To save time because i play with Dark ages so some skills are different. Therefore i made a single base with the good skills that i duplicate for every character) but that base was made on an older version of the system... (2.2 or 2.1 i think)

**Comment by JohanFalt** [comment]
Have you corrected the sheets since? Because they show correctly at the moment.

**Comment by Araluen124** [comment]
I corrected them since yes (and i was talking about the lower "Path" line witch says that every value is 0)

**Comment by JohanFalt** [comment]
Yeah that is the old one from v2.1, in v2.2 it was moved to the one under adventages.

I think this is connected to https://github.com/JohanFalt/Foundry_WoD20/issues/433 and that part is fixed now so - sorry. There shouldn't be any problems in the future though.

**Comment by Araluen124** [comment]
Thanks for your help and Merry Christmas (In the event that you celebrate it, otherwise, happy holiday season)
