### ISSUE TITLE
Specialty QOL Improvement

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#465]
I'd like to request two minor quality of life improvements.

The first, specialties. It's a little clunky to go to another page, so could we have the boxes that let us type in our specialties move to the main, core page next to the relevant ability/attribute? Below is a quick and dirty visual of it.

![Specialty](https://user-images.githubusercontent.com/117007321/212254036-5b972e23-7617-4075-a30c-5d784052c043.PNG)

Second part placed in:
https://github.com/JohanFalt/Foundry_WoD20/issues/467
The second is combination disciplines. They're kind of.... weird to create items for. I ended up making a discipline item called "Combination Disciplines" so the ones my players get can be seperate from the others, but another header like "Discplines, Paths, Rituals" would be ideal. Overall, that's not the wird thing that I ran into.

The pre-reqs are what's really weird. The book presents them as part of the title like: "Under the Skin (Auspex ●●●, Presence ●●●)" but that gets really wordy. I'd like to see some kind of item in the header that lets us type in the pre-reqs.

Ultimately this isn't too big of a deal and we can always just put the pre-reqs in the description if need be.

**Comment by JohanFalt** [comment]
As a design solution I really like your solution for specialties. Especially since that space isn't really used. Could just be a button you press. If you then hover over the specialty button then what you have written can be read right away.
(it would also make the code easier).

Second part. Can you add that text to the issue about Combination disciplines as a seperate issue?

**Comment by SeaSaltSong** [comment]
Exactly. And I personally really like that the box to type specialties doesn't even show unless you have 4 dots in the respective attribute/ability. Having that box show when the sheet is unlocked, and the text visible when locked will make it just nicer to see everything at one glance.

And yes, can do.

**Comment by JohanFalt** [comment]
Mage spec  remaining.
