### ISSUE TITLE
Game Compendium

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#466]
(Last thing I wanted to add, made them separate issues for convienicne)

It's my understanding that a compendium cannot be added to the game because of legal issues with Paradox. I totally understand, however I do have a work-around and I am willing to help with it.

If the items are only the names and other tedious info, and the descriptions are "please see pg x of y" you can get around this legal issue without piracy or take-down requests. The Star Wars FFG does this, and it's up to the people using the system to put in the information.

An example is this:
![Discipline](https://user-images.githubusercontent.com/117007321/212255862-f6d9063d-ad64-41fc-a590-ba14d2a55a29.PNG)

Users will have to manually put in the meat of the power, but the tediousness of creating the item and everything else is already halfway done.

I'm willing to do this to help support this system. I don't have the technical know-how to set it up, but I could do the time-consuming data entry for it.

The only thing I could see needing to be done, is perhaps a field of each discipline power (and perhaps the other systems version of) that lets us put the discipline, arte, etc. name so that it is auto-organized into the character sheet. That's a bit of a stretch goal though, and really just more QOL than anything.

**Comment by JohanFalt** [comment]
Good idea. Question would be how to get into the system. You thinking it would be to import externally or it being a part of the system as you install in?

**Comment by SeaSaltSong** [comment]
Considering I'm making a full fleshed out with copy/paste for my games anyway, it could be external and swap to this if I ever receive a cease and desist.

However, I do not know what would be easier to implement, something external or being baked into the system directly.

**Comment by JohanFalt** [comment]
External would be simpler yes.

Could be that if we are talking about this as a project you have one compendium per WoD game.
I'm already patching possible compendiums within the game world to fit the present version of the system so I think it would work.

**Comment by JohanFalt** [comment]
This issue should be implemented for this though:

https://github.com/JohanFalt/Foundry_WoD20/issues/320

**Comment by SeaSaltSong** [comment]
I'm currently looking into modules that allow folders in compendiums, which makes things much more manageable if those folders stay when exporting.

This will allow me to make a V20.Disciplines compendium that has a folder for Animalism, Auspex, etc. without having to make them each a unique compendium.

This would also help with a workaround I used. Since compendiums alphabetize things , all one dot discipline powers get bunched up on top of each other if they aren't kept separate, so I named the powers things like "Animalism ● Feral Whispers" so that the disciplines are kept together. This means the user importing needs to manually delete "animalism" from the name for ever power and that's... that's tedious for no reason.

And being mixed with that is awesome.

**Comment by JohanFalt** [comment]
I think it is a group effort though so if you find more people that wish to help in cooperating the compendium in this fashion (just reference to the descriptions) then I think that would be a good idea.

**Comment by SeaSaltSong** [comment]
I almost have everything from V20 typed up and organized in my game. If someone could help me learn to export it I could make it available relatively soon.

**Comment by JohanFalt** [comment]
Just let me know when you are done I can help you.

**Comment by Grandsome** [comment]
> I almost have everything from V20 typed up and organized in my game. If someone could help me learn to export it I could make it available relatively soon.

There's a [module](https://github.com/kid2407/Compendium2Module) that can turn compendiums into modules, haven't tested it yet. If you publish it let us know gonna be a hell of a time saver.

**Comment by JohanFalt** [comment]
> I almost have everything from V20 typed up and organized in my game. If someone could help me learn to export it I could make it available relatively soon.

I think this is the normal way. Not sure if the (TA) Export to JSON is standard Foundry (checking)...
I use Compendium Folders.

![image](https://user-images.githubusercontent.com/57871596/213369874-6097d4a5-b040-40d8-a582-5b769cf9ab55.png)

**Comment by SeaSaltSong** [comment]
I'll try it out after tomorrow nights game. I have at least the core done except bloodlines and elder powers

**Comment by SeaSaltSong** [comment]
GRANDSOME! YOU ARE AMAZING. It worked. Amazingly I should add. Even worked with the compendium folders, so this:

![image](https://user-images.githubusercontent.com/117007321/213687875-637fa59f-2775-435e-8923-0d48cec34027.png)
 Doesn't need to have the discipline name in front of it to prevent from getting lost in the rabble.
 
I'll post a manifest link hopefully within the next week for the base of it. Long story short, it's on a friend's server and I need his help to get the files to put on github. I'll also try and get elder powers on there after that since I saw someone asking for them before.

**Comment by SeaSaltSong** [comment]
Game compendium completed. I figured out my simple issue and resolved it.
Repository: https://github.com/SeaSaltSong/wod20-compendium
manifest URL: https://raw.githubusercontent.com/SeaSaltSong/wod20-compendium/main/module.json

**Comment by JohanFalt** [comment]
Nice :)

**Comment by SeaSaltSong** [comment]
I opened a new world and didn't get that. Are you using a new version not released yet?

**Comment by JohanFalt** [comment]
Could be. I need to experiment with it a bit. Reason is that in v2.3 there are a patch for power items. And I notice that IF you are using v2.3 already and install the compendium it doesn't get patched - I need to fix that somehow.

**Comment by Grandsome** [comment]
> GRANDSOME! YOU ARE AMAZING. It worked. Amazingly I should add. Even worked with the compendium folders, so this:

You're welcome, glad that my module addiction is useful to somebody ;-)
Also, if this is gonna be a stand-alone module, don't forget to put compendium folders as dependency, I think you can ask JohanFalt how to flag that.

I'm gonna have a look at your awesome work, now. :-)

**Comment by SeaSaltSong** [comment]
> > GRANDSOME! YOU ARE AMAZING. It worked. Amazingly I should add. Even worked with the compendium folders, so this:
> 
> You're welcome, glad that my module addiction is useful to somebody ;-) Also, if this is gonna be a stand-alone module, don't forget to put compendium folders as dependency, I think you can ask JohanFalt how to flag that.
> 
> I'm gonna have a look at your awesome work, now. :-)

Already done as a dependency. A good friend of mine (And player in my game) does coding professionally and helped me iron out the wrinkles and do things like the dependencies.

**Comment by JohanFalt** [comment]
This was fixed right?

**Comment by SeaSaltSong** [comment]
> This was fixed right?

Yes, it was.
