### ISSUE TITLE
Combination Discipline QOL Improvement

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#467]
At the moment, Combination Disciplines are kind of.... weird to create items for. I ended up making a discipline item called "Combination Disciplines" so the ones my players get can be separate from the main discplines they already have, but another header like "Discplines, Paths, Rituals" would be ideal. 

The pre-reqs are what's really weird. The book presents them as part of the title like: "Under the Skin (Auspex ●●●, Presence ●●●)" but that gets really wordy. As an item in teh sheet it gets really cluttered. I'd like to see some kind of item in the header that lets us type in the pre-reqs.

Ultimately this isn't too big of a deal and we can always just put the pre-reqs in the description if need be.

**Comment by JohanFalt** [comment]
A combination Discipline is a Discipline which have a number of Discipline Powers connected to it. Which you need to have already.

These type of Powers exists in Vampire and Demon only I think, can't recall that they exist anywhere else.

So I picture a new type of Power which in Vampire's case would be Discipline Combination Power (a bit of a mouthfull). As you pull that to the sheet you then can connect it to existing Discipline Powers that the sheet has. Just as you can when you sort unsorted Discipline Powers. 

These then get listed with the Combination Discipline as well.

This would give the sheet four lists:

Disciplines
Combination Disciplines
Paths
Rituals

**Comment by JohanFalt** [comment]
Will try to get it into 2.3. But we see.

**Comment by SeaSaltSong** [comment]
Yes, four lists. I believe the Roll20 sheet has a pretty intuitive implication of this, for reference
![Roll20 Combo Discipline](https://user-images.githubusercontent.com/117007321/212272338-68d0bbe0-10c1-4c8d-8cae-781125a168c3.PNG)

A screenshot from one of my player's sheet from before moving to Foundry.

It doesn't need to be 2.3. Right now they have the disciplines "Animalism, Potence, Obfuscate, Combination Disciplines, etc. etc."

**Comment by JohanFalt** [comment]
So in essence, if you want this to be easy. You treat these as normal Discipline Powers and just list them as their own. You fill in what Powers is required for them and if you need to roll them or not as normal?

**Comment by JohanFalt** [comment]
This was way more complicated than I first thought so I will push this to v3.2.

**Comment by JohanFalt** [comment]
https://github.com/JohanFalt/Foundry_WoD20/issues/799
