### ISSUE TITLE
Abilities Dot doesnt draw correctly on Vampire Character

### ISSUE THREAD

**Issue by Cougy-6185** [JohanFalt/Foundry_WoD20#472]
Hello,
If you create a Vampire with generation 7 or less and create an new Ability (Talent, Skill or Knowledge), the Dot corresponding doesn't fit the character sheet correctly. You only have 5 Dots (not 6+ as usual) and they are drawned strangely.
Sorry for my english, it is not my native language.

**Comment by JohanFalt** [comment]
I'll fix this in the coming version.

In the meantime there are a quick fix for it. Add the abilities you wish to use then go to generation add a temporary generation and then clear it again. That will make the system to recalculate the max values.

https://github.com/JohanFalt/Foundry_WoD20/wiki/Sheet:-Vampire-the-Masquerade#generation
