### ISSUE TITLE
[QOF] Auto-Assigning Powers

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#480]
Quality of life to add to longer-term milestones. I'm going to use a VtM example, but it could apply to others like Changeling.

Could we get a field in the Discipline powers Heading called "Discipline" that checks the sheet if a discipline exists by that name and auto-assigns it to that?

For example, I put Auspex on a character sheet. Then I add the "Heighten Senses" item to the sheet with the field for discipline filled out, and it auto-checks if that discipline exists on the sheet already and assigns it there, or leaves it unassigned if not.

Expected issue, a typo on user side could cause it to fail. For example, my Auspex exists on the sheet, but I typed "Ausoex" on Heightened Senses by missing the p and hitting o instead. This would cause it to be unassigned since "Ausoex" doesn't match the pre-existing "Auspex."

Suggesting this, since with the compendium near initial release it'd be a nice quality of life for GMs building NPCs, etc.

EDIT: Also would need to apply for Necro and Thaum paths. These are what the average user might get the most out of.

**Comment by JohanFalt** [comment]
The main reason for this function is that to be able to update powers that has been added but has now been updated. OR is it so you can't add the same power twice?

**Comment by SeaSaltSong** [comment]
The main point is when adding new powers to a sheet for the first time, they would automatically assign themselves to the appropriate power set.

Most players buy a power one at a time and it's not a problem, but if a character does and they bring in a new one with a large handful of xp, or a gm fleshing out an NPC, and manually assigning each power to the appropriate heading is tedious.

**Comment by JohanFalt** [comment]
Hmm what I could do is….

All Power Items has an attribute called parentid. If you would add the Discipline’s name there on the Discipline Powers I could check that if I find a discipline’s name you have I automatically connect them. Not sure if it was clear enough.

**Comment by JohanFalt** [comment]
Like this (example):

{
  "name": "• Awe",
  "type": "Power",
  "img": "systems/worldofdarkness/assets/img/items/power_vampire.svg",
  "effects": [],
  "flags": {
    "exportSource": {
      "world": "xxxxxxxxxxx",
      "system": "worldofdarkness",
      "coreVersion": "10.291",
      "systemVersion": "2.3.0"
    }
  },
  "system": {
    "iscreated": true,
    "version": "2.3.0",
    **"parentid": "auspex",**
    "worldanvil": "",
    "reference": "",
    "description": "",
    "details": "",
    "type": "wod.types.disciplinepower",
    "level": "1",
    "value": 0,
    "max": 5,
    "dice1": "charisma",
    "dice2": "performance",
    "bonus": 0,
    "difficulty": "7",
    "isrollable": true,
    "isactive": false,
    "spendwillpower": false,
    "spendrage": false,
    "spendgnosis": false,
    "spendblood": false,
    "spendglamour": false,
    "game": "vampire"
  },
  "_stats": {
    "systemId": "worldofdarkness",
    "systemVersion": "2.3.0",
    "coreVersion": "10.291",
    "createdTime": null,
    "modifiedTime": 1674036356280,
    "lastModifiedBy": "CJSsCwdnDobaXtrZ"
  }
}

**Comment by SeaSaltSong** [comment]
Yes, clear. How do I edit that so something in a compendium would have that set?

**Comment by JohanFalt** [comment]
I came up with a solution that works:

https://github.com/JohanFalt/Foundry_WoD20/issues/483

Will have a new version out of the system tomorrow (Sunday) and then I can explain how it works.

**Comment by SeaSaltSong** [comment]
Beautiful. From what I just read that would work very well.

**Comment by JohanFalt** [comment]
I got it to work BUT it is way bigger than what I can put into a part release and thus it will be in the v2.3. It looks like this:

![image](https://user-images.githubusercontent.com/57871596/213911045-1c9be8e7-c182-466e-a8d9-5269657cb2d2.png)

If you have e.g a discipline power that is not connected to a sheet but just within the world you get a list of all disciplines that has been created in the world. Then you set this and as you drag it to the sheet the sheet tries to find if the set discipline's name exist on the sheet already. If it does then it connects automatically.

The game setting you see on top is to start to minimize the list of power types. It is starting to get long.

**Comment by R00k0fShad0ws** [comment]
I am not seeing these options. Was this feature removed?

**Comment by JohanFalt** [comment]
No, but in some cases if you just added the disciplines to the world try restart it.

Also it doesn't check compendiums.
