### ISSUE TITLE
Discipline Dots to Attributes

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#484]
I was trying to think of how to implement powers that directly increase attributes, such as VtM's Potence, Fortitude, and Celerity. I think I figured out the easiest way to do it.

If on the power item itself there was a drop down menu to select an attribute that will auto-add the power dots to rolls of that attribute.

So hypothetically I would have Celerity.
That drop down was by, default, "none" so I click it and select dexterity.
I add to the sheet, and let's say set it at 2 dots of Celerity.

I go to roll a weapon attack with my pistol.
before the roll it would have that display that shows:
Dexterity (3) + Firearms (2) + Celerity (2)

This would also add to soak for players with fortitude (currently I gave them an armor called "fortitude" that needs to be manually updated when they gain fortitude dots.

**Comment by JohanFalt** [comment]
I’m working on something like this I the coming version. What it does is that you can add bonuses to powers, merits and so on and by so doing - when the e.g power is active the bonus is automatically added.

The only not solved so far is powers like potence.
