### ISSUE TITLE
[Feature Request] Manoeuvre Subsection in the Combat Tab

### ISSUE THREAD

**Issue by Grandsome** [JohanFalt/Foundry_WoD20#493]
**Description**
Add Manoeuvre Subsection in the Combat Tab, and a corresponding Manoeuvre flag for items and "weapons" representing them.

**Context:**
I made a bunch of manoeuvres as items to give easy roll access to my players for stuff like Parry, Dodge, Block but also attacks like Low Blow, the problem is that it easily clutter the natural weapon section of sheet and makes it hard to read. I used ASCII order to my advantage, but it's not ideal. 

Giving items a Manoeuvre flag and their own subsection would alleviate that.

**Details**
Basic Manoeuvres like Block, Parry, and Doge could also be implemented as big buttons next to Soak.
An advanced feature would add an item check for manoeuvres that need an item in Melee or Ranged section, like Parry and Pistol Whip.

Thanks.

**Comment by JohanFalt** [comment]
I would solve this like the below. My question is what doesn't this fix that you suggest?

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/868c6d6a-d497-4545-b32b-6b70059b81d1)

**Comment by Grandsome** [comment]
I'd still separate natural weapons and manoeuvres given that there are a ton of manoeuvres, they tend to clutter the natural weapon section for martial art focused characters.
