### ISSUE TITLE
[MtA] Add Wonders

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#498]
In Mage there are magic items with different capabilities. They can be found in the Toybox section at page 651.
- Devices and Talismans have their own Arete/Enlightenment trait to roll, which is fixed.
- Fetishes work the same as in Werewolf, and are present
- Periapts and Matrices store up Quintessence
- Trinkets give fixed bonuses you don't need to roll for.

It would be nice to have at least items where I can write down their abilities, even if they don't roll, but all Wonders are able to give Permanent Paradox when they're equipped, which I'd like to note at least, and I'd like to be able to add active effects to equipped trinkets somehow. Even if they do have a linked Background, I think they would be most useful in the Combat tab.

**Comment by JohanFalt** [comment]
Same as Teasure
