### ISSUE TITLE
[MtA] Add Sciences as opposed to Spheres

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#499]
Technocratic characters -but also some Tradition mages!- don't have the usual 9 Spheres, but they have their own, which are listed at p. 65.
- Correspondence Principles OR Data 
- Entropic State Control 
- Dimensional Science Paraphysics
- Force-Based Paraphysics
- Life Sciences
- Material Sciences
- Primal Utility Theory
- Psychodynamics
- Temporal Science

They also may have Enlightenment instead of Arete.

These would JUST be aesthetic changes, but I think they would be useful to have in a sheet, to differentiate different kinds of mages, willworkers, enlightened scientists or what you will. Perhaps it could be a setting in the 'Powers' section of the sheet settings?

**Comment by JohanFalt** [comment]
So essentially a possibility to change the shown name.
