### ISSUE TITLE
Specialities on lower levels

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#501]
With some abilities it's possible to take a Speciality with less than four dots, and Crafts is required to have a speciality. Still the character sheet doesn't allow this.

**Comment by JohanFalt** [comment]
You do that by altering the ability’s name.

you do this under Settings -> Abilites.

**Comment by TheFokin** [comment]
I guess it's a way out. Thanks, didn't think of that.
Still would be nice to have an option to input a proper Speciality.
