### ISSUE TITLE
Render @Journal and @Actor links as buttons on the sheet

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#504]
Even on WoD 2.3 when I drag a Journal or an Actor in the new editable text boxes what appears is @UUID[JournalEntry.blablabla]{name}; unlike what happens when said link is put in chat, when on the sheet this does not work at all. I was wodnering if you could make it a clickable button. Some pictures for examples:
How it is now (unclickable, not very useful):
![immagine](https://user-images.githubusercontent.com/56313572/217011176-353df02b-6807-48f1-9f12-a46afd51bbb9.png)
How I would like it to appear (clickable, very useful):
![immagine](https://user-images.githubusercontent.com/56313572/217011447-4d128529-2ffd-4796-8688-fff99edefa99.png)

**Comment by JohanFalt** [comment]
It should, that is one of the boxes in Magic?

**Comment by EldritchTranslator** [comment]
Okay, since it seems to be a bug, I can tell you this happens in:

All Sheets
- Equip

Changeling Sheet
- Unseelie & Seelie Legacy (Bio)
- Thresholds (Core)

Mage Sheet
- All Focuses (Magic)

**Comment by JohanFalt** [comment]
It works with Description of actors :)

**Comment by EldritchTranslator** [comment]
Yes, the ones I listed are the ones where the Journal links don't show up, in Description they do work, Appearance too. Actor links don't work at all, but maybe that's intentional? Less important than Journals anyway.

**Comment by JohanFalt** [comment]
This should now work in v2.3.1
