### ISSUE TITLE
[Bug] V2.3 Cannot Open Actor Sheet On Player Side

### ISSUE THREAD

**Issue by Grandsome** [JohanFalt/Foundry_WoD20#506]
I get the following error trying to open the sheet on my player testing side the first is using an old actor, the following trying to open a new actor:

![image](https://user-images.githubusercontent.com/32459440/217146862-24486fae-d6ac-4e9c-a69b-2c7c21a541b8.png)

Thanks

**Comment by JohanFalt** [comment]
Just checking:

you create a new Mage sheet.
A player opens it

**Comment by JohanFalt** [comment]
No can't reproduce there has to be something you do that is "special". 

What permissions have you set for the Player to have?
Are they owner of the sheet?
Is it mage only?

**Comment by Grandsome** [comment]
I've isolated the problem, it's probably a bad interaction with a browser extension. I've tested with 3 browser and incognito mode and the sheet worked.
