### ISSUE TITLE
Specialties Currently Hidden

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#510]
With the new update, specialties show as a green exclamation point on the sheet, and display when hovered over, however this is still out of sight and effectively hidden. I do, however, LOVE the yellow exclamation point if the field is empty.

Could we get the text in the field to display next to the skill on the main page when the sheet is locked so that the icon does not need to be hovered over to see the specialty? So it's visible at first glance?

**Comment by JohanFalt** [comment]
I tried to have them visible at all time but it was not really possible, they can't fit. So the end result was what came out. I can't really see any other way to manage to do it without needing to widen the whole sheet which I don't want to do.

The main problem is that you need the width there are as you can alter the text of the abilities.

So in short. No this will be the end result of this issue.

**Comment by SeaSaltSong** [comment]
Very fair, if it doesn't fit, it doesn't fit. Thanks again, it's still a HUGE improvement.
