### ISSUE TITLE
Lore Demon: The Fallen

### ISSUE THREAD

**Issue by andersonalmeidda** [JohanFalt/Foundry_WoD20#513]
Hello, I can't add the Lores from Demon:The Fallen ... I don't know if I'm doing it wrong. I use the latest version of Foundry. Thanks!!!

![image](https://user-images.githubusercontent.com/125048196/218127555-54ae111c-55ee-40cd-9f45-163e0a80ef14.png)

**Comment by JohanFalt** [comment]
You need to create the powers in the world before you can add these to a sheet. For demon you use Lores and Lore Powers which are Power Items. I can add these under the item tab in Foundry. See wiki below. If more questions don't hesitate to ask.

https://github.com/JohanFalt/Foundry_WoD20/wiki/Feature:-Powers

**Comment by andersonalmeidda** [comment]
Thank you very much!! Thanks for the quick response, sorry I hadn't seen it!!!!
