### ISSUE TITLE
[Feature Request] Add Combat and Notes tab to Creature sheet

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#518]
Maybe by design, the Creature sheet is very simple. However, I think that at least the Combat tab would be useful, since even 'normal' creatures could have natural weapons and armor. Likewise, the Notes tab would be useful to create Mage Familiars and similar creatures, which can have Merits and Flaws, and may need to track experience added and spent. All in all, if it's not complex to add these, it would add a LOT of flexibility to this sheet.

**Comment by JohanFalt** [comment]
You are correct as I first designed the creature sheet it was thought to be simple, but as the functionality of it has grown it needs an overhaul which is planned for next version. I place this there.
