### ISSUE TITLE
[Feature Request] For Vampires, add an entry on Ritual items for "Blood Sorcery"

### ISSUE THREAD

**Issue by RinVindor** [JohanFalt/Foundry_WoD20#522]
As the suggestion says an entry for Rituals for Vampires would be great as its not entirely uncommon for a character to have Blood Sorcery from several areas. It'd be great to either have an entry for Ritual items, or an even better, a way to add additional Ritual headers on the character page and be able to name them, ie, "Thaumaturgy Rituals" and "Koldunic Rituals"

![image](https://user-images.githubusercontent.com/12647469/219290983-a1c70e67-dd97-4ab0-933c-1ec6cc9e0ac3.png)

**Comment by JohanFalt** [comment]
What if just to add what type of ritual it is on the ritual itself. Then show this in the list of rituals?

Once you have typed what ritual it is then it would be easy to bundle the different rituals together in the list making it possible to separate them if you have different kinds.

**Comment by JohanFalt** [comment]
I'll do something easy by now, you can set a category (what type of ritual it is) and then that is visible in the list.

I'll see what can come up later as it requires quite alot of work to actually divide the rituals into many lists.
