### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sfckor** [JohanFalt/Foundry_WoD20#528]
Ability to have Quick Draw skill be added to initiative roll.

**Comment by JohanFalt** [comment]
Hmmm this is a secondary ability right?

At the moment there are no way to actually give abilities bonuses, so I recommend you create a Other Trait - see Notes tab then give that initiative bonus. Either that or go into the sheet settings (the cogwheel) and add bonus to initiative under combat.

**Comment by JohanFalt** [comment]
Workaround exists.
