### ISSUE TITLE
Changeling character sheet has no space for the arts

### ISSUE THREAD

**Issue by khovisfersa** [JohanFalt/Foundry_WoD20#529]
![image](https://user-images.githubusercontent.com/25487722/219507327-962ccc03-516d-456b-8310-fda1084c71ea.png)

As shown above, changeling character sheet has no space for the arts

**Comment by JohanFalt** [comment]
Help for this is coming. But until then what you do is create the powers in Foundry then drag it to the sheet. See wiki below. If more questions just ask away here.

https://github.com/JohanFalt/Foundry_WoD20/wiki/Feature:-Powers

**Comment by JohanFalt** [comment]
With the latest version this has now been fixed. You need to unlock the sheet to see it.
