### ISSUE TITLE
[Request] Level "dots" and more space for the name of the Powers

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#531]
Maybe we can add a "dot counter" at the very left of every Power, that show automatically their level. Like in the header withe the Discipline name, but smaller.

Or add more space for names. For example, in spanish, Obfuscate five Power is "**Encubrimiento de la Concurrencia**", but with the dots, it doesn't fit.

![imagen](https://user-images.githubusercontent.com/114583468/219843165-a1718d0c-b2c7-4ebb-aa5d-218d8ed52f19.png)

**Comment by JohanFalt** [comment]
Not a simple problem will push this for v2.5.

**Comment by JohanFalt** [comment]
After consideration I will leave this as is.
