### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by yagit5593** [JohanFalt/Foundry_WoD20#534]
Could you consider adding the option to create custom Virtues, Paths, Renown, and other characteristics? As a player who uses second edition Sabbat Morale and enjoys playing Black Spiral Dancers, I have noticed that these groups do not follow the standard systems. Being able to customize these traits would greatly enhance the gaming experience for myself and others who enjoy playing these unique characters.

**Comment by JohanFalt** [comment]
There are future plans for things like this and I will place this request among those.
