### ISSUE TITLE
Bug with the Willpower test

### ISSUE THREAD

**Issue by Crossfk** [JohanFalt/Foundry_WoD20#535]
Hi,
Recently, I discover a problem with the Willpower test. In the beginning, I was thinking it was a problem with a module, so I erase all of them. But, the problem stayed.

When I click on the button to throw the dices, the counter is not read. The number of dice will always be zero (in every character sheet, all of them have the bug). Here a screen of the problem with a fresh character sheet I created

![6c3f93e6157b6871a6ce75fff3ab8e4f](https://user-images.githubusercontent.com/119798099/220442747-4a222780-f597-4df8-b0a6-26427b3a8bf3.png)

**Comment by JohanFalt** [comment]
I found this as well during my game tonight. Update will come tomorrow.
