### ISSUE TITLE
backgrounds in mage character sheet not saving

### ISSUE THREAD

**Issue by khovisfersa** [JohanFalt/Foundry_WoD20#536]
In the "Bio" tab, whenever I fill the Background field and lock the sheet back, it disappears

**Comment by JohanFalt** [comment]
![image](https://user-images.githubusercontent.com/57871596/220549903-8199b6e1-4201-4234-a5b5-313829180fff.png)

You see the arrow pointing down. Did you click that? For some reason Foundry require you to made a "save" for the containts of the editor to actually store its values.
