### ISSUE TITLE
[Request] More control to hide info in Bio tab

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#542]
I usually tend to hide the entire sheet of a NPC, and only reveal parts as they are discovered by the players. It would be great if we can choose "permissions levels" to certain lines... for example, an option to hide Clan or Auspice (not evident; other things, like Kiths in Changeling are more obvious.), Nature (is the inner and true personality, you need to know very well that person), Generation, Rank... 
Don't know if we have enough with default Limited/Espectator roles, but maybe you can add a simple button to show or hide, like in Sec. Abilites. 
For example,  for me, "initial" view would be perfect with only: portrait, name, Demeanor, aspect/description, and concept. The public info that you can see or know easily.

(Sometimes it seems that we just want to give you more work! Thx for all the work, btw :) )

**Comment by JohanFalt** [comment]
I'll restrict what a non-owner may see in Bio but to create a specific ruleset what you can set for yourself I think is to make things more complicated. The general rule will be that if you can see the Bio stat as you look at the person you will be able to see it.
