### ISSUE TITLE
fix alignment

### ISSUE THREAD

**Issue by andersonalmeidda** [JohanFalt/Foundry_WoD20#543]
![image](https://user-images.githubusercontent.com/125048196/221373975-17b59959-22f6-41f4-af4f-d2dbdf1c7b24.png)

Hello, is there anything I can do to fix the alignment of the attributes in the middle of the sheet? Since the last update it has been misaligned.

Thanks

**Comment by JohanFalt** [comment]
Is that in all sheets?

Haven’t seen that myself, but will investigate.

What screen size do you use?

**Comment by andersonalmeidda** [comment]
yes it's on every sheet. 1920x1080

**Comment by JohanFalt** [comment]
You using the following?

![image](https://user-images.githubusercontent.com/57871596/221417583-31b67c2d-7f23-4790-b575-8469195d9083.png)

**Comment by EldritchTranslator** [comment]
This also happened to my player, who was using Chrome, but I can't reproduce it at all. Both Foundry and the system are fully updated.

**Comment by JohanFalt** [comment]
Yes me too. It was an old sheet.

What think is wrong if I could understand how is that the changes in how specifications is messing with it. If I just could understand how.

**Comment by JohanFalt** [comment]
Ok, one problem - I don't have a font-size 7 so I need more information where to set the font-size to correct this.

**Comment by JohanFalt** [comment]
So I need som help here to know what to change.

**Comment by JohanFalt** [comment]
ah! will fix.
