### ISSUE TITLE
[Feature Request] Expand dice roll options to include Virtues.

### ISSUE THREAD

**Issue by RinVindor** [JohanFalt/Foundry_WoD20#545]
As the title, there are rolls that require Virtues such as the V20 Animalism power Drawing Out the Beast on page 132 of the core V20 book which uses Manipulation + Self-Control/Instinct.

**Comment by JohanFalt** [comment]
You should be able to do that. It is the vampire sheet?

**Comment by RinVindor** [comment]
Within the Discipline Path powers I don't see an option for that.

**Comment by JohanFalt** [comment]
![image](https://user-images.githubusercontent.com/57871596/221516403-86b8ee42-662b-4fa5-8171-12a5d8a2a413.png)

**Comment by RinVindor** [comment]
🤦‍♂️Whoops. Any chance we can have the drop down better separate them for those of us who are clearly visually challenged? 😂

**Comment by JohanFalt** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/57871596/221848280-bc653777-9678-4e49-a442-51fbf926b663.png)
