### ISSUE TITLE
[Dark Ages] The problem with Paths

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_WoD20#547]

**Comment by GrimGaia** [comment]
Hi! How has this been implemented? I'm using 3.0  on 11.301 and I can't write down the paths, or select paths other than the new ones. Paths from dark ages like the path of screams isn't available.

**Comment by JohanFalt** [comment]
It hasn’t been released yet. If you check this issue is connected to a milestone called 3.1 once all the issues are fixed in that one a new version will be released.
