### ISSUE TITLE
CSS Tag Bug with Actor Sheet Combat Tab Descriptions (confirmed on Werewolf Sheet)

### ISSUE THREAD

**Issue by illandhil** [JohanFalt/Foundry_WoD20#553]
The tooltiptext class for Description popup text is displaying the CSS tags for the Description box instead of converting to CSS due to rendering in quotes.

The files with the bug are referenced at the following lines in the following parts that I could confirm:
templates/actor/parts/combat_melee.html - line 83
templates/actor/parts/combat_natural.html - line 76
templates/actor/parts/combat_ranged.html - line 83

I resolved this issue by adding an opening and closing curly bracket to {{item.system.description}} in each part:
Current line: <b>{{localize "wod.labels.description"}}:</b> {{item.system.description}} 
My change: <b>{{localize "wod.labels.description"}}:</b> {{{item.system.description}}} 

After making this change on my local install the Description popup renders the CSS correctly. I referenced this difference from the Gifts part templates/actor/parts/gifts.html - line 108. The implementations seem to be different but the 3 curly brackets instead of two did resolve my issue. Not sure if this is the actual fix but wanted to bring it to your attention none the less. So hopefully it won't re-break in the next release.

Thanks.

**Comment by illandhil** [comment]
This bug presents itself on 2.4.7.

**Comment by JohanFalt** [comment]
I'll do a revision of this, seems I missed a few of these. Thank you for the issue reported.

**Comment by JohanFalt** [comment]
I found the same problem with Rotes so I fixed it there as well. Will be shiped out in next version though I don't think I'll do a part release for this given it is at this stage quite a hassle. But thank you again :)
