### ISSUE TITLE
(compatibility): Lack of scoped CSS styles can lead to issues w/ modules

### ISSUE THREAD

**Issue by typhonrt** [JohanFalt/Foundry_WoD20#554]
Greets... An issue was reported for Forien's Quest Log on WoD20 system:
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues/30

The problem has to do with a lack of proper scoping for game system styles. Most of the system styles use single classes or basic combinations of such. This can easily conflict with add on modules that use those same CSS classes. 

The FQL module scopes CSS styles specifically to FQL apps, but in this case the WoD20 styles in particular this section (`.row`):
https://github.com/JohanFalt/Foundry_WoD20/blob/main/css/wod.css#L447-L458

Causes this result in FQL:
<img width="1475" alt="Screen Shot 2023-03-14 at 5 40 09 PM" src="https://user-images.githubusercontent.com/311473/225173981-3fdeaa45-ce0d-4e70-824a-716d28e36a0d.png">

My suggestion is to better scope the game system styles otherwise conflicts like this might be pretty common. FQL is game system agnostic so works with any game system.

**Comment by JohanFalt** [comment]
Thank you for bringing this to my notice. I'll start look into the whole thing and fix it in some what.
