### ISSUE TITLE
Use specialty checkbox issue

### ISSUE THREAD

**Issue by IronHowdy** [JohanFalt/Foundry_WoD20#557]
I use a house rule that a 10 on the die always count as two successes. Is it possible to make it so I can toggle a general 'double success' system setting? I'd like for the dice rolls to calculate all 10s as two successes every time but as it is even toggling the use specialty box doesn't work unless the sheet actually has 4 dots in something.

**Comment by JohanFalt** [comment]
What are your rules about specialities in that case? As 2 successes on rolling 10 is that rule.

**Comment by IronHowdy** [comment]
Anything that has 4 dots in it gets 1 bonus dice so that the specialties are still useful but I really dislike the idea of a 1 being a double fail without also having an equal possibility of double success on a 10. In an ideal world I'd be able to give bonus dice to both attributes and abilities as well as making it so that all 10s are a double success. I realize it probably sounds strange but within the context of our table it works very well. However having to manually add bonus dice and double checking if the successes are correct slows down the game a lot.
