### ISSUE TITLE
[Bug?] Armour Dexterity Penalty and Positive numbers.

### ISSUE THREAD

**Issue by Grandsome** [JohanFalt/Foundry_WoD20#563]
I just realised that positive numbers in the Dex Penality of armour items add to the Dex score of actors rather than substracting it.
Is that the intended behaviour?

![image](https://user-images.githubusercontent.com/32459440/231355815-6301135e-72f3-410a-8604-98e36d8f8f58.png)

![image](https://user-images.githubusercontent.com/32459440/231355868-a6775fd8-ea9f-4563-be4e-bc8e2ce42b6c.png)

**Comment by JohanFalt** [comment]
It is implemented by reducing the value by the penalty so it should be -1 for biker jacket and -2 for leather duster. Maybe should have that as a selector or something by then you can't enter whatever value you wish.

As you have added these you get a dexterity bonus using the armor.

**Comment by Grandsome** [comment]
Oh, I see now, I've got to go over all my implemented npc and player actors and fix them.  XD Or find some macro to do it. BTW is there a plan to have items "prototypes" so that one edit in a compendium changes the values of all instances of an item?

**Comment by JohanFalt** [comment]
Yeah I have an issue about that it has just come a bit low prio at the moment. I want to get the line done first then I will see what the order will be in the end. At the moment it is stuff like Dark Ages and Wraith.
