### ISSUE TITLE
Request: add things like blood pool etc to all sheets

### ISSUE THREAD

**Issue by Crowhazard** [JohanFalt/Foundry_WoD20#572]
Would like to create abomination (Werewolf vampire) and weird creature but i can't for example add things like a changeling who became a ghoul or a mage that is a kinfolk etc. that would be cool and not so hard to implement?

So if you for example let people add blood pool to other sheets it would let us create things that are actually within the rules (Ex: mage ghoul, werewolf ghoul, changeling ghoul, mage kinfolk, etc) hope you can be positive thanks anyway cheers.

Also would like a way to make bigger blood pool in that case (some rules for ghouls in ghouls and revenant)

**Comment by JohanFalt** [comment]
This will come up as a setting under Settings -> attributes.
