### ISSUE TITLE
Demon - The Fallen - More Apocalyptic Forms

### ISSUE THREAD

**Issue by Amovitam** [JohanFalt/Foundry_WoD20#573]
Hey :)
Not really an Issue...but is there a way/option, to add more than 8 apocalyptic forms to the character-sheet?
If not: Is there a way for you to add this option?

**Comment by JohanFalt** [comment]
Try creating a Trait item marked as an apocalyptic form (I think you can).

then pull that to the sheet.

**Comment by Amovitam** [comment]
Mhh...thanks for your quick response :)
But it seems like it does not work that way :/
I can't mark a trait as an apocalyptic form
I can choose between "Secondary Talent/Skill/Knowledge Ability", "Resonance" and "Other Trait". But I must admit: I am new to foundry :D

**Comment by Amovitam** [comment]
> Try creating a Trait item marked as an apocalyptic form (I think you can).
> 
> then pull that to the sheet.


Mhh...thanks for your quick response :)
But it seems like it does not work that way :/
I can't mark a trait as an apocalyptic form
I can choose between "Secondary Talent/Skill/Knowledge Ability", "Resonance" and "Other Trait". But I must admit: I am new to foundry :D

**Comment by JohanFalt** [comment]
Hmmm so there are most likely a very simple solution by just adding so you can create apocalyptic forms. Problem is that once you have added it to the sheet, you can't remove it again just change it.
