### ISSUE TITLE
[Changeling] Marking Imbalance

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#574]
Imbalance is a mechanic in Changeling that does not have its own tracker on the sheet. Page 275 of the C20 rulebook has this to say on the subject:

> When a character’s Nightmare rating reaches 10, the player removes all the Nightmare points from the character sheet and then marks an imbalance by circling the character’s rightmost Willpower box (underneath the last dot of Willpower, reading left to right). The Willpower point represented by that box functions normally, except that the character suffers a Bedlam Threshold (p. 294) if she spends the Imbalanced point of Willpower. If all of a character’s Willpower becomes Imbalanced, she is lost to Bedlam. Marking an Imbalanced Willpower also regains one point of Glamour.

At this point in time there is no way to mark the imbalance on the sheet. This isn't as common as, say, regaining glamour, blood pools, etc.

My suggestion for how to implement is that when a sheet is "unlocked" and other things appear (Such as the specialties box, humanity: bearing, etc. for example.) there is a small tickbox tracker above/below the willpower boxes that can be marked that circle the the affected box.

Locked sheet:
![image](https://user-images.githubusercontent.com/117007321/234145184-5237ed7d-aa45-4f6f-bdc8-f7c376dbb64e.png)

Unlocked sheet:
![image](https://user-images.githubusercontent.com/117007321/234150618-25e2c4f7-e65e-4a9b-bce5-b23073b214d5.png)

As a sort of suggestion. I realize that circle is clunky, I just threw a fat one there for the visual.

**Comment by JohanFalt** [comment]
From the wiki:

To record the sheet's imbalance rating you right-click the permanent Willpower dot you wish to turn/unturn to show imbalance or remove it.

**Comment by SeaSaltSong** [comment]
Oh, wonderful, thank you. I noticed it does the whole row of dots rather than just the right most one (Since it's tracked from right to left instead of left to right. It's a really weird mechanic) but I can just have my players mirror how they spend willpower instead.

Thanks!
