### ISSUE TITLE
[Feature Request] Ammo Counter

### ISSUE THREAD

**Issue by Grandsome** [JohanFalt/Foundry_WoD20#576]
Since some weapons have clips in the game, I've been wondering if an ammo-counter and reload mechanic could be implemented down the line in the system instead of using scratch marks on the wall like currently.

Thanks.

**Comment by RinVindor** [comment]
Wanted to say this would be a nice option for those who enjoy combat. The Chronicles of Darkness implementation is a very pleasant way to handle it with ammo being swappable. ie, you give your players various ammo options like silver bullets.
