### ISSUE TITLE
Exploding dice

### ISSUE THREAD

**Issue by Sandvich** [JohanFalt/Foundry_WoD20#577]
Hi,

We're setting up werewolf on foundry, but we've noticed that the 10s don't explode, even when rolling something where the character is specialised.
Is this a known issue, or is this something we did wrong?

Also, we usually use an alternate system whereby 10s always explode and specialities reduce the difficulty by 1 - is it possible to add this as an optional houserule?

**Comment by JohanFalt** [comment]
In WoD20 dices doesn't explode on 10s. Instead if you have a speciality on an ability or attribute and roll a 10 you get 2 successes instead of the normal 1.

**Comment by JohanFalt** [comment]
So with exploding dice do you mean:

As a 10 comes up you gain an additional die to roll and if that too comes up as a 10 it explodes again, and again until no more 10s comes up?

**Comment by Sandvich** [comment]
Yeah, so my GM checked the rules after, and it turns out this is a thing from 2e. Our group likes it though, so he's keeping it on as a house rule.

And yeah, if it comes up as a 10 you get an extra die, and the 10s keep exploding. You can theoretically get infinite successes.

**Comment by JohanFalt** [comment]
I add the option in the coming version. There will be two settings for this - the specification rule and exploding 10s.

**Comment by Sandvich** [comment]
Thank you :)
In the meantime we'll just roll the extras manually.

**Comment by JohanFalt** [comment]
This is connected to v3.1 and even if I can’t really say when that version is done you can follow the progress by checking how many issues remaining in the milestone.

what has been released was a quick version for Foundry v11.

**Comment by Sandvich** [comment]
Ah, I didn't notice it was in the milestone, thanks :)
