### ISSUE TITLE
[Changeling] Sheets Tweaking

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#578]
Long story short, my irl game is moving to foundry in the next couple months. While setting up changeling I've noticed some opportunity for quality improvements. Hope I'm not too annoying asking for stuff like this. 

## 1.  When rolling an art there is no option to voluntarily replace 3 dice with nightmare dice
> pg. 275
>Players can reduce the difficulty of a cantrip roll by 1 by replacing another three dice in the pool with Nightmare dice. The character must have three non-Nightmare dice in the pool to gain this benefit. Doing so does not increase the character’s Nightmare pool past that one roll (unless the player rolls some 10s, of course).

I recommend a checkbox similar to specializations in the roll prompt. If there are not enough dice in the dice pool to convert, this box can be greyed out and unable to be clicked.

## 2. Health Tracker
Can this be moved to the Core section of the sheet? It's weird that all the other sheets (Vampire, Werewolf, Demon, etc.) Have the health tracker in core at the bottom right, but Changeling is the only one with it in another tab. Above Ravaging/Musing Threshold makes the most sense.

## 3.  Musing/Ravaging threshold is awkward
The text box for this JUST too small. Could it be made to change size based on the total text that is saved there? This is honestly the most minor/nitpicky/non-issue thing I have.

## 4. Revelry has no place on the sheet 
Revelry is a once per story method of completely refilling glamour. The methods are specific to each kith type and the descriptions are about a paragraph long. Below Musing/Ravaging would be best, and a similar text box/method of recording it.

## 5. Birthrights & Frailties
These text boxes are small for what they are. I had to do a workaround where I entered them in as 0 point merits/flaws and made a note in the boxes to look there.

I'd suggest removing them from the bio page entirely and implementing a text box similar to the musing/ravaging. 

## 6. Houses
So, houses are really weird. On the surface it seems just one line is enough, but in reality there are mechanical benefits and drawbacks to being a member of a house. Each house has a boon and a flaw, and each description of them can be 2 paragraphs long. They're almost full powers in their own right.

This deserves a full text box like a bio. 

## 8. Affinity Realm
The character's affinity realm is hard to distinguish since it's only bolded. Can it get a green pip next to it similar to specialties? This will make it more distinguished for the players that need the extra help.

## 9. Nightmare Legacies
Nightmare legacies are legacies that can replace either your Seelie or Unseelie legacy. These are exclusive to Thallain, which are typically NPCs, but worth noting.

<hr>
<hr>

I know it's kind of a lot that I posted. If it's easier for you I can separate these into several different posts. I wanted to thank you again for being so active on this project.

**Comment by JohanFalt** [comment]
I’ll place this in v2.5 but most likely it will be in 2.6 especially given the timeframe.

**Comment by SeaSaltSong** [comment]
Totally fair.

I also wanted to add two things as I am entering the arts now.

## 10. Rollable Arts
I am 99% sure every art gets rolled to be used, so the checkbox is redundant. There might be an art that doesn't require a roll, but I haven't seen it


## 11. Type: Chimerical or Wyrd
Each power is either Chimerical, Wyrd, or varies. A way to see this from the character sheet would be AMAZING. This effectively asks if the effects are visible by regular people or not.  For now I am putting it in the name of the power.


## 12. Art dropdown not working
I cannot select Arts on the powers item that I have created like I can for vampire. Something got broken along the way.

**Comment by JohanFalt** [comment]
As I will start working on the Changeling Sheet today and forward I'll split these points up into indivudual issues. 

If you have more things you can come up with please create a new issue.

**Comment by JohanFalt** [comment]
https://github.com/JohanFalt/Foundry_WoD20/issues/606
https://github.com/JohanFalt/Foundry_WoD20/issues/607
https://github.com/JohanFalt/Foundry_WoD20/issues/608
https://github.com/JohanFalt/Foundry_WoD20/issues/609
https://github.com/JohanFalt/Foundry_WoD20/issues/610
https://github.com/JohanFalt/Foundry_WoD20/issues/611
https://github.com/JohanFalt/Foundry_WoD20/issues/612
https://github.com/JohanFalt/Foundry_WoD20/issues/613
https://github.com/JohanFalt/Foundry_WoD20/issues/614

**Comment by JohanFalt** [comment]
I think I will do as following. 

I am fixing up the graphics in general of all sheets and given the amount of information needed to the Changeling one I think I will just alter as you suggests and not try to do this perfectly. Sure this will mean that Bio will be very long but for this version I think that is ok. In this case - function before style.

Then in 3.2 I'll see what can be done to maybe improve Bio all in all.
