### ISSUE TITLE
Problems with the Spirit character sheet

### ISSUE THREAD

**Issue by WattGrego** [JohanFalt/Foundry_WoD20#579]
Hi! I'm working on making a compendium of antagonists in Werewolf, and I noticed some problems with the spirit actor type.

1. Adding a Charm to them doesn't seem to connect to their Rage/Gnosis abilities. Attempting to roll the Charm from their sheet does nothing. Same with Gifts.
2. The Appearance/Background boxes on the Bio tab are a little funky. They're cut off about halfway and can't be scrolled on.

Just a very minor issue I noticed. Thanks!

**Comment by JohanFalt** [comment]
1. Patch coming out.
2. Assume this also is Spirit sheet? You sure you have latest version? Mine look as follows:

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/a364350e-cb23-4056-ace3-cef8e3d598bb)

**Comment by WattGrego** [comment]
Yes, I have the latest. I keep having a problem with putting text in. If I copy/paste a large block of text in, the bottom half of it is covered up until you move the cursor down with arrow keys - scrolling doesn't work. This problem usually clears up if I close the sheet and open it again.
