### ISSUE TITLE
[Bug] Missing Edit/Remove buttons from inner items for Backgrounds.

### ISSUE THREAD

**Issue by Havoclivekiller** [JohanFalt/Foundry_WoD20#580]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/21118924/46b1f725-2fcd-4ec6-80f6-b0f45c50339c)
This is on Vampire sheet.

**Comment by JohanFalt** [comment]
Is this something you need right away or just something you discovered? Reason I ask is that I would like to place it in the general release of v2.5 but if you need it like NOW then I can release an update for it.

**Comment by Havoclivekiller** [comment]
I personally don't need it as it is just bonuses. (My player wanted to list all his ghouls using this but didn't know it was for bonuses).

**Comment by JohanFalt** [comment]
If you wish to list your ghouls I would add that to the description. Bonuses are more if you have a feature that add automatically to your sheet. Like +2 strength.

I'll make sure this comes out in my next update though so he can clean it up again.
