### ISSUE TITLE
Token image not displayed on sheet.

### ISSUE THREAD

**Issue by rsimmerm** [JohanFalt/Foundry_WoD20#587]
Hello,

I'm first time user of your module as I'm working on a new VTM game.  I loaded some token/images for some characters and the images show up when pulled to a scene, but they don't display on the actual sheet.  

Screenshot:
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/8026848/2bc925a1-0823-4572-b73e-635ea5646d17)

**Comment by JohanFalt** [comment]
You do it the other way around. First you add the image to the sheet then as you drag the actor to the scene the image is added to the created token.
