### ISSUE TITLE
Foundry VTT 11 update

### ISSUE THREAD

**Issue by sciwiz12** [JohanFalt/Foundry_WoD20#588]
After updating yo Foundry VTT 11 build 299 the wod core seems to no longer be compatible. Can I get an eta on the update?

**Comment by JohanFalt** [comment]
A few months most likely. My recommendation is that you take the V10 backup you took before the upgrade and downgrade again.

**Comment by JohanFalt** [comment]
Due to how little there are to fix for v11 I have made a release for it which should be out within an hour.

**Comment by sciwiz12** [comment]
Thank you thank you thank you.
