### ISSUE TITLE
Difficulties, could you review it

### ISSUE THREAD

**Issue by M4lkav** [JohanFalt/Foundry_WoD20#589]
In the book Vampire The Masquerade 20th anniversary it says the following.

Pag. 249
Difficulties
There's no point in rolling says unless you know what results you're looking for. Whenever you try to perform an action, the Storyteller will decide on an appropriate difficulty number and tell you her decision. **A difficulty is always a number between 2 and 10** (but generally between 3 and 9).

Maybe I'm wrong but when I try to reduce the difficulty below 3 with your module it doesn't allow me.

I take this opportunity to thank you for your excellent work, thanks to you I have been able to share many hours of fun with friends that I cannot see in person due to distances.
![File](https://github.com/JohanFalt/Foundry_WoD20/assets/134603065/9f9c5960-f4d0-458e-995f-745d0458ebee)

**Comment by JohanFalt** [comment]
I'll fix this. I do think it is a remnant of my werewolf campaign.
