### ISSUE TITLE
Can't roll Initiative from the Character Sheet for Changeling the Dreaming

### ISSUE THREAD

**Issue by Tarmorax** [JohanFalt/Foundry_WoD20#616]
If you try to use the "Roll for Initiative" button on a player's character sheet, it doesn't work. If you look inside the console, it says that it's a ReferenceError because specialDiceType is not define inside combat-helpers.js line 75.

The problematic line is: 'specialDiceType = "black_";'

I'll put some screenshot that display the errors. 

![InitiativeButton](https://github.com/JohanFalt/Foundry_WoD20/assets/3279088/6ab6c30f-6ef4-4935-8482-8099adbed2bb)

![CombatHelperError](https://github.com/JohanFalt/Foundry_WoD20/assets/3279088/c1693929-9bec-47cf-903b-e6ca515ac9da)

![NotDefined](https://github.com/JohanFalt/Foundry_WoD20/assets/3279088/2f526b29-c1fb-4cfd-bcce-e5e3fb32134e)

Thank you for your work on the system.

**Comment by JohanFalt** [comment]
Easy fix new patch will be out this morning.
