### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#627]
1. "Edit Merit" and "Edit Flaw" buttons have wrong localisation.
2. When switching the sheet to Victorian mode, the custom "Ride" trait that appears is unrollable, undeletable and it shows a message that "Item ID doesn't exist!"
3. When switching the sheet to Victorian mode, the "Drive" trait remains.
4.  I know that Victorian rules are from Revised edition, but in the Era Selector it's said "Victorian Age (20th)". Despite this it still adds "Dodge" and "Linguistics" and "Security" traits from Revised. Not a bug per se, just a little unclear.

**Comment by JohanFalt** [comment]
1. Fixed in v3.1.1
2. Fixed in v3.1.1 I think as I can't duplicate it any longer.

**Comment by JohanFalt** [comment]
3. These are the official abilities in Victorian era:

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/473f39b7-4597-4440-af10-17a5704080bc)

**Comment by JohanFalt** [comment]
4. That is for vampire right? Hmmm I'll ask some people that should know stuff like these.

**Comment by TheFokin** [comment]
> 4. That is for vampire right? Hmmm I'll ask some people that should know stuff like these.

Not only for Vampire, but for Mortal as well. Granted, there are no official rulesets for these, but V20 (and all other 20th Aniiversary splats) don't have these three traits at all. There are unofficial books set in Victorian era for V20 Ruleset (like Vampire the Wild West), and you can look at mrGone V20 Victorian sheets for reference,
