### ISSUE TITLE
Missing translation keys

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#628]
In the lastest version, 3.1.0, the character sheets have some translation keys missing. Here are the ones I found:

All sheets:
- LANG: Wiki
- LANG: Settings
- LANG: Edit ability
- LANG: Specialty
- LANG: Alternative ability name
- LANG: Select damage type (for changeling this is both in chimerical and normal)
- LANG: Other items
In the settings: 
- LANG: This setting sets the maximum value an ability can have
- LANG: The total value used in soak with attribute, armor bonus
- LANG: Bonus - extra bonus to soak
- LANG: Can soak - if soak if this type of damage is normally allowed
- LANG: Value the base calculated value based on total value of attributes
- LANG: Bonus - extra bonus to initiative
- LANG: Total - the total value used in combat with all active bonuses
- LANG: Graphics
Banner:
- LANG: Set sheet to (x) era!
Mage sheet:
- LANG: Use technocracy version
- LANG: Specialty (in Spheres)
- wod.labels.customaffiliation
Creature sheet:
- LANG: No (ability) selected
- LANG: Set Sheet type
- LANG: Autumn people
- LANG: Chimera
- LANG: Dreamer
- LANG: Ghoul
- LANG: Kinfolk
- LANG: True Faith
- LANG: Setting this only sets the sheet to activate the advantages the choosen type uses.
- LANG: Possible system settings are NOT over-ridden.
Changeling sheet:
- LANG: Revelry

As well as all the section titles in the dropdowns in create new actor and new item.

**Comment by EldritchTranslator** [comment]
Also:
- wod.labels.edit.merits
- wod.labels.remove.merits
- wod.labels.remove.flaws (which is both on the edit and remove buttons)
- wod.labels.edit.experience
- wod.labels.remove.experience
In the Bonus window, the dropdown titles
- LANG: Attributes
- LANG: Abilities
- LANG: Other

**Comment by JohanFalt** [comment]
I don't have any LANG: on my end at all... I'll see if things improve with v3.1.1

**Comment by JohanFalt** [comment]
wod.labels.edit.merits
wod.labels.remove.merits
wod.labels.remove.flaws (which is both on the edit and remove buttons)
wod.labels.edit.experience
wod.labels.remove.experience

I found

**Comment by JohanFalt** [comment]
Fixed in v3.1.1.
