### ISSUE TITLE
Mage Sphere alternative names issue

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#630]
In 3.1.0, selecting the checkbox for the Spheres of Force and Life doesn't switch to the alternate names.

**Comment by JohanFalt** [comment]
Just a question... should the sheet react if you select that you are technocracy to set all Sphere's to technocracy names?

Like wise if you are other than technocracy you set them to "normal".

**Comment by EldritchTranslator** [comment]
You can decide: I _think_ all technocrats use sciences, but there are also tradition mages that use a mix of sciences and spheres, so it depends on how it works for you.
