### ISSUE TITLE
The character sheet era/type switch doesn't work in Mage and Mortal/Creature sheets

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#633]
In 3.1.0, you can't switch sheet eras in the Mage sheet, and the different sheet types in the Mortal and Creature sheets are likewise unselectable.

**Comment by JohanFalt** [comment]
Please try again with v3.1.1.

**Comment by EldritchTranslator** [comment]
The eras are selectable now, but the sheet types (chimera etc) have disappeared from the Creature and Mortal sheets.

**Comment by JohanFalt** [comment]
That is a feature I had thought to release in v3.1 but it will come in v3.2.
