### ISSUE TITLE
Issue with option explanations in settings

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#636]
I think there are a few mistakes in the options of the following menu:
![immagine](https://github.com/JohanFalt/Foundry_WoD20/assets/56313572/dd8e070f-d7b4-4dc4-9f89-d05310baafb4)

1. The 'Lowest difficulty allowed' is the same as the first option;
2. '10s explode handling' looks like a truncated sentence to me.

**Comment by JohanFalt** [comment]
LOL copy/paste doing fun stuff.
