### ISSUE TITLE
[Bug/Feature Request] 3.1.2 Mage Sheet Typos and other Design Pointers.

### ISSUE THREAD

**Issue by Grandsome** [JohanFalt/Foundry_WoD20#639]
Awesome work on the new interface but...
### There are a few bugs in the new UI:

- A typo in the spell rolling window and there's an alignment problem with the word "correspondence":

![Capture d’écran 2023-07-22 132124](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/cb1a222a-1c29-4382-8608-6d578d906877)

- The magic tab doesn't seem to respond to change in window size and the spell names are foreshortened at random, also the description of spells is leaking in the title:

![Capture d’écran 2023-07-22 132334](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/9bb444a6-f13a-4892-8e97-6d15c644404f)

Old UI for Comparison:
![Capture d’écran 2023-07-22 124838](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/da526ddd-8b75-4892-8519-74ba8bb80eff)

(Also, the main sphere indicator could use some work, maybe just an underline or a star, I dunno.)

I know that UI design is hard, so the following criticisms are for the sake of better readability/usability.
### Minor gripes:

- The new bold fonts are somehow harder to read and freak out Windows clear text, I don't know if it's only a render problem on my end, or my eyeball mk1, but some experiment with different typeface, serif and weight might fix that and make the whole more eye pleasing:

New
![Capture d’écran 2023-07-22 133940](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/e027c391-deeb-41f8-9ca5-2c36f1964ba7)

Old
![Capture d’écran 2023-07-22 124757](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/099ae8c6-4d21-41c9-ad34-47d9ab8c4e38)

- The new bio boxes are huge and obscure the other boxes in the overflow, they could be smaller when empty and expand during editing, and also wrap almost exactly around the amount of content in them:

![Capture d’écran 2023-07-22 134400](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/becb49e4-2d65-4591-ba6f-f2d59fa09627)

- I don't know if it was a style design, but the alignment of chat messages is touches the chat bubble box side, also the font could be a little more bold in the chat box for readability:

![Capture d’écran 2023-07-22 132732](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/2dddb20d-c083-4cd4-95dd-78fb9e921bfa)

- Not all part of the UI respond to windows change the same, not sure if a bug or just a limitation:
![Capture d’écran 2023-07-22 140914](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/af963ab4-167b-4209-b8f9-3eb9a577890e)

### Feature Request

- Bring back the title of the tab buttons:

It would help when guiding players around the interface. I've highlighted some buttons whose icons are not super explicit that might either need new icons, or a title to discriminate them. 

Tough, the whole section in the bracket could use a title for uniformity and clarity. Also speaking of section tab button, the active section indicator could be a little bolder or explicit than a little shadow (sometime a big ugly selection square is what is needed lol).

![Capture d’écran 2023-07-22 140312](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/208603f9-0f49-4345-a477-2d86ea415dd7)

- Darker background colour:

The old UI had a darker background colour that helped readability, dunno if it's just a me problem or if I was spoiled with darkmode, but the new bright grey background is a little too violent for the eyes.

### Thanks Section
Thanks. :-) Awesome work.

**Comment by JohanFalt** [comment]
I'll see what I can do.

**Comment by JohanFalt** [comment]
- [ ] Available spheres
- [ ] Rote listnings alignment
- [ ] Font problems
- [ ] Bio boxes
- [ ] Width of sheet
- [ ] Chat messages
- [ ] Show what icon means
