### ISSUE TITLE
WtA Token Status Shapeshifting

### ISSUE THREAD

**Issue by Ringelpiez** [JohanFalt/Foundry_WoD20#660]
Shapeshifting icons will stack instead of switching.

![WoD20_WtA](https://github.com/JohanFalt/Foundry_WoD20/assets/107757109/b7a206de-75de-4618-b100-d2452bf0a87d)

**Comment by JohanFalt** [comment]
There is something that has changed how effects are applied to a token which causes this problem. I have removed it and the next version should purge these icons as you shift forms.

**Comment by JohanFalt** [comment]
My fix didn't work so I have decided just to remove the function all together and remove these effects on the tokens. This will occur as you start your game with v3.1.6.
