### ISSUE TITLE
Localization typos, errors and missing keys

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#661]
Those I managed to spot.
1. wod.games.mage is set to "Mage the Ascen**t**ion"
2. wod.types,vampire is missing for some reason, but it was present in previous iterations.
3. wod,bio.tips is set to "Rolplaying Tips",
4. wod.labels.edit.artpower is set to "Edi**y** art power".
5. wod.labels.remove.art is set to "Rem**n**ove art",
6. It's wod.labels.show.traits in the localization file, but wod.labels.show.trait in the sheet
7. wod.dialog.aretecasting.availspheres is set to "Avail**i**ble Spheres"
8. Add buttons in "Combat" tab are missing their titles. All but "Add Melee Weapon" which is set to "Add Other Trait"
9. "Edit" and "Remove" buttons for powers have wrong localization keys (for example, instead of wod.labels.edit.art wod.labels.edit.artpower)
10. "Remove connected bonuses to discipline/path/art/etc." button doesn't remove bonuses, but disassociates powers one by one. Not a strictly localization error, I presume, but still.

**Comment by JohanFalt** [comment]
Thank you :)

**Comment by JohanFalt** [comment]
2. wod.type.vampire is never used so that is really why.
10. Which icon were you referring to:

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/8b9a5ff3-ae0b-4844-8af5-f1918fe6b761)

**Comment by TheFokin** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/b0ccae20-94d3-4eef-b1a0-dea518504b96)
This one

**Comment by JohanFalt** [comment]
That was a good catch. The language didn't make sense at all. Now fixed.

Thank you again.
