### ISSUE TITLE
WTA - Chaning Breeds wont let you actually select a breed.

### ISSUE THREAD

**Issue by mnwolfboy** [JohanFalt/Foundry_WoD20#675]
There is a weird issue where we can not select a changing breed from the drop down list. It just acts like a type in box, but then it turns into a drop down menu and you can see the list of changing breeds, when you go to select one, it just keeps saying -select- and not let you actually select anything. Out of random when i reloaded foundry it allowed be all of a sudden to select A breed, but then went back immediately to not allowing me to select again.

**Comment by JohanFalt** [comment]
I can't really reproduce this just by your description.

What version of Foundry do you use?
I assume you use WoD20 v3.1.6.

If you click on F12 and select Console before you make the shift. Do you see anything in red to your right? (looks as the image below)

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/f66cc847-802f-4036-a1b5-40e94d58fe7b)

**Comment by mnwolfboy** [comment]
Yeah I dont know that is weird then. I have system up to day, which is now even on 3.1.7, I have the foundry vtt also up to state on stable version. I disabled all modules just to make sure nothing is interfering, and it still giving me issue. Also hitting f12 and looking at the console I do not see anything out of ordinary. Looks like your screenshot.

**Comment by JohanFalt** [comment]
Ok let’s go through it all basic style:

1. Unlock sheet
2. Click the box
3. Does it unfold to show the different types?

**Comment by mnwolfboy** [comment]
So at first it likes to act like a type in box rather than a pull down. After I type gibberish there it turns to -select- box instead where I can than pull down and see the list of Changing Breeds. For a moment it will let me select something. However if im going through selecting different ones, it will hang up on a changing breed and not let me change it again. Like the pull down will still pull down but it will be hung up for example on Ratkin but wont let me switch to rokea. However I noticed when it gets stuck like this I can select ananasi for some reason that unsticks it for a moment. Weird as heck.

**Comment by JohanFalt** [comment]
And if you press F12 no red text?

**Comment by JohanFalt** [comment]
What version of Foundry do you use?

**Comment by mnwolfboy** [comment]
Foundry 11 stable 306

**Comment by mnwolfboy** [comment]
It givers me this for errors but i think its just because foundry doesnt like my small monitor and only complains about my resolution when i have console up. theme.min.js:4 Uncaught TypeError: Cannot read properties of null (reading 'innerWidth')
    at RO.<anonymous> (theme.min.js:4:294222)
    at oO.dispatch (tinymce.min.js:4:378965)
    at RO.dispatch (tinymce.min.js:4:380219)
    at Array.<anonymous> (tinymce.min.js:4:406854)
    at Re (tinymce.min.js:4:5335)
    at Object.PO (tinymce.min.js:4:406764)
    at ba.executeHandlers (tinymce.min.js:4:52835)
    at i (tinymce.min.js:4:50673)
foundry.js:68050 Foundry Virtual Tabletop requires a minimum screen resolution of 1024px by 700px or greater. Your display currently has an effective resolution of 676px by 837px, as a result many features of the software may not work properly.

**Comment by JohanFalt** [comment]
Its a Foundry 11 problem that I managed to recreate. Fix will come.
