### ISSUE TITLE
[Bug] Sheet is not opening

### ISSUE THREAD

**Issue by Puoko** [JohanFalt/Foundry_WoD20#678]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/140884165/d79963bd-04f8-4beb-829d-cd3dfd6b8afc)

Whenever I try to open a random type of sheet, I'm getting this error and the sheet is not opening. I can only open creature sheets, but not all the other types. I can create the sheets, but I can't open.

**Comment by JohanFalt** [comment]
So in your case you open a newly created  demon sheet?

what version of Foundry?
Any difference if you don’t use modules?

**Comment by JohanFalt** [comment]
Is the user creating and opening the sheet of GM permission?

**Comment by Puoko123** [comment]
@JohanFalt

I don't know what happened. I have four sheets that are opening and ok. But then I just can't open my newly created sheets, I'm the GM trying to open a normal sheet.

I'm using foundry 11, latest stable

I don't know about the modules because I didn't install "sheet changing modules" or something, just other modules at all, and I really don't want to recreate the world and lose all my progress and configs 😢

The users and me, we can open the first 4 sheets normally, but now I can't open the newly created sheets of any type, I'm getting the error of the screenshot when I click to open it

**Comment by JohanFalt** [comment]
If you create a sheet as GM can you open that one?

**Comment by Puoko123** [comment]
Yes, I, as GM, I'm creating new sheets and I can only open the creature type sheet but not the actor sheet types (demon, werewolf, mage and others)

**Comment by JohanFalt** [comment]
That is because the creature sheet don't have abilities, your world fail to load these

**Comment by JohanFalt** [comment]
No clue really why. But as an effect you have this newly created sheet and the system tries to give it abilities, but since there are none it crashes. I'll see how I can fix this.

**Comment by Puoko123** [comment]
Thanks for listening to me. And thanks for the job. I love your systems! I hope it works, because this is a huge problem for me, since I can't open new sheets. So I can't create new NPCs or players

**Comment by JohanFalt** [comment]
No problem at all really I was afraid something like this could happen. Can you check that there are a file called ability.json under the folder systems/worldofdartkness/assets/data/

**Comment by Puoko** [comment]
Yes, i have this file here
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/140884165/10042566-9be3-418d-9538-b645479dc0ed)

**Comment by Puoko** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/140884165/776b8c7a-f640-4395-98ee-802198bc79b0)
Whenever I click to open the new sheets, it independs of the type, and it is not opening, i just click and nothing happens, nothing except for this error

**Comment by Puoko** [comment]
I tried also to download the system again and replace it on the folder, but it didn't work

**Comment by JohanFalt** [comment]
So this is a permission thing, for some reason the user creating the sheet are not allowed to read the file. I'll see how to fix that.

**Comment by JohanFalt** [comment]
I’ll let you know when a fix is out that fixes this shouldn’t take that much time.

**Comment by Puoko123** [comment]
You're me hero. Thanks!

**Comment by JohanFalt** [comment]
V3.1.7 should fix this

**Comment by Puoko** [comment]
I'll try to update it to 3.1.7

**Comment by Puoko** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/140884165/d9ca70cc-406b-4fa9-981f-32dcb942878f)
I have an error when I try to update it.... :c

**Comment by Puoko** [comment]
And I also can't open the recently created sheets, or the new ones.

**Comment by Puoko** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/140884165/1733d96b-b73f-46cb-8182-41e817ab37f2)

**Comment by Puoko** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/140884165/0a0b0db4-8bcb-44b1-80be-61f2524c85ce)
Also, the options aren't giving the dropbox options

**Comment by Puoko** [comment]
If I create an new world, the character sheets are working fine, but it's a huge problem to migrate all my job to the other new world, specially compendiums. What can I do? :c

**Comment by JohanFalt** [comment]
I totally missed your posts here as the issue are closed. The solution to your original problems are in the new version. Please create a new issue about your problem to update.

What I need in this issue is the errors the migration caused.
