### ISSUE TITLE
Pop up descriptions

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#679]
Pop up descriptions of items in the sheet share style with many other places in the sheet. As a result, text in the description has big interline spacing and takes too much space.

**Comment by JohanFalt** [comment]
Do you have an example?

**Comment by TheFokin** [comment]
Sure
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/80a0b393-16ea-4a35-8766-8dd61906ec08)
I won't copy an actual description for copyright reasons.  Because of the bold text and big interline spacing, the text takes too much space.

**Comment by JohanFalt** [comment]
This will be fixed in 3.2.
