### ISSUE TITLE
Negative bonus in roll formula

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#680]
If a roll bonus is negative, it doesn't show up in the roll chat message
Roll 1 — no bonus 
Roll 2 — +1 bouns, shows up as "+1"
Roll 3 — -1 bonus, doesn't show up as "-1"
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/47924cc9-1398-4b63-9281-f5c4f1e2e667)

**Comment by JohanFalt** [comment]
What type of bonus do you select?

**Comment by JohanFalt** [comment]
Found it - the normal kind not permanent bonus to stuff

**Comment by TheFokin** [comment]
In this menu.
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/c537e1d7-e7bd-4ce8-b37a-68bf946d1dec)
Also, when you input the value and switch the focus from the field, the value visually resets to zero but is still accounted for.
Not a gamechanger, but confusing for players.

**Comment by TheFokin** [comment]
Additionally, I've been checking bonuses that are set up in Traits tab, and they don't seem to work at all.
Attribute bonus and Attribute dice bonus don't add extra dice to the dicepool, attribute difficulty doesn't affect difficulty, Automatic attribute successes don't add successes. Haven't tested them all.

**Comment by JohanFalt** [comment]
- [ ] If neg temp bonus not visible but functions are working.
