### ISSUE TITLE
Bonuses from traits are not applying

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#689]
I don't know, maybe I'm doing something wrong, but here are my actions step by step:
1. Create a Trait
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/64959325-052b-4d66-b628-f1245fe936fc)
2. Create a bonus
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/2f2f0331-b371-4318-9277-578a0f81f051)
3. Edit bonus, set it as an Attribute Bonus, Strength +1
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/fdc5dc34-0541-49f1-8536-872aa68003f0)
4. Activate the Trait
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/89bce6e7-3838-4444-8797-ea580733d94e)
5. Making a Strength roll
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/fa4d43df-96c3-4962-927b-073efc1a76d6)
6. Result: rolled 4 dice instead of five
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/19e3bb8d-7278-40ff-a0cb-20417fffe6f2)

**Comment by JohanFalt** [comment]
Your merit is not active.

**Comment by TheFokin** [comment]
How do I make it active if not by ticking the box?

**Comment by JohanFalt** [comment]
That is how you do it you check the box. The image you sent have the merit marked at “not active”

**Comment by TheFokin** [comment]
In step 4 I tick the box.

**Comment by JohanFalt** [comment]
![IMG_1148](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/e86c2be1-1862-4ab9-b5d0-40aafdfd5909)

this box needs to be checked

**Comment by TheFokin** [comment]
Yes, and I checked it at step 4.
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/34f6baac-9200-41ea-a568-651c6c4c6848)

**Comment by TheFokin** [comment]
I even tried to create a clean world with no additional module. The outcome is the same.

**Comment by JohanFalt** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/083a0b78-fcb0-40de-bc11-f269faf7d44f)

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/b52048ba-c736-4cdb-97a6-093a118d9fe8)

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/72f0e97f-ec43-4d01-ba66-082ae6a263ec)

**Comment by TheFokin** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/9decaa96-ab8e-4cd3-b7bd-63722f47e908)
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/de1b6931-0f3a-43a5-b12f-3698a0855348)
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/8ed66886-af20-4afe-a6da-3a9a09b5715b)
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/667735f4-ff1d-4014-ad60-4a2b9afff4d5)
Doesn't work on my end for some reason.

**Comment by TheFokin** [comment]
Aha. I reinstalled the system and it now works.
