### ISSUE TITLE
Traits and Bonuses lock up

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#690]
I don't recall having this issue before.
If I create a Trait and check the Activate bonus box, it locks and I can't uncheck it unless I reload the page. Additionally, such a trait cannot be deleted or edited until I reload the page.
If a bonus for a Trait is created before the lock-up, it locks as well in the similar manner.
If a bonus is created after the lock-up, it works fine, but when I try to delete the parent Trait, the bonus is deleted instead.
Sometimes, If I make a fresh World it works fine initially, but then this behaviour resumes.
When I tested it with Powers (Disciplines in my case) it worked fine initially, but then the behaviour spread to them as well.
Initially I thought that it's connected to the fact that I run the game not in English and use Cyrillic letters in the names of Traits and Bonuses, but I wasn't able to find a link between languages and the lock-ups.

**Comment by JohanFalt** [comment]
I did a quick test and I need more information than this. Are any errors visible in you open up F12?

I tested on Foundry v11 put can't reproduce this problem.

**Comment by JohanFalt** [comment]
Have you turned off all your modules?

**Comment by TheFokin** [comment]
I created a fresh world with no modules.
I even did a fresh installation of Foundry, as I thought maybe there are some issues piled up after migration from v10 to v11.
A fresh world on a fresh installation with no modules active.
I can check and uncheck these boxes fine unless a bonus is added. Then all of them lock up until a page refresh.
No error or warning messages in the F12 console. Can't spot any obviously anomalous behaviour, but I'm not that well versed in Java.

**Comment by JohanFalt** [comment]
I have been analyzing the code around shifting items active/inactive and it _can_ be a slow connection to the server which I can't really test. But I act as if that is the problem and add things to where things can go wrong.

**Comment by TheFokin** [comment]
I'll tinker around and try to look for the issue myself,
