### ISSUE TITLE
[Feature] Make Faith a Choice as a Rollable Stat in Powers Creation

### ISSUE THREAD

**Issue by sfckor** [JohanFalt/Foundry_WoD20#696]
**Is your feature request related to a problem? Please describe.**
I was creating True Faith Powers and the Faith Advantage is not listed as a Rollable Choice

**Describe the solution you'd like**
Add Faith to the list of choices under Rollable items when creating Powers

**Comment by JohanFalt** [comment]
I don't have a problem BUT...

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/dce4f824-46e7-4c17-8661-c0397f9955ca)

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/d56d2616-deb1-4387-9fdb-1e0b277e12a5)

Could be a settings problem, check world settings

https://github.com/JohanFalt/Foundry_WoD20/wiki/System-Settings#rule-settings

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/ea54878d-0d08-4009-bd5c-40538b8f33fd)

**Comment by JohanFalt** [comment]
Is this with the mortal sheet or demon one?

**Comment by JohanFalt** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/eb748e76-23dc-4e74-b485-888762643ca9)

**Comment by JohanFalt** [comment]
This is from the other trait boxes.
