### ISSUE TITLE
Add Changeling the Dreaming

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_WoD20#7]
New Sheet

**Comment by JohanFalt** [comment]
Advantages

**Comment by JohanFalt** [comment]
abilities

**Comment by JohanFalt** [comment]
![changeling](https://user-images.githubusercontent.com/57871596/184501122-2c026731-3435-43aa-9f13-71e1d8b47afa.png)

**Comment by EldritchTranslator** [comment]
There are a couple 'errors'; Changelings do not have Nature and Demeanor, they are completely overridden by Legacies. Because of this Legacies can be a one-line input box. House can stay a big input box, since I suppose you could put there the House boons and weakness. You would also need two more big boxes, one for the two Kith Birthrights and the other for the Frailty. There should also be space for the Changeling's Antithesis, which can be big or small.

**Comment by JohanFalt** [comment]
Something like this. Hasn't put boxes yet on all as I just wanted to make sure I have it all. The Birthrights and such was on Core.

![changeling1](https://user-images.githubusercontent.com/57871596/184523940-09c19fcd-d7d4-4d2d-a2c8-b3c4a035a010.png)

**Comment by JohanFalt** [comment]
The line is where the sheet's bottom is.

**Comment by Ringelpiez** [comment]
Is there an option for more columns?
House, Legacies (and Thresholds) are just one or two words each.
I'd take Kith Affinity to the Cantrips tab because it's only important for Cantrips.

**Comment by EldritchTranslator** [comment]
I would also put the House box at the bottom, since not all characters will have one, but all have Birthrights and so on. I agree with shifting Kith Affinity to the Cantrips tab.

**Comment by Ringelpiez** [comment]
> Also the characters will have only one Threshold, either a Ravaging or a Musing one
I would disagree on that. As I understand it, Changelings have both Courts/Legacies/Thresholds, with one always dominating (but that could theoretically change quickly and permanently).

Antithesis missing. But I would have to read that part again, because it was introduced with C20. 
(Does it actually come from Dark Ages Fae?)

**Comment by EldritchTranslator** [comment]
I agree that Changelings have both Courts and Legacies at once -my suggestion to take away the Seelie/Unseelie label on Legacies was to make the sheet compatible to those non-Kithain that don't have both, like Thallain, but was mostly a suggestion to save space. I don't think they have both Thresholds however, as they are unlinked from your Court: a Seelie could have a Ravaging Theshold and a Unseelie could have a Musing Threshold, but a character may have only one active at a time, so they would need only one in the sheet. (As per the Corebook, p.145: "_most [Changelings] find **one** form or style that calls to them more than others._")

**Comment by JohanFalt** [comment]
> Is there an option for more columns?
> House, Legacies (and Thresholds) are just one or two words each.
> I'd take Kith Affinity to the Cantrips tab because it's only important for Cantrips.

I could easily make two columns on the page. That should solve a lot I think.
But not the textboxes those should remain large.

Affinity I was thinking to have visible on both Core and with Cantrips which I was thinking to place under Dreaming.

**Comment by JohanFalt** [comment]
> I agree that Changelings have both Courts and Legacies at once -my suggestion to take away the Seelie/Unseelie label on Legacies was to make the sheet compatible to those non-Kithain that don't have both, like Thallain, but was mostly a suggestion to save space. I don't think they have both Thresholds however, as they are unlinked from your Court: a Seelie could have a Ravaging Theshold and a Unseelie could have a Musing Threshold, but a character may have only one active at a time, so they would need only one in the sheet. (As per the Corebook, p.145: "_most [Changelings] find **one** form or style that calls to them more than others._")

So one Legacy but as box then as you might need to add both?

**Comment by EldritchTranslator** [comment]
> So one Legacy but as box then as you might need to add both?
No, no, you do have both Legacies, I was meaning more of a... 

Legacies: [Box 1 here] [Box 2 here]

**Comment by JohanFalt** [comment]
This is not final in any way and would be viewed as the basic changeling sheet. Versions for other types of changeling I will solve in some way (most likely by using Type that then set what to show and so on).

But I think in essence it works. Graphics must of course be hammered more but as a vision of it, what say?

![changeling2](https://user-images.githubusercontent.com/57871596/184547791-e33bc7d0-6dd2-4984-a4bb-a3606b93d968.png)

![changeling_core](https://user-images.githubusercontent.com/57871596/184547793-88e26790-cee6-4137-b922-bae8dea135fa.png)

**Comment by JohanFalt** [comment]
Maybe Antithesis on Core as well?

**Comment by EldritchTranslator** [comment]
I suggest House below Antithesis since most characters don't have something to put there; Derangement should also be lowered. I agree with Antithesis on Core, below Frailty.

**Comment by JohanFalt** [comment]
Not 100% of the graphics on the core page but mainly set on things.

![image](https://user-images.githubusercontent.com/57871596/188065820-b3a8cc04-7ff3-4442-a449-9479a77f1512.png)

![image](https://user-images.githubusercontent.com/57871596/188065866-5c724249-121a-4ef3-b2cc-b2802628e7fa.png)

**Comment by Ringelpiez** [comment]
That already looks great. I'm looking forward to it when everything is finished. I'm already in the starting blocks for a few stories that I want to start with.
Johan, you make a dream come true, thank you so much.

**Comment by JohanFalt** [comment]
You who know the system... to cast a cantrip you add the number of dices you have in the Art itself, then add half the level of the lowest primary realm you are using.

So if you use Creeping Shadows from Autumn which you have 2 in and then use Actor (4) and Nature (2) you would roll 2 + 1 dices? The rating you need has nothing to do with this?

**Comment by EldritchTranslator** [comment]
No, you add all the dice, you don't halve anything.

**Comment by Ringelpiez** [comment]
Like EldritchTranslator said.

Suppose your Sidhe has Autumn 3, Actor 4 and Nature 2.
"Creeping Shadow" is level 1 Art and so it is included in Autumn 3.
"The Realm used determines who or what the character can scrutinize" so most likely the Realm would be Actor. Let's say a person whose name is known (Actor 2)
Then the pool for the cantrip is the sum of 3 (Autumn 3) plus 4 (Actor 4) - a total of 7d10.

**Comment by JohanFalt** [comment]
So when casting a cantrip, can you get bonus dices beyond what you have on the Art and then based on selected Real/Realms?

**Comment by Ringelpiez** [comment]
No.

Cantrip Dice Pool (C20 Core p.194):
Players roll a number of dice equal to their character’s Art rating plus the rating of the lowest primary Realm used (Fae,
Actor, Nature, Prop). The modifier Realms (Scene and Time) change the scope of the cantrip, but do not alter the number
of dice in the pool. (...)
The player must replace dice in her cantrip pool with a number of distinct dice (...) for the
roll equal to the character’s Nightmare rating. (...)

**Comment by Ringelpiez** [comment]
Unleashing an Art (C20 Core p. 196):
The player rolls a number of dice equal to the character’s Glamour rating plus a number of dice equal to her Nightmare
rating (...).

**Comment by JohanFalt** [comment]
So a checkmark if you are doing an Unleashing would be enough more or less?
It will keep track on the Nightmare dices - it will be fully visible which is which.

**Comment by Ringelpiez** [comment]
I don't know how you want to implement it. But if it's going to be something similar to WtA Gifts or Rites, then the simplest way would be an item with the maximum value of the associated Art and a drop-down menu for Realms (plus description etc...).
Then two options for rolling the dice:
1) Cantrip Casting (Art+Realm incl. Nightmare with a difficulty to be selected )
2) Unleashing (Glamour+Nightmare, difficulty 7).
With more effort, this could of course be further automated.

**Comment by JohanFalt** [comment]
I use the same method as with Vampire's disciplines. You have two types of power items - Arts and Art Powers. Arts are just what it sounds like the different arts themselves and the Art Powers and each power (1-5) within an Art. What you do is that you drag the Art to the sheet then you drag the Art Powers you have that are within the Art then you connect each Art Power with the Art. The end result is like follows:
![image](https://user-images.githubusercontent.com/57871596/189396566-97903aee-baf1-4214-a649-7901c69425e3.png)

As you click on the headline of the Art Power you get the following where you select which realms you are to use - and if you will Unleashed you check the checkbox for this.
![image](https://user-images.githubusercontent.com/57871596/189396664-248c8331-29e3-4e2d-89a1-2d670966b23e.png)

The roll looks like this with 2 Nightmare.
![image](https://user-images.githubusercontent.com/57871596/189397281-6115a1c8-efff-42bf-9adc-ce2e3194cd91.png)

**Comment by Ringelpiez** [comment]
That looks great.  :+1:
