### ISSUE TITLE
[CtD] Can't select both chimerical and wyld in art powers 

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#706]
Some Art powers have the possibility of being Chimerical or Wyld depending on the target. As it is rn it seems impossible to have that reflected on the art, I was wondering if that could be changed, esp since it doesn't seem to have a mechanical effect on the eventual roll.

**Comment by JohanFalt** [comment]
So essentially to set “both” and then as you use it you pick which?

should type be visible in the roll? Can’t remember if it does.

**Comment by EldritchTranslator** [comment]
In the rolled card atm it's not visible, it would be nice if that tag could appear somewhere. And yes, basically my idea is you select one or both, and when you roll you have to select the one you use between the ones you selected (so if it's just Chimerical it would just show chimerical, and if it's both you would have to pick)
