### ISSUE TITLE
1s don't take away successes from damage rolls.

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#709]
I noticed that 1s don't take away successed when rolled in a damage roll; I am not certain if it's the case in all splats, but in Mage at least that should not be the case, and it should behave normally. I do have the 'Use default result 1 handling' option in the settings ticked, and so far this is the only place it didn't work; if it works differently someplace else, maybe make this a toggle too in 'rolling dice rules'?

**Comment by JohanFalt** [comment]
I know that in Werewolf and Vampire 1s are not counted on damage and soak rolls, and as I read the rules of M20 they actually doesn't state that - they only refer to Rule of One on all rolls, so I'll make this an option in the settings.

**Comment by EldritchTranslator** [comment]
Yeah soak rolls work like that in mage too, as it's specified in the rules; for damage they modified it in Mage for... possible dice-pool related reasons?? Or something. I didn't really get it when my players explained that to me lol. But yeah that would be useful!
