### ISSUE TITLE
[MtA] Extended casting will always heighten the difficulty of the next roll in the casting by 1

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#711]
I am not certain if extended casting is meant to be used for some other mechanic, but personally I use in M20 for the optional rule of rituals, which are extended rolls. However, following this rule, the difficulty doesn't go up 1. when doing a number of rolls equal to your Stamina score 2. past that, when you pass the first Stamina roll to keep going on. After that, it will go up by 1 for each roll.
Maybe beside the 'extended roll' toggle you can put a 'keep base difficulty' toggle, so that this behaviour can be temporarily overridden?

**Comment by JohanFalt** [comment]
I would think to have the two options - extended casting and ritual casting so you can pick which to use.
