### ISSUE TITLE
Era setting doesn't change skill in Mage the Ascension

### ISSUE THREAD

**Issue by BokuNC** [JohanFalt/Foundry_WoD20#715]
**Have you tested without modules**

Yes, i tested in completely clean installation.

**Describe the bug**

**To Reproduce**
1. Go to 'A Mage Character Sheet Settings Tab'
2. Click on 'Victorian Age (20th)'
3. Return to the Core Tab

**Versions of software:**
- Version of Foundry VTT: V11 build 308
- Version of World of Darkness v20: 3.1.11

**Comment by JohanFalt** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/3437f602-9b3a-40e5-b5ea-b99cdbb5e1dd)

The Victorian sheet to the left, WoD20 Victorian sheet to the right.

**Comment by BokuNC** [comment]
> ![image](https://user-images.githubusercontent.com/57871596/267541082-3437f602-9b3a-40e5-b5ea-b99cdbb5e1dd.png)
> 
> The Victorian sheet to the left, WoD20 Victorian sheet to the right.

So, for some reason, Mr. Gone's Character Sheet for Victorian Age just changed the looks from the M20th base to the Victorian overall kit. 

But the character sheet on the book does change some things, as computers wouldn't be really present in a 1834-1901 Era (Unless i missed some update).

![Victorian Age Sheet p1](https://github.com/JohanFalt/Foundry_WoD20/assets/119072605/6c81da96-4539-4269-bb78-21e934574555)

![Victorian Age Sheet p2](https://github.com/JohanFalt/Foundry_WoD20/assets/119072605/82d09b06-57ad-49be-8e89-ff1204d17665)

**Comment by JohanFalt** [comment]
Present in v3.1.12
