### ISSUE TITLE
Mockery Breed Sheets

### ISSUE THREAD

**Issue by smorstinguy** [JohanFalt/Foundry_WoD20#722]
new sheets

**Comment by JohanFalt** [comment]
This will be a variant of the creature sheet most likely but I’ll see.

**Comment by JohanFalt** [comment]
**War Wolves**
Rage, Willpower
Power: Shapeshifting - Crinos

**Anurana**
Rage, Gnosis, Willpower
Power: Shapeshifting - Anuran, Shapeshifting - Dagon

**Samsa**
Rage, Gnosis, Willpower
Power: Shapeshifting - Ungeziefer
Gifts

**Kerasi**
Rage, Gnosis, Willpower
Power: Shapeshifting - Bandia, Shapeshifting - Kiforu, Shapeshifting -Faru

**Yeren**
Rage, Gnosis, Willpower
Power: Shapeshifting - Crinos
Gifts
