### ISSUE TITLE
Custom Advantages/Powers and/or Orpheus Support

### ISSUE THREAD

**Issue by SophieScott12** [JohanFalt/Foundry_WoD20#723]
The system as written now allows for customizing sheets for a number of splats, which is great, but doesn't have any kind of support for Orpheus, which is a shame.  Adding native Orpheus support would be great, or short of that, one could allow for adding custom Advantages to the sheet much like the custom secondary abilities.  The latter would also allow for homebrew games based on the WoD storyteller system.

**Comment by JohanFalt** [comment]
I don’t have Orpheus which will be a problem. But I’ll add it to the list.
