### ISSUE TITLE
Customizing Compendiums background images

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#725]
I had problems with my PC, and I have recently caught up with version 11. I have seen the update of the background images for the compendiums types (scenes, objects, actors...)

I'm working with exhaustive compendiums: Powers, Merits/Flaws, Backgrounds, magical objects (like Fetish, Artifacts, Relics, talens...)
And there's a [Custom Compendium Banners module](https://foundryvtt.com/packages/custom-compendium-banners) that allow to change the default image for each type of document. 
Is there a way in which we could customize the background, or maybe add just some different images for **different objects (Feature, Trait...)** in the system core? It would be great if we could change the background between objects: I have a LOT of compendiums with the same image: Common Backgrounds, Changeling-specific Backgrounds, Physical common Merits, Mental common Merits, Werewolves Merits, Vampire Flaws, Blood Magic Rituals, Garou Rituals, Disciplines, Arts... and so, all of them with the same pic. Is confusing :S

I assume not, but...

**Comment by JohanFalt** [comment]
Think all you need to do is to link somewhere outside the system folder or a folder named icons then the image is changed. But then you need to change the image for each item you wish to do this for.

**Comment by JohanFalt** [comment]
Personally I use folders and https://github.com/prolice/auto-color-folder/
