### ISSUE TITLE
"Secret" format don't work

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#727]
Create an object (Power, Gift) and set a line in description or system as 'Custom > Secret' don't work. The save button wipe it. 
I just wanted to add some commentary like "in this book, the roll use this Skill, in this other, this other one". Guess it will have to go as quote.

**Comment by JohanFalt** [comment]
O'm not sure what you are trying to do.

**Comment by Kad-Caiel** [comment]
Gift window
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/f5126a2b-d308-4098-8fd8-be18cc85a9d5)

I add some line at the end and set it as Secret.
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/1ed5e153-fc27-4d70-9cd8-89d03eedfcf9)

Click in save
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/551bf511-66d7-4986-8890-7b2316fb3462)

And... a dog ate it!
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/752e90b4-e491-477f-9f66-2d425cd98bd8)

**Comment by JohanFalt** [comment]
Apparently only on items. Making investigations.

**Comment by JohanFalt** [comment]
This seems to be some kind or Foundry problem which I haven’t gotten a clear answer why it is reacting like this. Hopefully it will be fixed in Foundry in the future.
