### ISSUE TITLE
Wheel of Destiny causing problems

### ISSUE THREAD

**Issue by LordOnyx4242** [JohanFalt/Foundry_WoD20#737]
Most character sheets won't open after the update thought a few like mortal sheets will, though not all of them

**Comment by JohanFalt** [comment]
Please try v3.2.2

**Comment by LordOnyx4242** [comment]
well it doesn't seem to have worked even rolled it back to before and then applied the 3.2.2 and it didn't work.  New sheets are fine but most of my existing npcs and sheets are not opening including werewolf ones.  The info in the sheets is intact it at least looks like

**Comment by jacksands** [comment]
Same here.
For me it was working with 3.2.1, but couldn't create new sheets...
Reversing back from 322 -> 321 and also the world in the backup for 321 strangely do not solve it, all werewolf, changeling and vampires sheets do not open.

reversing all the way to 3.1.12 and a backup from there was ok...

foundry  v11.313

and always, thank you!!!  amazing work on the system!  this kind of bugs are expected for a immensely complex system!

**Comment by JohanFalt** [comment]
With 3.2.2, please press F12 and and take a screen picture of the error message as you open the actor.

**Comment by JohanFalt** [comment]
Please test with v3.2.3

**Comment by jacksands** [comment]
No longer characters are blocked.  but testing creating a new character caused 2 sheet type windows to open... (for changeling and changing breed, all others are ok)

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/3428ee4f-9178-47b6-b91a-e763f4f4c0bb)


console print  
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/63d9a6f1-1ce9-446b-b627-11fc2d1ec407)

actor expanded 
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/1f54906d-65de-440b-9a46-8c313c435cca)

**Comment by jacksands** [comment]
Just noticed....

Changeling Art Power, do not find Art option when creating then

And those that I had working before had lost they art option...?


on the character sheet they still works fine

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/a409ce6d-fb08-4a44-ba5c-0d6025d5279f)

**Comment by JohanFalt** [comment]
If you restart Froundry? The reason is that that list is only read as Foundry starts.

**Comment by JohanFalt** [comment]
> v3.2.3
> 
> No longer characters are blocked. but testing creating a new character caused 2 sheet type windows to open... (for changeling and changing breed, all others are ok)
> 
> ![image](https://user-images.githubusercontent.com/7229143/274940904-3428ee4f-9178-47b6-b91a-e763f4f4c0bb.png)
> 
> console print ![image](https://user-images.githubusercontent.com/7229143/274941933-63d9a6f1-1ce9-446b-b627-11fc2d1ec407.png)
> 
> actor expanded ![image](https://user-images.githubusercontent.com/7229143/274942064-1f54906d-65de-440b-9a46-8c313c435cca.png)

Found this,

**Comment by jacksands** [comment]
Sorry...    found this...

I haven't notice that a single module was still active during testing, and deactivating it solved the issue...

Reactivating all modules minus this one also no issues

activating it cause problems again...
module:
Wheel of Destiny

https://foundryvtt.com/packages/wheel-of-destiny

It's a shame, I really like it... kkkk

sorry the false flag


> Just noticed....
> 
> Changeling Art Power, do not find Art option when creating then
> 
> And those that I had working before had lost they art option...?
> 
> on the character sheet they still works fine
> 
> ![image](https://user-images.githubusercontent.com/7229143/274946500-a409ce6d-fb08-4a44-ba5c-0d6025d5279f.png)

**Comment by JohanFalt** [comment]
Perfect I’ll see what the problem are.

**Comment by jacksands** [comment]
Many many Tks!!!!
