### ISSUE TITLE
Adding a new item locks character sheets inaccessible

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#739]
**Have you tested without modules**

**Describe the bug**
When you add a new item of any type (be it weapon, armor, power, etc.) it doesn't add anything, but when you close the sheet, it's no longer accessible

**To Reproduce**
1. Open any sheet
2. Add any item, there is no reaction
3. Close the sheet
4. Try to reopen
**Versions of software:**
- Version of Foundry VTT 11.307
- Version of World of Darkness v20 3.22

**Comment by JohanFalt** [comment]
Can you press on F12 and take a screen picuture of the error text that appear as you try to open the actor.

**Comment by JohanFalt** [comment]
Please test with v3.2.3

**Comment by TheFokin** [comment]
It now works, but behaves in a weird fashion.
For some existing characters, it seemingly duplicates items, but the duplicates disappear when I lock or unlock the sheet.
1. The sheet is locked. Character has one ranged weapon on her
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/02142be7-c0be-4845-875c-95113ea7cf8e)
2. After pressing "Add weapon" it adds one, but both the new and the old one are doubled.
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/e1578f96-dcd6-4446-a323-d20f4a780b6d)
3. Unlocking the sheet removes the duplicates.
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/e07d3c12-b807-4b7a-83e2-cc6ff15778c3)
4. When I remove the new weapon, it doubles the old one
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/3e1a1b52-34dc-4eb8-9c28-1d684798e6b3)
5. When I lock the sheet again, the duplicate disappears.
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/e1f08182-2502-410f-a754-bf9b4e87ce98)

**Comment by JohanFalt** [comment]
What sheet are you using?

**Comment by TheFokin** [comment]
This is a mortal character.
No red messages in the console.

**Comment by TheFokin** [comment]
Weirdly enough, when I export the json and import it into another character, it works fine.

**Comment by JohanFalt** [comment]
Restarting foundry?

**Comment by JohanFalt** [comment]
Can you export the character and post here?

**Comment by TheFokin** [comment]
[fvtt-Actor-lidiya-eduardovna-deber-0tEnYL4MptqyjzBR.json](https://github.com/JohanFalt/Foundry_WoD20/files/12894517/fvtt-Actor-lidiya-eduardovna-deber-0tEnYL4MptqyjzBR.json)
Here. But it will probably work just fine.

**Comment by JohanFalt** [comment]
Yes it does as it only contains one weapon.

Could you open the sheet. Press F12 and check the listdata property Combat as I show below. What does that show?

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/3945d42e-1a20-424c-840c-45a97c8ac391)

**Comment by TheFokin** [comment]
Can't find this menu. How do I access it?

**Comment by TheFokin** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/9a9ac52d-4ccc-4449-8cc6-ac81fc0f1e3f)
I've pressed "Add Melee Weapon" button once
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/b998c86d-50bc-4d0d-affa-9c45c14ad055)

**Comment by JohanFalt** [comment]
Can you unfold Id for those two. I'm interested to see if they have the same Id or different.

**Comment by TheFokin** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/9efd18c5-c1b3-4780-aa1e-6014e15a841d)
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/41635428/3843904a-b84f-4832-861f-70ee32038a72)
IDs are the same.
