### ISSUE TITLE
Migration from spirit to creature sheet

### ISSUE THREAD

**Issue by jacksands** [JohanFalt/Foundry_WoD20#742]
**Is your feature request related to a problem? Please describe.**

considering that the spirit sheet is no longer supported, please, would be possible to change the sheet default type to migrate, instead of recreating then by hand...  I have a few dozens of spirit sheets.... 

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/9b957549-7214-47bb-87b3-35c52eab0aa9)

like in here

In any case, just a suggestion, great work!

question... will you venture into Werewolf W5?

**Comment by JohanFalt** [comment]
I'll see what I can do.

**Comment by JohanFalt** [comment]
As for W5 I'm not planning too. But is keeping an eye out for the future.

**Comment by JohanFalt** [comment]
A migration function from Spirit to Creature will be present in v3.2.6.

If will be a button present on the Spirit sheet where it will create a new actor as creature. Tokens are not effected.

**Comment by jacksands** [comment]
thank you very, very much!!!
