### ISSUE TITLE
Discipline power in Compendium losing attached Discipline

### ISSUE THREAD

**Issue by Cougy-6185** [JohanFalt/Foundry_WoD20#745]
**Have you tested without modules**
Yes.

**Describe the bug**
When creating Discipline Power, you can only choose the Discipline attached to it if the Discipline Item is on your world at the start of the World. When creating Compendium of Items and storing the Discipline Power Item the Discipline attached to it remains ONLY if the discipline is still in your world.
Creating Compendium of Discipline and Discipline Power is useful to NOT have everything in your World. But then when importing the Item stored in the Compendium, the link Discipline <-> Discipline Power is lost.

**To Reproduce**
1. Create the Discipline.
2. Create a Discipline Power attached to the previous Discipline.
3. Create a Compendium.
4. Store both Items in the Compendium.
5. Delete both Items in your World.
6. Reload the World.
7. Open the Compendium.
8. Import the Discipline Power.

**Screenshots**
Not necessary.

**Versions of software:**
- Version of Foundry VTT V11 313
- Version of World of Darkness v20 3.2.3

**Comment by JohanFalt** [comment]
The way Foundry handles items in items this can’t be fixed.
