### ISSUE TITLE
Changing a type of a Mortal doesn't activate Powers tab

### ISSUE THREAD

**Issue by TheFokin** [JohanFalt/Foundry_WoD20#747]
**Have you tested without modules**
Yes

**Describe the bug**
When you assign a type to a Mortal character, either a new or existing one, it doesn't automatically activate a corresponding Power tabe

**To Reproduce**
1. Open a Mortal character sheet\Settings\Sheet Setting or alternatively create a New Mortal character
2. Assign "Ghoul" subtype

**Versions of software:**
- Version of Foundry VTT 11.307
- Version of World of Darkness v20 3.2.4

**Comment by JohanFalt** [comment]
For now (until fixed) you need to activate it manually under Setting -> Power on the sheet.

**Comment by TheFokin** [comment]
Yeah, I know that. But thanks.
Keep up the good work!

**Comment by JohanFalt** [comment]
3.2.5 fixes this in my tests at least.
