### ISSUE TITLE
Weapons, The Bow, Cant use archery as secondary skill when making it.

### ISSUE THREAD

**Issue by mnwolfboy** [JohanFalt/Foundry_WoD20#752]
So a character we have has a bow but when making the item the options are athletics and firearms, Does not let me use archery.

**Comment by JohanFalt** [comment]
As I understand you.

You create Bow, then as you are to pick ability you expect Archery to be selected right?

Not quite, what you do is set it to Custom. Then as you use it the first time you select what secondary ability to use. 

Reason is that the weapon checks what Secondary Abilities exists on the actor and let you pick from them as the ability can really be anything.
