### ISSUE TITLE
Better fit for Dialog windows size.

### ISSUE THREAD

**Issue by jacksands** [JohanFalt/Foundry_WoD20#757]
**Is your feature request related to a problem? Please describe.**

The system dialog window does not open showing all the content, you need to expand it using the arrow.

**Describe the solution you'd like**
To open showing all content, with the arrow allowing you to change if desired.

**Additional context**
in css I used "   min-height: 700px !important;   " and it looks better, but it prevents you from changing it to less...

can this be made?  I tried  fit-content   but no luck...

in any case it is just QoL...  Your system is utterly impressive!  congratulations!!!!

![WhatsApp Image 2023-10-21 at 09 41 53_181a02cf](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/47aef257-9b5e-47d2-ba18-d7137b395d7d)

**Comment by JohanFalt** [comment]
I think I caught all that was causing problem.
