### ISSUE TITLE
Suggestion of change: Update Demon to 20th

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#758]
As long as the system is called WoD 20th anniversary, it would be great to update the Demon primary Abilities to the 20th official ones.

![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/bd3bd5e2-0bda-4385-9fda-c9fb11551cd3)

Source: some minor supplements edited by WW, in the storyteller vault.
For example: https://www.storytellersvault.com/product/271257/Infernal-Might-Common-Lore

**Comment by JohanFalt** [comment]
Hmmm I actually have that one. Think I'll make this a setting.

**Comment by Kad-Caiel** [comment]
After speak with the writer, it's only fan material, but appears as published by WW, which may lead to confusion. There's no official abilites set (although removing Demolitions for Demons is a positive point... there's no sense in any game but Hunter, so I would keep doing it). Maybe is meta-canonical.
Your choice.

**Comment by JohanFalt** [comment]
My thought is to have both.
