### ISSUE TITLE
Change or add a toggle for Changeling font

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#766]
Kells, Changeling's font, is a very pretty font, but unfortunately it doesn't support accented letters such as à and è, which are both very common and present in the italian translation for the sheet. May I suggest to switch it to the equally Changeling MeathFLF, which has a similar style but a better letter range? It can be found in the STV Changeling style packs.

![immagine](https://github.com/JohanFalt/Foundry_WoD20/assets/56313572/cc5266be-4c97-4d7e-91f9-41d11aaf6528)
 Pictured: MeathFLF normal, then bolded, then Kells

**Comment by JohanFalt** [comment]
I'll make the font language specific. Kells came through the Spanish translation so I make Kells the default one there and MeathFLF for the rest especially if MeathFLF holds more characters.

**Comment by JohanFalt** [comment]
After checking MeathFLF was SO much better making it the standard font.
