### ISSUE TITLE
[Mage] Alternative to Paradox wheel

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#767]
While all my players find it really cool looking, after 20 sessions it became clear that most of them struggle adding paradox/quint to it via clicks. I also find it fiddly, even if manageable. I was wondering if it was feasible for some other solution to be present, maybe a couple dropdowns for the amount of quint and paradox, or something? They could be put under the wheel, so they wouldn't bother the layout of the rest of the sheet, I think.

**Comment by JohanFalt** [comment]
I'll ponder how to make something up on this. Will try to get it out in present version but it might be pushed ahead to v4 if it gets complicated.

**Comment by JohanFalt** [comment]
Something like this?

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/60d0f4b5-7c21-4dbf-8550-b0cf9cbcc099)

**Comment by EldritchTranslator** [comment]
Polled to my players, it's a resounding yes, that would be excellent
