### ISSUE TITLE
Visual bug & paradox bug

### ISSUE THREAD

**Issue by EldritchTranslator** [JohanFalt/Foundry_WoD20#769]
In the latest version (3.2.11) I can't add more Paradox than half the wheel. The Quint works fine. The visual bug is that the arrow to lower Quint goes on a second line, probably because 'Quintessenza' is too long a name? 
![](https://i.imgur.com/Hjpgjwk.png)
Widening the sheet does not help.

**Comment by JohanFalt** [comment]
Will fix tomorrow.

**Comment by JohanFalt** [comment]
In the Foundry Core settings what are your:

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/f821361e-f205-41c7-8c3c-88b19fb7bc65)

**Comment by JohanFalt** [comment]
I'm a bit unsure about the graphical problem as I can only reproduce it in Spanish but try v3.2.12 and see what you get.

The paradox problem was an easy fix.

**Comment by EldritchTranslator** [comment]
Both fixed!
