### ISSUE TITLE
mummy the resurrection character sheet

### ISSUE THREAD

**Issue by Dudaeel** [JohanFalt/Foundry_WoD20#770]
It would be cool if it was possible to add the game, Mummy the Resurrection.

**Comment by JohanFalt** [comment]
Its in the plans check issue:

https://github.com/JohanFalt/Foundry_WoD20/issues/140

Most likely it will be part of the next great release which is planned for Foundry v12. Depending on how much work Foundry v12 is will decide if Mummy will be made in that version of the one after that.
