### ISSUE TITLE
Maximum net difficulty change for Arete rolls in Mage

### ISSUE THREAD

**Issue by logarium** [JohanFalt/Foundry_WoD20#771]
Under M:tA rules, the maximum net change in difficulty for Arete rolls is +3 to -3. 
Under the current version (3.2.12), there doesn't appear to be a limit on this - I am able to move the Arete difficulty more than 3 points higher and lower from its starting difficulty (which should be based on whether the Effect is coincidental, vulgar, or vulgar with witnesses).
Is it possible for you to address this, so that the final difficulty can't be moved more than 3 points in either direction?

This rule crops up in  a few other places as well. For example,, you can use Effects to increase or lower the difficulty of Ability rolls, but never more than 3 points overall. But I think that might be less important than making the Arete difficulty accurate.

Thank you for your outstanding work. You have saved my Mage chronicle, by the way.

**Comment by JohanFalt** [comment]
Hmmm this is a bug. As it should have been built (if it had worked) is that the limit is max -3 on normal difficult, so if your casting diff is 5 and then you add +2 because - penalties - then you can use up to -5 diff in quint. for instance.

Or am I wrong about this?

**Comment by logarium** [comment]
Hey, yeah, that's how it should work. Whatever your starting difficulty,
you can't end up more than +3 or -3 in either direction. You can have
penalties and bonuses stacking and cancelling each other out, so long as
the final result remains within that 3-point boundary either side of the
initial difficulty. So in your example, yes, you could spend 5 quint to
bring it back down but anything more would be wasted.
