### ISSUE TITLE
Gear tab improvements

### ISSUE THREAD

**Issue by Laczi11** [JohanFalt/Foundry_WoD20#774]
The gear tab is a bit too compact if you want to make a good looking inventory. Could we have a resizeable textbox? 
Also, the money has the "carried" value listed on both the "carried" and "in bank" side, i do not know if that's how it should be, i thought they'd show the separate values.

**Comment by JohanFalt** [comment]
Fist part will look into that.

The second:
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/47a5dbc6-9e26-471d-8509-e1e2b73b4866)

What version are you using?

**Comment by Laczi11** [comment]
I use the 3.2.12 version of the module. I see the problem in the Vampire character sheets, in the Dark Ages version.
Here it is in edit mode, in a correct state:
![Edit mode](https://github.com/JohanFalt/Foundry_WoD20/assets/32680704/79e5a9c3-b72d-4858-9b35-039d0caf80e0)
Here what we see outside of edit mode:
![Non-edit mode](https://github.com/JohanFalt/Foundry_WoD20/assets/32680704/9cb2f107-168a-4b88-be9a-b6c2bbe2d57a)
