### ISSUE TITLE
[Request]Want to add Chinese support to the system

### ISSUE THREAD

**Issue by aimili1** [JohanFalt/Foundry_WoD20#775]
I want to add Chinese support to the system How do I get started?

**Comment by JohanFalt** [comment]
Started to check Foundry setting before answering. It seems Foundry has different support for this. I assume the translation you are asking for is "cn"?

What you do is checking in your installation of WoD20 take a copy of en.json which is placed in the folder worldofdarkness\lang. The  you rename this to cn.json and open it in a normal texteditor like notepad and start translate the phrases that exists. There are quite many.

**Comment by JohanFalt** [comment]
Once that is done you send that file back to me and I incorporate it with the system.
