### ISSUE TITLE
[Suggestion/Request] Highlight Evocation dices according to Torment

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#776]
Regarding this mechanic: _...if the majority of successes are equal to or less than Torment, the pain perverts your efforts and the tormented effect occurs_
It would be great to have a way to highlight or emphasize the Evocations dices whose result is lower than Torment, to control the effect of the Lores, whether normal or tormented. Or maybe even a calculation that shows you, below the success counter, for example.
Perhaps a red outline on the dice icon (which could also be used in green for 10's with an active specialisation or double success configuration, in any "game").

**Comment by JohanFalt** [comment]
I won't add this as it complicates the roll function quite a lot.
