### ISSUE TITLE
[Request] Allow skill specialties earlier than rank 4.

### ISSUE THREAD

**Issue by oneeyedirishman** [JohanFalt/Foundry_WoD20#777]
At present, you cannot add a specialty to skills that have fewer than 4 dots in them. Certain skills however, such as linguistics and crafts, are designed to have specialties which are represented by the number of dots beginning from the very first rank. Being able to customize specialties without the restriction of rank 4 would make these skills much easier to manage.

**Comment by JohanFalt** [comment]
Rule reminder for self:

p100 V20
For certain Abilities (_Expression, Crafts, Performance, Academics, Law, Science, and Technology_), it is best to pick a specialty (p. 96), even if the character’s rating in the Ability is not yet 4 or higher.

**Comment by Kad-Caiel** [comment]
In case it helps:
**V20**: Expression, Crafts, Performance, Academics, Law, Science, Technology.
**V20DA**: Crafts, Commerce, Performance, Academics.
**W20**: Expression, Crafts, Academics, Science, Technology.
**M20**: Crafts. _Optionally: Art, Athletics, Fireams, Martial Arts, Melee, Academics, Esoterica, Lore, Politics, Science._
**C20**: Crafts, Performance.
**Wr20**: None, apparently.

**Comment by JohanFalt** [comment]
Commerce does not fall within this rule:

"Choose a field of expertise when taking Commerce. Outside that field, treat the Ability as if it had no dots. Additional fields can be purchased with one experience point."
