### ISSUE TITLE
Bug? - Wyld / Wyrd

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#784]
In the line 971 of lang files, we can found 'Wyld'.
Wyld is a Werewolf term: Wyld, Wyrm and Weaver (in spanish, Wyld is Kaos)
But in the Changeling sheet, in spanish, there're 'Quimérico' (Chimerical) and Kaos, both Art types.
Should be Chimerical and Wyrd, not Wyld. I haven't found 'Wyrd' in the lang file.

**Comment by JohanFalt** [comment]
wod.power.wyld -> e.g dialog-power
