### ISSUE TITLE
Blood points for Anansi charcter sheet

### ISSUE THREAD

**Issue by VinnerZeroX** [JohanFalt/Foundry_WoD20#794]
need to add the ability to change the number of blood points for the Anansi character sheet

**Comment by JohanFalt** [comment]
I thought that was a fixed thing, but ok will open up the possibility.

**Comment by VinnerZeroX** [comment]
I don't know why but it still doesn't work
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/156355002/eb69e915-7add-4c64-bcae-64acdb4e02ed)

**Comment by JohanFalt** [comment]
It's part of v4.0 so it is not out yet.
