### ISSUE TITLE
[Feature Request] Support for Combination Disciplines in V20

### ISSUE THREAD

**Issue by tevwoods** [JohanFalt/Foundry_WoD20#799]
Currently when creating a Discipline Power in vampire, you must select a single discipline the power belongs to. V20 has the notion of Combination Disciplines or Combination Powers, which are powers that require a particular level in 2 or more Disciplines, and exist outside of the normal "dot/level" notion for a single discipline. 

It would be great if you could designate a power as a Combination Discipline and indicate which Disciplines and levels are required to take it, instead of indicating the "level" of the power. These powers could either be displayed in all of the disciplines that they require, e.g. if a Combination Power requires Fortitude 1 and Presence 4, like Rescue Beacon it would show under both the Fortitude and Presence Disciplines, or a completely separate Discipline entry could be created with a name like "Fortitude/Presence" and it would be listed there (along with any other combination powers that required both Fortitude and Presence).

Additionally these powers are unique in that they carry a specific experience point cost. It would be nice if there was a place to put that cost as well.

**Comment by JohanFalt** [comment]
Will be available in coming version
