### ISSUE TITLE
[Feature Request] Some Mage Actor Sheet UI Improvements

### ISSUE THREAD

**Issue by Grandsome** [JohanFalt/Foundry_WoD20#800]
Edited the Request to compile a few UI improvements, since those problems are in the same section of the Actor Sheet.

- **Add Descriptions field to MtA Resonance and the Ability to Roll Them:**
Given that the effect of Resonance can be complex as well as their origin, a description field with a tooltip for players to read would be very useful.
And the ability to roll their dots would be neat too.

- **Implement a Resonance Item:** So the GM doesn't have to copy and paste between actor sheets with the same resonance.

- **Ability to change the difficulty of a Rotes roll by using the big purple difficulty buttons in the difficulty box of the roll window.**

- **Change the order of the double column display of the Rotes section**:
Currently, Rotes are ordered in the double column display from left to right in a Z pattern, standard double column text is usually read in a flipped N pattern (I/I) where you read each line of one column before starting the next. Maybe there could be a toggle between the two-way in the sheet settings.

So instead of:
1 || 2
3 || 4
we have:
1 || 3
2 || 4

- **Increase Line Height in the Rotes section to allow for the display of long Rotes names when they overflow a line:**
When a Rote's name is too long before shortening it with "..." allow for the name to occupy two line height of the column (this would also double the line height of the second column, but that's not a big deal.) so more of the Rote's name can be displayed before being shortening.

So a line in the rote section would go from:

1 "long rote name stri" + "..." || 2 "short rote name string"

To look like this:

1 "long rote name "  || 2 "short rote name string"
"string" + "..."_______||

thanks.

**Comment by JohanFalt** [comment]
- [ ] Add Descriptions field to MtA Resonance and the Ability to Roll Them
- [x] Implement a Resonance Item (already exist as it is a Trait item)
- [ ] Ability to change the difficulty of a Rotes roll by using the big purple difficulty buttons in the difficulty box of the roll window
- [ ] Change the order of the double column display of the Rotes section
- [ ] Increase Line Height in the Rotes section to allow for the display of long Rotes names when they overflow a line

**Comment by JohanFalt** [comment]
"Ability to change the difficulty of a Rotes roll by using the big purple difficulty buttons in the difficulty box of the roll window"

For now you can change this by edit the value in the difficulty modifier box. Move the feature for future estimation.

**Comment by JohanFalt** [comment]
"Change the order of the double column display of the Rotes section"

Will see how I'll fix this as it would require alterations on the main design of the sheet.
