### ISSUE TITLE
Changeling the Dreaming 20th Anniversary - Cantrip Types:  "Wyld" should be "Wyrd"

### ISSUE THREAD

**Issue by ovidianskin** [JohanFalt/Foundry_WoD20#802]
**Have you tested without modules**
n/a, since the module is WoD20th 
**Describe the bug**

While creating the Arts as Foundry Items, I noticed there was a field to choose the Cantrip type--options are Chimerical, Wyld, or Both.  Wyld should be Wyrd.  It's a typo, nothing more.  

**To Reproduce**
While creating the "sub" powers of each Art, look at the Art Type drop down field.  

**Screenshots**
![Screenshot 2024-02-03 173333](https://github.com/JohanFalt/Foundry_WoD20/assets/139589414/9711547d-6b4a-4e80-bd32-91b71a76fdbb)

**Versions of software:**
- FoundryVTT V11 Stable, Build 315
- WoD 20th Anniversary 3.2.14

**Comment by ovidianskin** [comment]
Not sure if this is actually a bug, probably should have been a feature request : P

**Comment by JohanFalt** [comment]
This has been fixed in the coming version.
