### ISSUE TITLE
Character sheet bug Vampire Splat.

### ISSUE THREAD

**Issue by miker177** [JohanFalt/Foundry_WoD20#806]
**Have you tested without modules**
Yes
**Describe the bug**
The character sheet somewhat breaks if you select Generation 5 and 4. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the character sheet.
2. Click on generation select 5.
3. Go to Core. 

**Screenshots**
Generation 5
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/107895781/da2af9dd-fc10-4476-ae7e-83b252901e15)

Generation 6 comparison
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/107895781/1d44b4db-9ab0-4b11-9e91-046925787225)

**Versions of software:**
- Version of Foundry VTT 11 Stable, Version 315
- Version of World of Darkness v20 - 3.2.14

**Comment by JohanFalt** [comment]
No that is actually by design so you still can keep the circles as notifications.
