### ISSUE TITLE
Cannot change max value on attributes

### ISSUE THREAD

**Issue by Lapiccelle** [JohanFalt/Foundry_WoD20#810]
**Have you tested without modules**
Yes, i have

**Describe the bug**
Cannot raise max values on a sheet, everytime i change the number it goes back, from whatever it was, to 5 and doesn't change, at least on a vampire sheet

**To Reproduce**
1. Go to 'Settings'
2. Click on 'max value and change it in a vampire sheet"

**Versions of software:**
- 11 (Foundry) 
- 3.2.16 (Wod 20)

**Comment by JohanFalt** [comment]
On the vampire sheet that is by design as the max-value of attributes and abilities are tied to generation.

**Comment by Lapiccelle** [comment]
> On the vampire sheet that is by design as the max-value of attributes and abilities are tied to generation.

Oh, i see, but it would be nice to be able to change that, since some boons can surpass the atribute max without generation (like golconda)

**Comment by JohanFalt** [comment]
Suggest to use an Other Trait and then set a bonus to it that adds what you need.
