### ISSUE TITLE
re-add running totals to experience headings

### ISSUE THREAD

**Issue by R0gu3P403n1x** [JohanFalt/Foundry_WoD20#814]
In the Notes tab, the Headings for Earned Experience and Spent Experience used to show totals from those headings.  Having this information was EXTREMELY useful for bookkeeping, both as a player and as a Storyteller (GM).  The current total on the main page is great, it lets you know if you have any to spend, but knowing how much a character has spent or has gained is also very important.  If it is not too much trouble to add this feature back in, it would be greatly appreciated.

Phoenix

**Comment by JohanFalt** [comment]
A bug.

**Comment by JohanFalt** [comment]
You mean these:

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/2ef3da52-df64-4d34-b057-dc143b4095f6)

Or these:

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/4746c0c8-c6ff-4499-958a-8d0ef285cab0)

**Comment by R0gu3P403n1x** [comment]
The first image is the ones that are missing.

**Comment by JohanFalt** [comment]
On what sheet because I can't recreate this problem?

**Comment by R0gu3P403n1x** [comment]
Vampire sheet, just the basic one.

**Comment by R0gu3P403n1x** [comment]
The totals ARE on Werewolf sheets, just confirmed.  It appears it is just
Vampire.
