### ISSUE TITLE
A little thing to do: Add the two options of Demon editions for Abilities in lang files

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#817]
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/efdc5b98-374c-489d-9855-74ac65dbdab1)
This list doesn't appear in the lang files.

**Comment by JohanFalt** [comment]
No it is the same list as the others. They are already translated.

**Comment by Kad-Caiel** [comment]
I have the program and the system in spanish, there is no entry in the lang file that I am translating, and I still see it in english :S
