### ISSUE TITLE
[Sugestion] Increase font size for combat tab, in Hunter sheet

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#820]
Can you increase the special/themed font size one or two points? It is too small.
Or is a standard value, same in every sheet?

![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/64123b95-0c4d-4f1b-bf93-ec0b4890ce15)

**Comment by Kad-Caiel** [comment]
In Garou/Fera too
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/9abaf9e7-7cea-41c2-8c41-77b08fac6c1b)

**Comment by jacksands** [comment]
suggestion, foundry has that option in the case settings, but it is not very good... it will not apply correctly to all css styles....
![309076210-0f1e73a7-4d35-4173-8431-5c392766b13b](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/d658afa2-58b2-4a5d-91b8-c14ea3b72eb9)

but the zoom in/out in the browser level is very good at that... yes, it will change more than the fonts...  but is a temporary solution...
![309075979-f974432c-efd9-4d1a-b86c-08631a185c45](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/777940be-82f3-45e0-805f-f9644badd3cf)

**Comment by JohanFalt** [comment]
Fixed in 3.3.0
