### ISSUE TITLE
[Bug] Unable to Render Character Sheet

### ISSUE THREAD

**Issue by Grandsome** [JohanFalt/Foundry_WoD20#824]
**Have you tested without modules**
Yes.

**Describe the bug**
Clicking on token or in the character menu, character sheets cannot be loaded/rendered. Happens even when all modules are off, using Find the Culprit.

**To Reproduce**
New characters are also affected by the bug.

**Screenshots**
3.3.0
![Capture d’écran 2024-03-18 005305](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/6b748ac6-0b20-4187-8da1-46c22b7d06fa)
![Capture d’écran 2024-03-18 005401](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/8a7a7c3f-e344-485c-b8e5-c1f4738bd34d)
![Capture d’écran 2024-03-18 005322](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/8e5f54b7-39a1-4eee-9c8f-8fd2614f952f)
3.3.1
![Capture d’écran 2024-03-19 173829](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/bb5fcd21-d507-42c8-bf27-89ae2b6770a5)
![Capture d’écran 2024-03-19 173838](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/61710608-11c2-469c-b340-93e0e2742a99)
![Capture d’écran 2024-03-19 173850](https://github.com/JohanFalt/Foundry_WoD20/assets/32459440/c35854c4-bdf8-4061-a7c2-b30d6e42dcdd)

**Versions of software:**
- Version of Foundry VTT: 11 315
- Version of World of Darkness v20: 3.3.0 and 3.3.1

**Comment by JohanFalt** [comment]
I can reproduce this. Would need access to your world for further investigation, player access should be enough and access to one of the actors that are a problem.

**Send access through Discord**.

**Comment by Grandsome** [comment]
Problem came from reverse-proxy Cloudflare delivery, fixed with a cache purge.
