### ISSUE TITLE
German translation not consistent with official German rule book

### ISSUE THREAD

**Issue by grafnull** [JohanFalt/Foundry_WoD20#830]
The German translations of some abilities does not match the official German rule book
For example "expression" is translated as "Überzeugen" but in the rule book it is "Ausdruck"
This is causes confusion when looking things up in the rules and also "Überzeugen" and "Ausdruck" are not synonyms in German.

This is just one example, there are couple more translations of abilities that are slightly off.
In the past I edited the de.json, but it is overridden with every update.

I could provide a de.json with the official translations.
![v20](https://github.com/JohanFalt/Foundry_WoD20/assets/64161192/d2461c74-d4ea-49c7-8e0b-f03b07a2706a)![v20-2](https://github.com/JohanFalt/Foundry_WoD20/assets/64161192/a6609aef-f583-49dc-84bb-9835f6ec119c)

**Comment by JohanFalt** [comment]
Please do

**Comment by grafnull** [comment]
Attached my de.json file. I updated the sections _attributes_, _abilities_, _health_ to match the translations in the official Vampire the Masquerade 20th Edition German rulebook.
The translation are not necessarily _better_, but they match the official translations, which makes it easier to find in the book.
I only have the Vampire Rulebook, the translations in other World of Darkness rulebooks might be different. 

[de.json](https://github.com/JohanFalt/Foundry_WoD20/files/15072022/de.json)
