### ISSUE TITLE
[[Feature Request]] Enable Direct Control of Trait Caps for Powers

### ISSUE THREAD

**Issue by RinVindor** [JohanFalt/Foundry_WoD20#835]
**Is your feature request related to a problem? Please describe.**
I'm trying to make the Vozhd from the V20 Core but it calls for Potence 6, currently you can't directly control the max cap for power related items only Abilities and Attributes, so alas my poor Vozhd is stuck with Potence 5.

**Describe the solution you'd like**
Set if free and let us raise that cap to whatever we need 😂

**Comment by JohanFalt** [comment]
This is a creature I assume?

**Comment by JohanFalt** [comment]
- [ ] Setting
- [ ] Patch if setting changes

**Comment by RinVindor** [comment]
Sorry I had only just now saw this, yeah its a creature though having the option in general for all splats would be great, one of the books I wrote Elder Discipline Compilation has a merit that lets the user pick a single Discipline and have it be capable of being 1 dot higher than normal, letting a 13th Gen have a single Discipline where they could buy 6th dot powers for example.
