### ISSUE TITLE
[Request] Resizable Text Areas

### ISSUE THREAD

**Issue by BokuNC** [JohanFalt/Foundry_WoD20#837]
**Is your feature request related to a problem? Please describe.**
Currently, the text areas arent resizable or sensitive to the amount of content it holds, it creates some very narrow windows to edit larger blocks of informations for items, backgrounds and other things. 

**Describe the solution you'd like**
It would be very helpful for preparation, reading and clarity if the text boxes were resizable.

**Comment by Kad-Caiel** [comment]
I believe this has been discussed in the past, but yes, it would be great. 
For example, manage a table in System area to create a simple Number of successes/Effect paragraph is a bit annoying, since you have to do it only with only a few lines in height.

**Comment by BokuNC** [comment]
Exacty, even copying and pasting text into them is bothersome, i don't know if its something CSS only or if its HTML based, i may look into it deeply sometime.

**Comment by BokuNC** [comment]
Yeah, its HTML based. As it is, for the editor side, a "resize: vertical;" in front of the "height: 150px;" is enough to let you, at least, drag its size up to where you find it comfortable. 
When closed, we could use some automation/content-aware, so it just envelops whatever is there. 

I'm not even trying to change how the sheet work, just the item sheets.

I may try some bigger changes and, if it works, do a pull request later.

**Comment by BokuNC** [comment]
Yeah, you can force a CSS rule to ignore the html defined ones. The solution i found is adding through CustomCSS:
`.editor {
	resize: vertical;
}

.tox {
	height: 100% !important;
}	
`

For now, its enough to enlarge the boxes while editing. It may be possible to do something similar with the locked side. Still investigating. 

It could work on editor.css
