### ISSUE TITLE
[Bug] Small bug in Breed (Werewolf)

### ISSUE THREAD

**Issue by Kad-Caiel** [JohanFalt/Foundry_WoD20#838]
With the sheet unlocked (Werewolf), Breed is ok, the select list has translated names (Homínido).
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/f5a0190f-9d62-4a59-95aa-a5435fb174ad)

But when you lock the sheet, the value changes to Homid, in english, ignoring lang setting. 
![imagen](https://github.com/JohanFalt/Foundry_WoD20/assets/114583468/c24a7973-ee88-4613-8740-260ec7b5fd46)

**Comment by JohanFalt** [comment]
This was a bigger problem as the data of the stored value is the name not the localization.

**Comment by JohanFalt** [comment]
Fixed:

- [ ] Werewolf
- [ ] Ajaba
- [ ] Ananasi
- [ ] Apis
