### ISSUE TITLE
[[Feature Request]] More Flexible Width

### ISSUE THREAD

**Issue by BokuNC** [JohanFalt/Foundry_WoD20#841]
**Is your feature request related to a problem? Please describe.**
As they are right now, the character sheets can be scaled vertically and scrolled for access to content that may get hidden. However, the same isn't true for horizontal movement, you have a minimum value that shows all the content, but makes it impossible to use the sheet if you need a smaller space, let's say, in a small monitor, tablet or smartphone. 

**Describe the solution you'd like**
As we have the scroll bar vertically (and without the content being squashed by it), it would be amazing if we could also scale down the sheet horizontally, without the formating breaking completely. A scroll bar would suffice.

That said, i have no idea how hard would that be to implement.

**Comment by JohanFalt** [comment]
Added a few rules for screen of 1024px and lower, will help but not fully.
