### ISSUE TITLE
Bonuses Not Being Saved for GIfts

### ISSUE THREAD

**Issue by tobenamed** [JohanFalt/Foundry_WoD20#844]
**Have you tested without modules**

**Describe the bug**
I have created a Gift for the WtA sheet. I have it organized in a compendium. The gift is created and the rest of the entry is saved. I go to make bonus for the associated power and every time i go to make it, it says fail to save
**To Reproduce**
1. Create A Power Item
2. Choose Werewolf
3. Make a gift
4. Add a bonus to the gift
5.  Edit the Bonus of the gift 
6.  attempt to save the bonus
7.  Fails to Save

**Screenshots**
![bug](https://github.com/JohanFalt/Foundry_WoD20/assets/19497518/442bb4f6-080c-4bef-9cbc-d01dc6b18f5f)

**Versions of software:**
- 11.315
- 3.1.5

**Comment by JohanFalt** [comment]
The gift is in the compendium?
