### ISSUE TITLE
[Bug] Abilities with less than 4 dots getting yellow pip for specialization

### ISSUE THREAD

**Issue by SeaSaltSong** [JohanFalt/Foundry_WoD20#846]
**Have you tested without modules**
Yes

**Describe the bug**
On the Vampire character sheets (I am unsure if this applies to all sheets) some abilities get a yellow (!) pip that usually means that the specialization field is empty. This appears if there is at least 1 dot in the ability, and should not appear until there are at least 4 dots in the ability.

The specific abilities in question are:

- Expression
- Craft
- Performance
- Academics
- Law
- Science
- Technology

This was tested on a fresh character sheet.

**To Reproduce**
1. create a new actor (this is an issue noticed on vampires, but might be on other sheets as well)
2. Assign at least 1 dot, but less than 4 in the effected ability
3. Yellow dot prematurely appears

**Screenshots**
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/117007321/728ec288-e5ed-465a-a434-b46461d32dc9)

**Versions of software:**
- Foundry 11
- Most recent World of Darkness (3.3.5)

**Comment by JohanFalt** [comment]
It is. Some abilities can be specified from start.
