### ISSUE TITLE
A little problemn changing the sphere to the technocracy version

### ISSUE THREAD

**Issue by ChaoxRPG** [JohanFalt/Foundry_WoD20#848]
**Describe the bug**
You can´t change the sphere to the technocracy version (like Spirit to Dimensional Science)

**To Reproduce**
You can go to spheres, and click on  "change for technocracy version" but when you try to save it, it just won't work

**Screenshots**
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/167710261/6e2b3a9b-a071-4751-962d-d749aa77a73f)

**Comment by Muji-k** [comment]
workaround:
put at least four points in the sphere you are trying to change, open up the edit box,
check the  "Use Technocracy version", save, close it, and remove the added points if necessary.

this feature seems to be somewhat tied to the specialty, so it will only save if it has enough point to have an specialty.
but you can trick the system with the workaround above

**Comment by ChaoxRPG** [comment]
Thanks a lot :D, love your work
