### ISSUE TITLE
Is it possible for me to add languages on my own?

### ISSUE THREAD

**Issue by derek-j-jones** [JohanFalt/Foundry_WoD20#856]
Unfortunately, due to the lack of Ukrainian in this system, there are some uncomfortable moments during the game. I would like to add this language in my game, but I'm not sure what I can change and where to make it work, I would be grateful if you could tell me.

**Comment by JohanFalt** [comment]
Only way is if Foundry supports the language. I took a look and which language setting is Ukrainian?

**Comment by derek-j-jones** [comment]
Yes, Foundry has a Ukrainian language https://github.com/GMonlineua/FoundryVTT_UA

**Comment by JohanFalt** [comment]
Yes but what language setting is it? I can't find the name  - Ukrainian so I'm guessing it is called something else.

**Comment by derek-j-jones** [comment]
![image](https://github.com/JohanFalt/Foundry_WoD20/assets/111453014/503bb82c-df3e-4d73-9471-a1d979cb9e71)

Is that what you're asking?

**Comment by Veilza** [comment]
> Yes but what language setting is it? I can't find the name - Ukrainian so I'm guessing it is called something else.

If you're looking for the language code, it's "uk" that's used for Ukrainian localization. Foundry by default doesn't support it, but that's what the localization module and international standard uses.

Even if Foundry doesn't innately support it, you can still add a localization file for it, also. Set it up the same as the others, like I did in the WoD5 module:

`
    {
      "lang": "uk",
      "name": "Core (Ukrainian)",
      "path": "lang/uk/core-uk.json",
      "flags": {}
    }`

**Comment by JohanFalt** [comment]
In that it is quite easy. I attach the language file to this message so what you need to do is to translate what words you want to have in Ukrainian and then I add the language as an option in next version.

[uk.json](https://github.com/JohanFalt/Foundry_WoD20/files/15446229/uk.json)

**Comment by derek-j-jones** [comment]
> Even if Foundry doesn't innately support it, you can still add a localization file for it, also. Set it up the same as the others, like I did in the WoD5 module:

I did this before writing here yesterday and even entered some terms with translation, I wanted to have at least a character table in Ukrainian, but I'm sure I missed something because it didn't appear, even though other systems with "uk" work fine. In general, filling out the uk.json file by itself is not a big deal, but it won't make sense if it doesn't work, and I'm not sure how to add a language because although I tried to follow how other languages are entered, it didn't work.
