### ISSUE TITLE
Checkboxes not activating

### ISSUE THREAD

**Issue by R00k0fShad0ws** [JohanFalt/Foundry_WoD20#858]
**Have you tested without modules**
Ywa
**Describe the bug**
Check boxes for armor, disciplines, backgrounds wont activate. 

**To Reproduce**
1. Go to 'Combat'
2. Add armor or fortitude to armor
3. Click on 'equip checkbox'

**Screenshots**
![Screenshot 2024-06-10 092744](https://github.com/JohanFalt/Foundry_WoD20/assets/172292248/5c58dedf-ec65-4233-a7d2-1cdea208ae49)

**Versions of software:**
- Version of Foundry VTT - 12.327
- Version of World of Darkness v20  - 4.0.0

**Comment by JohanFalt** [comment]
Found problem, same problem to activate powers.

Should have a new version out tomorrow.

**Comment by R00k0fShad0ws** [comment]
Just found another that might be connected. Adding bonuses only allows attribute modifier.
