### ISSUE TITLE
Token on vampire character sheet get desync when double click 

### ISSUE THREAD

**Issue by zanvel** [JohanFalt/Foundry_WoD20#864]
**Have you tested without modules**

**Describe the bug**
When i am on my character sheet (a vampire one) and do modifications i happen to want to double click on the token to reopen it to see that the one i open was named [token] "Character name" and the modifications weren't there

**To Reproduce**
1. Create a vampire character sheet
2. Associate a token to this sheet
3. when done put the sheet's token on the map
4. Double click on the token
5. Open the Character sheet
6. See the bug there is to character sheet open of the same character one for the token and the original one

**Screenshots**

**Versions of software:**
- Version of Foundry VTT 12 build 327
- Version of World of Darkness v20 4.0.1
![Bug vampire character sheet](https://github.com/JohanFalt/Foundry_WoD20/assets/87309008/1712286c-5b5e-48f5-b9e1-3c938dc0ba5f)

**Comment by JohanFalt** [comment]
That is from what I know the normal handling of Foundry. If you have linked your token to a sheet then there will not be a token up in the cornor.

Its the Link Actor Data setting.

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/57871596/833ea591-1853-4aaf-88f0-87396199243b)
