### ISSUE TITLE
Mortal sheet changes

### ISSUE THREAD

**Issue by Moradion** [JohanFalt/Foundry_WoD20#87]
Rework of the Mortal sheet to unify and use it too as a Hunter sheet.

See examples from mrgone sheet
[Mortals_V20_Interactive.pdf](https://github.com/JohanFalt/Foundry_WoD20/files/8831787/Mortals_V20_Interactive.pdf)

**Comment by JohanFalt** [comment]
Faith is fixed with Other Trait.
