### ISSUE TITLE
Help with text  css size config for mage rotes

### ISSUE THREAD

**Issue by jacksands** [JohanFalt/Foundry_WoD20#872]
I need a little help to change the css on the rotes list so I can see the entire name of the rotes...

I don't mind having a long list in a single row, as long as I can make the mane as long as possible..  there is a lot of lost space as it is...

can someone help, please?

I use custom CSS module and have very basic knowledge about CSS, already tried to change it and failed...

![image](https://github.com/JohanFalt/Foundry_WoD20/assets/7229143/39f96227-fc1f-44da-a6fb-29142a481fe7)

**Comment by JohanFalt** [comment]
That is actually by design. Any rote name longer than (I want to recall) 20 character gets shortened like that. Full name should be visible if you hover your cursor over it.

**Comment by jacksands** [comment]
I understand that, don't want for you to change your system, just for a personal change using custom css, can that be done?

**Comment by JohanFalt** [comment]
No using css can’t show the entire name as it is not limited by width but length of the name.

**Comment by jacksands** [comment]
ok, no problem, thanks for the answers and the patience!
