### ISSUE TITLE
Storyteller 20th anniversary system rules summery

### ISSUE THREAD

**Issue by Moradion** [JohanFalt/Foundry_WoD20#88]
**Difficulties**

- Range from 2 to 10 (but generally between 3 and 9)
- 10 always a success, no matter the difficulty number
- 1 cancels out a success

**Degrees of Success**

- 1 and 2 successes = Marginal success
- 3+ successes = Complete success

**Failure**

- If score no successes or all successes denied thru one’s

**Botches**

- If none of the dice comes up a success, and one or more dice are dice showing one

Note: Botche’s don’t count for soak and damage rolls

**Automatic Success**

- Number of dice pool is equal to the difficulty (can’t be used in Combat or under pressure)
- Spend of a Willpower point = Marginal success (with one success)

**Trying it Again**

- The difficulty of the roll increase with every try by one

**Willpower**

- Send of one point Willpower, per turn, ignored wound penalties

**Comment by JohanFalt** [comment]
The only differing from what is implemented is that the System has as minimum difficulty of 3.
