### ISSUE TITLE
Vampire:TM 20th Blood Pool and Points

### ISSUE THREAD

**Issue by Moradion** [JohanFalt/Foundry_WoD20#89]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/Moradion/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/Moradion/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/Moradion/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE style='tab-interval:35.4pt;word-wrap:break-word'>

<p class=MsoNormal><b><span lang=EN-US style='mso-ansi-language:EN-US'>Blood Pool
and Blood Points<o:p></o:p></span></b></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Resource
for vampires, to healing, weak up, disciplines, extend their physical attributes
and guhling<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Blood Pool
range from 1 to 50 (but generally 10, 13th generation), see table below.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Note: Blood
Pool, Blood Points and Generation is an important value for vampires and should
be part of the sheet. This can change as the story progresses (Diablerie)<o:p></o:p></span></p>

Generation | Blood Pool Max. | Use of Blood Points per Turn
-- | -- | --
Third | ??? | ???
Fourth | 50 | 10
Fifth | 40 | 8
Sixth | 30 | 6
Seventh | 20 | 4
Eight | 15 | 3
Ninth | 14 | 2
Tenth | 13 | 1
Eleventh | 12 | 1
Twelfth | 11 | 1
Thirteenth | 10 | 1
Fourteenth | 10 (only can use 8 for use1) | 1
Fifteenth | 10 (only can use 6 for us²) | 1

</body>

</html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/Moradion/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/Moradion/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/Moradion/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE style='tab-interval:35.4pt;word-wrap:break-word'>

<p class=MsoNormal><sup><span lang=EN-US style='mso-ansi-language:EN-US'>1</span></sup><span
lang=EN-US style='mso-ansi-language:EN-US'> Only eight of them may be used to
heal wounds, power Disciplines, raise Attributes, etc. You can still use the
final two blood points for other purposes, though. The blood point costs of nightly
rising, creating and sustaining ghouls, and creating blood bonds remains the same
as for other vampires. You cannot raise any Discipline above four dots.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>² Only six
of your 10 blood points can be used for Disciplines, healing or raising Attributes.
For these functions, you must expend two blood points to obtain the effect a
normal vampire would achieve with one. (The cost for nightly rising remains a
single blood point.) What’s more, you cannot create or sustain ghouls, create a
blood bond, or sire a vampiric child. You can use the remaining four blood
points to survive through the day and wake up each night, nothing more. You
cannot raise any Discipline above three dots.<o:p></o:p></span></p>

<p class=MsoNormal><b><span lang=EN-US style='mso-ansi-language:EN-US'>Earning blood
pool<o:p></o:p></span></b></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Drinking
from a vessel and other vampires, with the crossover of the WoD Systems Blood
pool should be an option (Suggestion: Per checkbox) for other Sheets to count their
Blood pool to. The value of the Blood pool of a vessel, change with the wound
state. The vessel has one fewer blood point in his system for each health level
of damage he currently suffers.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>A list for
vessels and their max. Blood Pool<o:p></o:p></span></p>

Vessel | Blood Pool of the Vessel
-- | --
Vampire | Different, see table above
Werewolf’s | 20
Adult Humans (Mages, Changelings,   Mummy’s, Daemons and Wrights with Body, too) | 10
Child | 5
Animals | Different, between ¼ to 10

</body>

</html>

**Comment by JohanFalt** [comment]
A small question about my implementation of gen 14 and 15 but we see how things falls out.

**Comment by HuevoBendito** [comment]
Sorry if I needed to make a new post (will do so if needed); however, I noticed that 14th and 15th generation characters have fewer Blood Points even though they should have 10 total.
