### ISSUE TITLE
Cannot Properly Edit 'Max rating on Powers'

### ISSUE THREAD

**Issue by HuevoBendito** [JohanFalt/Foundry_WoD20#908]
**Have you tested without modules**
Yes

**Describe the bug**
Attempting to edit 'Max rating on Powers' results in the dialogue box returning to **- Select -**

**To Reproduce**
1. Add a Discipline power to a V20 character
2. Edit 'Max rating on Powers' (un/locking does not affect this)
3. See error

**Screenshots**

**Versions of software:**
- v12 Stable 7 (Build 331)
- World of Darkness v20 4.1.1.

**Comment by JohanFalt** [comment]
Can't repoduce, did the following:

- Created Vampire character
- Unlocked the sheet.
- Set the generation to 5 (all abilities has a highest value of 8)
- Creates a discipline, it is naturally set to 5.
- Unlocks the discipline.
- Shifts the max value from 5 to 9.
- The discipline has a max rating of 9 in the sheet.

**Comment by HuevoBendito** [comment]
> Can't repoduce, did the following:
> 
> * Created Vampire character
> * Unlocked the sheet.
> * Set the generation to 5 (all abilities has a highest value of 8)
> * Creates a discipline, it is naturally set to 5.
> * Unlocks the discipline.
> * Shifts the max value from 5 to 9.
> * The discipline has a max rating of 9 in the sheet.

Yeah, changing that part on a Discipline works, but if I try to change the 'Max ratings on Powers' for a Discipline power, it doesn't work.

**Comment by JohanFalt** [comment]
You mean the one seen below? Me too.

![{7E9A776A-67B2-4C47-9DEA-B818FD3510AA}](https://github.com/user-attachments/assets/5cc418dd-b28d-4919-ade7-4c2c2471f90b)

**Comment by HuevoBendito** [comment]
> You mean the one seen below? Me too.
> 
> ![{7E9A776A-67B2-4C47-9DEA-B818FD3510AA}](https://private-user-images.githubusercontent.com/57871596/393221377-5cc418dd-b28d-4919-ade7-4c2c2471f90b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MzE2MjgsIm5iZiI6MTczMzUzMTMyOCwicGF0aCI6Ii81Nzg3MTU5Ni8zOTMyMjEzNzctNWNjNDE4ZGQtYjI4ZC00OTE5LWFkZTctNGMyYzI0NzFmOTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDAwMjg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZjM5OWRiMjI5NDY1Y2UxZmI3YjYxM2JiMTUwNGMxMjhmNDQwMWU4NjQ5YWU4ZDdlMGYwYWUxMTI5ZmIwMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KJpN-4ZBAhXWvcnFZ32MWwAXMSOhesEhTQjNGC4GT_w)

Sorry. Again, I'm referring to Discipline **powers**, e.g., 'New discipline power' or 'Beckoning' on your sheet, not actual Disciplines.

**Comment by JohanFalt** [comment]
No can still not trigger. Is it different if you create a new vampire or use the old ones?

**Comment by HuevoBendito** [comment]
> No can still not trigger. Is it different if you create a new vampire or use the old ones?

No, it's the same for either of them. In your most recent picture in this thread, I'm talking about modifying stuff like 'Beckoning' or 'New discipline power,' by the way.

**Comment by JohanFalt** [comment]
Oh that is a visual glitch. Discipline Powers shouldn't see that box as it is a Discipline trait.
